# - Find LIBICONV
# Find the native LIBICONV includes and library
# This module defines
#  LIBICONV_INCLUDE_DIR, where to find iconv.h, etc.
#  LIBICONV_LIBRARIES, the libraries needed to use LIBICONV.
#  LIBICONV_FOUND, If false, do not try to use LIBICONV.
# also defined, but not for general use are
#  LIBICONV_LIBRARY, where to find the LIBICONV library.

FIND_PATH(LIBICONV_INCLUDE_DIR iconv.h)

SET(LIBICONV_NAMES ${LIBICONV_NAMES} iconv)
FIND_LIBRARY(LIBICONV_LIBRARY NAMES ${LIBICONV_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set LIBICONV_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBICONV DEFAULT_MSG LIBICONV_LIBRARY LIBICONV_INCLUDE_DIR)

IF(LIBICONV_FOUND)
  SET(LIBICONV_LIBRARIES ${LIBICONV_LIBRARY})
  GET_FILENAME_COMPONENT(LIBICONV_LINK_DIRECTORIES ${LIBICONV_LIBRARY} PATH)
ENDIF(LIBICONV_FOUND)

# Deprecated declarations.
SET (NATIVE_LIBICONV_INCLUDE_PATH ${LIBICONV_INCLUDE_DIR} )
IF(LIBICONV_LIBRARY)
  GET_FILENAME_COMPONENT (NATIVE_LIBICONV_LIB_PATH ${LIBICONV_LIBRARY} PATH)
ENDIF(LIBICONV_LIBRARY)

MARK_AS_ADVANCED(LIBICONV_LIBRARY LIBICONV_INCLUDE_DIR LIBICONV_LINK_DIRECTORIES)
