Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/ColorDataspace.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/ColorDataspace.cpp File Reference
#include "ColorDataspace.h"
Functions
double hls_value (double n1, double n2, double hue)
Function Documentation
double hls_value (double n1, double n2, double hue)
Definition at line 13 of file ColorDataspace.cpp.
Referenced by HSLUnit::convertToNeutral(), hls2rgb(), and hsl2rgb().