Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/DataspaceLib.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/DataspaceLib.cpp File Reference
#include "DataspaceLib.h"
#include "AngleDataspace.h"
#include "ColorDataspace.h"
#include "DistanceDataspace.h"
#include "GainDataspace.h"
#include "NoneDataspace.h"
#include "PitchDataspace.h"
#include "PositionDataspace.h"
#include "TemperatureDataspace.h"
#include "TimeDataspace.h"
Functions
JamomaError jamoma_getDataspace (t_symbol *dataspaceName, DataspaceLib **dataspace)
Create a dataspace object by specifying the name of the dataspace you want as a symbol.
void jamoma_getDataspaceList (long *numDataspaces, t_symbol ***dataspaceNames)
Get a list of names of all the available dataspaces.
Function Documentation
JamomaError jamoma_getDataspace (t_symbol * dataspaceName, DataspaceLib ** dataspace)
Create a dataspace object by specifying the name of the dataspace you want as a symbol.
Definition at line 118 of file DataspaceLib.cpp.
References JAMOMA_ERR_NONE.
Referenced by dataspace_setDataspace().
void jamoma_getDataspaceList (long * numDataspaces, t_symbol *** dataspaceNames)
Get a list of names of all the available dataspaces.
The caller of this function is responsible for freeing memory allocated by this call.
Definition at line 157 of file DataspaceLib.cpp.
Referenced by dataspace_getDataspaces(), and main().