Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/source/JamomaObject.h File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/source/JamomaObject.h File Reference
#include "ext.h"
#include "ext_obex.h"
#include "ext_common.h"
#include "ext_strings.h"
#include "ext_critical.h"
#include "z_dsp.h"
#include "commonsyms.h"
Classes
struct t_jamoma_object
Functions
void jamoma_object_initclass (void)
t_object * jamoma_object_new ()
void jamoma_object_free (t_jamoma_object *obj)
Function Documentation
void jamoma_object_free (t_jamoma_object * obj)
Definition at line 53 of file JamomaObject.cpp.
Referenced by jamoma_object_initclass().
void jamoma_object_initclass (void)
Definition at line 20 of file JamomaObject.cpp.
References jamoma_object_free(), jamoma_object_new(), and s_jamoma_class.
t_object* jamoma_object_new ()
Definition at line 43 of file JamomaObject.cpp.
References s_jamoma_class.
Referenced by jamoma_object_initclass().