Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/source/JamomaObject.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/source/JamomaObject.cpp File Reference
#include "JamomaObject.h"
Functions
void jamoma_object_initclass (void)
t_object * jamoma_object_new ()
void jamoma_object_free (t_jamoma_object *obj)
Variables
static t_class * s_jamoma_class
static t_object * s_jamoma_object
Function Documentation
void jamoma_object_free (t_jamoma_object * obj)
Definition at line 53 of file JamomaObject.cpp.
Referenced by jamoma_object_initclass().
void jamoma_object_initclass (void)
Definition at line 20 of file JamomaObject.cpp.
References jamoma_object_free(), jamoma_object_new(), and s_jamoma_class.
t_object* jamoma_object_new ()
Definition at line 43 of file JamomaObject.cpp.
References s_jamoma_class.
Referenced by jamoma_object_initclass().
Variable Documentation
t_class* s_jamoma_class [static]
Definition at line 14 of file JamomaObject.cpp.
Referenced by jamoma_object_initclass(), and jamoma_object_new().
t_object* s_jamoma_object [static]
Definition at line 15 of file JamomaObject.cpp.