Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/source/Jamoma.h File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/source/Jamoma.h File Reference
#include "ext.h"
#include "ext_obex.h"
#include "ext_common.h"
#include "ext_strings.h"
#include "ext_critical.h"
#include "z_dsp.h"
#include "commonsyms.h"
#include <math.h>
#include <stdlib.h>
#include "TTAudioObject.h"
#include "TTAudioSignal.h"
#include "TTSymbol.h"
#include "TTValue.h"
#include "jcom.core.h"
#include "jcom.list.h"
#include "jcom.io.h"
#include "jcom.sendreceive.h"
#include "JamomaTypes.h"
#include "JamomaClock.h"
#include "JamomaScheduler.h"
#include "JamomaSymbols.h"
#include "DataspaceLib.h"
#include "FunctionLib.h"
#include "RampLib.h"
Defines
#define JAMOMA_VERSION "0.5 Dev"
#define NO 0
#define YES 1
#define JAMOMA_UNIT_HEIGHT 70.0
#define JAMOMA_UNIT_WIDTH 150.0
#define JAMOMA_MENU_FONT "Arial"
#define JAMOMA_MENU_FONTSIZE 10.0
#define JAMOMA_DEFAULT_FONT "Verdana"
#define JAMOMA_DEFAULT_FONTSIZE 8.0
#define JAMOMA_BUTTON_FONT JAMOMA_DEFAULT_FONT
Functions
void jamoma_init (void)
t_max_err jamoma_hub_register (t_symbol *name, t_object *hub)
void jamoma_hub_remove (t_symbol *name)
t_object * jamoma_get_hub_for_module_named (t_symbol *name)
void jamoma_get_all_module_names (long *numModules, t_symbol ***moduleNames)
t_object * jamoma_object_getpatcher (t_object *obj)
t_symbol * jamoma_patcher_getcontext (t_object *patcher)
void jamoma_patcher_getargs (t_object *patcher, long *argc, t_atom **argv)
t_symbol * jamoma_patcher_getvarname (t_object *patcher)
void jamoma_dsp (t_object *, t_signal **sp, short *count)
void jamoma_class_attr_new (t_class *c, char *attrName, t_symbol *attrType, method setter, method getter, long offset)
void jamoma_class_attr_array_new (t_class *c, char *attrName, t_symbol *attrType, long list_size, method setter, method getter, long sizeOffset, long offset)
void jamoma_class_attr_get (t_object *o, t_symbol *attrName, long, t_atom *)
Variables
t_object * obj_jamoma_clock
t_object * obj_jamoma_scheduler
bool max5
Define Documentation
#define JAMOMA_BUTTON_FONT JAMOMA_DEFAULT_FONT
Definition at line 59 of file Jamoma.h.
Referenced by ui_paint().
#define JAMOMA_DEFAULT_FONT "Verdana"
Definition at line 57 of file Jamoma.h.
Referenced by main(), and paramui_paint().
#define JAMOMA_DEFAULT_FONTSIZE 8.0
Definition at line 58 of file Jamoma.h.
Referenced by main(), and paramui_paint().
#define JAMOMA_MENU_FONT "Arial"
Definition at line 55 of file Jamoma.h.
Referenced by paramui_menu_do(), ui_menu_do(), and ui_refmenu_do().
#define JAMOMA_MENU_FONTSIZE 10.0
Definition at line 56 of file Jamoma.h.
Referenced by paramui_menu_do(), ui_menu_do(), and ui_refmenu_do().
#define JAMOMA_UNIT_HEIGHT 70.0
Definition at line 53 of file Jamoma.h.
Referenced by ui_oksize().
#define JAMOMA_UNIT_WIDTH 150.0
Definition at line 54 of file Jamoma.h.
Referenced by ui_oksize().
#define JAMOMA_VERSION "0.5 Dev"
Definition at line 14 of file Jamoma.h.
Referenced by jamoma_init().
#define NO 0
Definition at line 46 of file Jamoma.h.
#define YES 1
Definition at line 50 of file Jamoma.h.
Function Documentation
void jamoma_class_attr_array_new (t_class * c, char * attrName, t_symbol * attrType, long list_size, method setter, method getter, long sizeOffset, long offset)
Definition at line 266 of file Jamoma.cpp.
References jamoma_class_attr_get().
Referenced by jcom_core_subscriber_classinit_extended(), and main().
void jamoma_class_attr_get (t_object * o, t_symbol * attrName, long , t_atom *)
Definition at line 281 of file Jamoma.cpp.
References t_jcom_core_subscriber_common::attr_name, t_jcom_core_subscriber_common::hub, and ps_feedback.
Referenced by jamoma_class_attr_array_new(), and jamoma_class_attr_new().
void jamoma_class_attr_new (t_class * c, char * attrName, t_symbol * attrType, method setter, method getter, long offset)
Definition at line 251 of file Jamoma.cpp.
References jamoma_class_attr_get().
Referenced by jcom_core_subscriber_classinit_common(), jcom_core_subscriber_classinit_extended(), and main().
void jamoma_dsp (t_object * , t_signal ** sp, short * count)
Definition at line 239 of file Jamoma.cpp.
References jamoma_clock_dsp().
Referenced by main(), and phasor_dsp().
void jamoma_get_all_module_names (long * numModules, t_symbol *** moduleNames)
Definition at line 88 of file Jamoma.cpp.
References hash_modules.
Referenced by audioreceive_bang(), and audiosend_bang().
t_object* jamoma_get_hub_for_module_named (t_symbol * name)
Definition at line 79 of file Jamoma.cpp.
References hash_modules.
Referenced by audioreceive_attr_settarget(), audioreceive_dsp(), audiosend_attr_settarget(), and audiosend_dsp().
t_max_err jamoma_hub_register (t_symbol * name, t_object * hub)
Definition at line 59 of file Jamoma.cpp.
References hash_modules.
Referenced by hub_examine_context().
void jamoma_hub_remove (t_symbol * name)
Definition at line 73 of file Jamoma.cpp.
References hash_modules.
Referenced by hub_free().
void jamoma_init (void)
Definition at line 28 of file Jamoma.cpp.
References hash_modules, initialized, jamoma_clock_initclass(), jamoma_scheduler_initclass(), JAMOMA_VERSION, jamomaSymbolsInit(), max5, obj_jamoma_clock, obj_jamoma_scheduler, receive_initclass(), receivemaster_initclass(), and send_initclass().
Referenced by main().
t_object* jamoma_object_getpatcher (t_object * obj)
Definition at line 94 of file Jamoma.cpp.
References max5.
Referenced by hub_new(), and jcom_core_subscriber_new_common().
void jamoma_patcher_getargs (t_object * patcher, long * argc, t_atom ** argv)
Definition at line 159 of file Jamoma.cpp.
References t_bpatcher::b_argc, t_bpatcher::b_argv, jamoma_patcher_getcontext(), max5, and ps_box.
Referenced by hub_examine_context().
t_symbol* jamoma_patcher_getcontext (t_object * patcher)
Definition at line 106 of file Jamoma.cpp.
References max5, and ps_box.
Referenced by hub_examine_context(), and jamoma_patcher_getargs().
t_symbol* jamoma_patcher_getvarname (t_object * patcher)
Definition at line 215 of file Jamoma.cpp.
References max5.
Referenced by hub_examine_context().
Variable Documentation
bool max5
Definition at line 22 of file Jamoma.cpp.
Referenced by jamoma_init(), jamoma_object_getpatcher(), jamoma_patcher_getargs(), jamoma_patcher_getcontext(), jamoma_patcher_getvarname(), and jcom_core_subscribe().
t_object* obj_jamoma_clock
Definition at line 20 of file Jamoma.cpp.
Referenced by jamoma_clock_dsp(), jamoma_init(), and jamoma_scheduler_getphase().
t_object* obj_jamoma_scheduler
Definition at line 21 of file Jamoma.cpp.
Referenced by jamoma_clock_perform(), jamoma_init(), jamoma_scheduler_delay(), jamoma_scheduler_getphase(), jamoma_scheduler_removeevent(), and jamoma_scheduler_rewind().