Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/source/JamomaScheduler.h File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/source/JamomaScheduler.h File Reference
#include "ext.h"
#include "ext_obex.h"
#include "z_dsp.h"
#include "commonsyms.h"
Classes
struct t_jamoma_event
struct t_jamoma_scheduler
Defines
#define DEFAULT_TICKS_PER_SECOND 1000.0
#define DEFAULT_SAMPLE_RATE 44100.0
#define JCOM_EVENT_PRIORITY_HIGH 1
#define JCOM_EVENT_PRIORITY_MEDIUM 2
#define JCOM_EVENT_PRIORITY_LOW 3
Functions
void jamoma_scheduler_initclass (void)
t_object * jamoma_scheduler_new (t_symbol *s, long argc, t_atom *argv)
void jamoma_scheduler_free (t_jamoma_scheduler *x)
void jamoma_scheduler_getphase (double period, double *phase, double *slope)
void jamoma_scheduler_rewind (t_jamoma_scheduler *x)
t_object * jamoma_scheduler_delay (t_object *client, t_object *jamoma_scheduler_obj, method callback, double *timevalue, long repeating, long priority)
void jamoma_scheduler_removeevent (t_jamoma_scheduler *x, t_object *event)
void jamoma_scheduler_moveevent (t_jamoma_scheduler *x, t_jamoma_event *event, double newtime)
void jamoma_scheduler_update (t_jamoma_scheduler *x, double *newTime)
void jamoma_scheduler_doevents (t_jamoma_scheduler *x)
t_jamoma_event * jamoma_event_new (t_jamoma_scheduler *owner, t_object *client, method callback, double *timevalue, long repeating, long priority)
void jamoma_event_free (t_jamoma_event *event)
void jamoma_event_send (t_jamoma_event *event)
void jamoma_event_dosend (t_jamoma_event *event)
Define Documentation
#define DEFAULT_SAMPLE_RATE 44100.0
Definition at line 21 of file JamomaScheduler.h.
#define DEFAULT_TICKS_PER_SECOND 1000.0
Definition at line 20 of file JamomaScheduler.h.
Referenced by jamoma_clock_perform(), jamoma_clock_tickstosamples(), and phasor_attr_setperiod().
#define JCOM_EVENT_PRIORITY_HIGH 1
Definition at line 23 of file JamomaScheduler.h.
Referenced by jamoma_event_send().
#define JCOM_EVENT_PRIORITY_LOW 3
Definition at line 25 of file JamomaScheduler.h.
Referenced by jamoma_event_free(), and jamoma_event_new().
#define JCOM_EVENT_PRIORITY_MEDIUM 2
Definition at line 24 of file JamomaScheduler.h.
Referenced by jamoma_event_free(), jamoma_event_new(), jamoma_event_send(), and jcom_metro_int().
Function Documentation
void jamoma_event_dosend (t_jamoma_event * event)
Definition at line 327 of file JamomaScheduler.cpp.
References t_jamoma_event::client, t_jamoma_event::delaytime, jamoma_scheduler_moveevent(), jamoma_scheduler_removeevent(), t_jamoma_event::owner, t_jamoma_event::repeating, and t_jamoma_event::targettime.
Referenced by jamoma_event_new(), and jamoma_event_send().
void jamoma_event_free (t_jamoma_event * event)
Definition at line 306 of file JamomaScheduler.cpp.
References JCOM_EVENT_PRIORITY_LOW, JCOM_EVENT_PRIORITY_MEDIUM, t_jamoma_event::priority, and t_jamoma_event::transfer_mechanism.
Referenced by jamoma_scheduler_removeevent().
t_jamoma_event* jamoma_event_new (t_jamoma_scheduler * owner, t_object * client, method callback, double * timevalue, long repeating, long priority)
Definition at line 281 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::current_time, jamoma_event_dosend(), JCOM_EVENT_PRIORITY_LOW, JCOM_EVENT_PRIORITY_MEDIUM, and t_jamoma_event::owner.
Referenced by jamoma_scheduler_delay().
void jamoma_event_send (t_jamoma_event * event)
Definition at line 316 of file JamomaScheduler.cpp.
References jamoma_event_dosend(), JCOM_EVENT_PRIORITY_HIGH, JCOM_EVENT_PRIORITY_MEDIUM, t_jamoma_event::priority, and t_jamoma_event::transfer_mechanism.
Referenced by jamoma_scheduler_doevents().
t_object* jamoma_scheduler_delay (t_object * client, t_object * jamoma_scheduler_obj, method callback, double * timevalue, long repeating, long priority)
Definition at line 137 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::event_head, t_jamoma_scheduler::event_tail, jamoma_event_new(), JAMOMA_SCHEDULER_LOCK, JAMOMA_SCHEDULER_UNLOCK, t_jamoma_event::next, obj_jamoma_scheduler, t_jamoma_event::prev, and t_jamoma_event::targettime.
Referenced by jcom_metro_int().
void jamoma_scheduler_doevents (t_jamoma_scheduler * x)
Definition at line 83 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::current_time, t_jamoma_scheduler::event_head, and jamoma_event_send().
Referenced by jamoma_scheduler_update().
void jamoma_scheduler_free (t_jamoma_scheduler * x)
Definition at line 57 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::event_head.
Referenced by jamoma_scheduler_initclass().
void jamoma_scheduler_getphase (double period, double * phase, double * slope)
Definition at line 116 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::current_time, jamoma_clock_tickstosamples(), obj_jamoma_clock, and obj_jamoma_scheduler.
Referenced by phasor_perform().
void jamoma_scheduler_initclass (void)
Definition at line 28 of file JamomaScheduler.cpp.
References class_jamoma_scheduler, jamoma_scheduler_free(), and jamoma_scheduler_new().
Referenced by jamoma_init().
void jamoma_scheduler_moveevent (t_jamoma_scheduler * x, t_jamoma_event * event, double newtime)
Definition at line 218 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::event_head, t_jamoma_scheduler::event_tail, JAMOMA_SCHEDULER_LOCK, JAMOMA_SCHEDULER_UNLOCK, t_jamoma_event::next, t_jamoma_event::prev, and t_jamoma_event::targettime.
Referenced by jamoma_event_dosend().
t_object* jamoma_scheduler_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 42 of file JamomaScheduler.cpp.
References class_jamoma_scheduler, t_jamoma_scheduler::event_head, t_jamoma_scheduler::event_tail, and jamoma_scheduler_rewind().
Referenced by jamoma_scheduler_initclass().
void jamoma_scheduler_removeevent (t_jamoma_scheduler * x, t_object * event)
Definition at line 186 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::event_head, t_jamoma_scheduler::event_tail, jamoma_event_free(), JAMOMA_SCHEDULER_LOCK, JAMOMA_SCHEDULER_UNLOCK, t_jamoma_event::next, obj_jamoma_scheduler, and t_jamoma_event::prev.
Referenced by jamoma_event_dosend(), jcom_metro_free(), and jcom_metro_int().
void jamoma_scheduler_rewind (t_jamoma_scheduler * x)
Definition at line 102 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::current_time, and obj_jamoma_scheduler.
Referenced by jamoma_scheduler_new(), and jcom_time_rewind().
void jamoma_scheduler_update (t_jamoma_scheduler * x, double * newTime)
Definition at line 71 of file JamomaScheduler.cpp.
References t_jamoma_scheduler::current_time, t_jamoma_scheduler::event_head, jamoma_scheduler_doevents(), and t_jamoma_event::targettime.
Referenced by jamoma_clock_perform().