Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/source/JamomaClock.h File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/source/JamomaClock.h File Reference
#include "ext.h"
#include "ext_obex.h"
#include "z_dsp.h"
#include "commonsyms.h"
Classes
struct t_jamoma_clock
Functions
void jamoma_clock_initclass (void)
t_object * jamoma_clock_new (t_symbol *s, long argc, t_atom *argv)
void jamoma_clock_free (t_jamoma_clock *x)
t_int * jamoma_clock_perform (t_int *w)
void jamoma_clock_dsp (t_jamoma_clock *x, t_signal **sp, short *count)
void jamoma_clock_setup_coreaudio (t_jamoma_clock *x)
void jamoma_clock_start (t_jamoma_clock *x)
void jamoma_clock_stop (t_jamoma_clock *x)
unsigned long long jamoma_clock_tickstosamples (t_object *o, double period)
Function Documentation
void jamoma_clock_dsp (t_jamoma_clock * x, t_signal ** sp, short * count)
Definition at line 92 of file JamomaClock.cpp.
References dsp_called, jamoma_clock_perform(), obj_jamoma_clock, t_jamoma_clock::one_over_sr, t_jamoma_clock::samples_per_block, and t_jamoma_clock::sr.
Referenced by jamoma_clock_initclass(), and jamoma_dsp().
void jamoma_clock_free (t_jamoma_clock * x)
Definition at line 60 of file JamomaClock.cpp.
References jamoma_clock_stop().
Referenced by jamoma_clock_initclass().
void jamoma_clock_initclass (void)
Definition at line 20 of file JamomaClock.cpp.
References class_jamoma_clock, jamoma_clock_dsp(), jamoma_clock_free(), and jamoma_clock_new().
Referenced by jamoma_init().
t_object* jamoma_clock_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 37 of file JamomaClock.cpp.
References class_jamoma_clock, DEFAULT_SAMPLE_RATE, jamoma_clock_setup_coreaudio(), t_jamoma_clock::one_over_sr, t_jamoma_clock::samples_per_block, and t_jamoma_clock::sr.
Referenced by jamoma_clock_initclass().
t_int* jamoma_clock_perform (t_int * w)
Definition at line 73 of file JamomaClock.cpp.
References t_jamoma_clock::current_samples, t_jamoma_clock::current_time, DEFAULT_TICKS_PER_SECOND, dsp_called, jamoma_scheduler_update(), obj_jamoma_scheduler, t_jamoma_clock::one_over_sr, and t_jamoma_clock::samples_per_block.
Referenced by jamoma_clock_dsp().
void jamoma_clock_setup_coreaudio (t_jamoma_clock * x)
Referenced by jamoma_clock_new().
void jamoma_clock_start (t_jamoma_clock * x)
void jamoma_clock_stop (t_jamoma_clock * x)
Referenced by jamoma_clock_free().
unsigned long long jamoma_clock_tickstosamples (t_object * o, double period)
Definition at line 290 of file JamomaClock.cpp.
References DEFAULT_TICKS_PER_SECOND, and t_jamoma_clock::sr.
Referenced by jamoma_scheduler_getphase().