Jamoma: GainDataspace Class Reference
GainDataspace Class Reference
#include <GainDataspace.h>
Public Member Functions
GainDataspace ()
~GainDataspace ()
Detailed Description
Definition at line 49 of file GainDataspace.h.
Constructor & Destructor Documentation
GainDataspace::GainDataspace ()
Definition at line 99 of file GainDataspace.cpp.
References DataspaceLib::neutralUnit, DataspaceLib::registerUnit(), DataspaceLib::setInputUnit(), and DataspaceLib::setOutputUnit().
GainDataspace::~GainDataspace ()
Definition at line 113 of file GainDataspace.cpp.
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/GainDataspace.h
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/GainDataspace.cpp