Jamoma: FunctionUnit Class Reference
FunctionUnit Class Reference
#include <FunctionLib.h>
Public Member Functions
FunctionUnit (const char *functionName)
constructor
virtual ~FunctionUnit ()
destructor
virtual double map (double x)=0
map x to y
Detailed Description
Definition at line 21 of file FunctionLib.h.
Constructor & Destructor Documentation
FunctionUnit::FunctionUnit (const char * functionName)
constructor
Definition at line 13 of file FunctionLib.cpp.
FunctionUnit::~FunctionUnit () [virtual]
destructor
Definition at line 18 of file FunctionLib.cpp.
Member Function Documentation
virtual double FunctionUnit::map (double x) [pure virtual]
map x to y
Implemented in CosineFunction, LinearFunction, LowpassFunction, PowerFunction, and TanhFunction.
Referenced by map_float(), SchedulerRamp::tick(), QueueRamp::tick(), and AsyncRamp::tick().
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/FunctionLib/FunctionLib.h
/Users/tim/dev/Jamoma/SourceCode/Framework/FunctionLib/FunctionLib.cpp