Jamoma: ColorDataspace Class Reference
ColorDataspace Class Reference
#include <ColorDataspace.h>
Public Member Functions
ColorDataspace ()
~ColorDataspace ()
Detailed Description
Definition at line 56 of file ColorDataspace.h.
Constructor & Destructor Documentation
ColorDataspace::ColorDataspace ()
Definition at line 314 of file ColorDataspace.cpp.
References DataspaceLib::neutralUnit, DataspaceLib::registerUnit(), DataspaceLib::setInputUnit(), and DataspaceLib::setOutputUnit().
ColorDataspace::~ColorDataspace ()
Definition at line 329 of file ColorDataspace.cpp.
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/ColorDataspace.h
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/ColorDataspace.cpp