Jamoma: PositionDataspace Class Reference
PositionDataspace Class Reference
#include <PositionDataspace.h>
Public Member Functions
PositionDataspace ()
~PositionDataspace ()
Detailed Description
Definition at line 77 of file PositionDataspace.h.
Constructor & Destructor Documentation
PositionDataspace::PositionDataspace ()
Definition at line 213 of file PositionDataspace.cpp.
References DataspaceLib::neutralUnit, DataspaceLib::registerUnit(), DataspaceLib::setInputUnit(), and DataspaceLib::setOutputUnit().
PositionDataspace::~PositionDataspace ()
Definition at line 235 of file PositionDataspace.cpp.
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/PositionDataspace.h
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/PositionDataspace.cpp