Jamoma: TemperatureDataspace Class Reference
TemperatureDataspace Class Reference
#include <TemperatureDataspace.h>
Public Member Functions
TemperatureDataspace ()
~TemperatureDataspace ()
Detailed Description
Definition at line 47 of file TemperatureDataspace.h.
Constructor & Destructor Documentation
TemperatureDataspace::TemperatureDataspace ()
Definition at line 84 of file TemperatureDataspace.cpp.
References DataspaceLib::neutralUnit, DataspaceLib::registerUnit(), DataspaceLib::setInputUnit(), and DataspaceLib::setOutputUnit().
TemperatureDataspace::~TemperatureDataspace ()
Definition at line 101 of file TemperatureDataspace.cpp.
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/TemperatureDataspace.h
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/TemperatureDataspace.cpp