Jamoma: TanhFunction Class Reference
TanhFunction Class Reference
#include <TanhFunction.h>
Public Member Functions
TanhFunction ()
virtual ~TanhFunction ()
Destructor.
double map (double x)
apply the function -- declared public so it can be called directly for efficiency
Private Member Functions
void calculateOutputScaling (void)
Calculate coefficients.
TTErr setWidth (const TTValue &value)
Calculate coefficients when this attr is set.
TTErr setOffset (const TTValue &value)
Calculate coefficients when this attr is set.
Private Attributes
TTFloat64 attrWidth
Parameter for function: y pow(x,pow(2,powerValue)).
TTFloat64 attrOffset
k = pow(2,powerValue)
double a
Internal coefficient.
double b
Internal coefficient.
double alpha
Internal coefficient.
double beta
Internal coefficient.
Detailed Description
Definition at line 20 of file TanhFunction.h.
Constructor & Destructor Documentation
TanhFunction::TanhFunction ()
Definition at line 13 of file TanhFunction.cpp.
References attrOffset, attrWidth, setOffset(), and setWidth().
TanhFunction::~TanhFunction () [virtual]
Destructor.
Definition at line 26 of file TanhFunction.cpp.
Member Function Documentation
void TanhFunction::calculateOutputScaling (void) [private]
Calculate coefficients.
Definition at line 53 of file TanhFunction.cpp.
References a, alpha, b, and beta.
Referenced by setOffset(), and setWidth().
TTErr TanhFunction::setWidth (const TTValue & value) [private]
Calculate coefficients when this attr is set.
Definition at line 41 of file TanhFunction.cpp.
References a, attrWidth, and calculateOutputScaling().
Referenced by TanhFunction().
TTErr TanhFunction::setOffset (const TTValue & value) [private]
Calculate coefficients when this attr is set.
Definition at line 32 of file TanhFunction.cpp.
References attrOffset, b, and calculateOutputScaling().
Referenced by TanhFunction().
double TanhFunction::map (double x) [virtual]
apply the function -- declared public so it can be called directly for efficiency
Implements FunctionUnit.
Definition at line 65 of file TanhFunction.cpp.
References a, alpha, b, and beta.
Member Data Documentation
TTFloat64 TanhFunction::attrWidth [private]
Parameter for function: y pow(x,pow(2,powerValue)).
Definition at line 22 of file TanhFunction.h.
Referenced by setWidth(), and TanhFunction().
TTFloat64 TanhFunction::attrOffset [private]
k = pow(2,powerValue)
Definition at line 23 of file TanhFunction.h.
Referenced by setOffset(), and TanhFunction().
double TanhFunction::a [private]
Internal coefficient.
Definition at line 24 of file TanhFunction.h.
Referenced by calculateOutputScaling(), map(), and setWidth().
double TanhFunction::b [private]
Internal coefficient.
Definition at line 25 of file TanhFunction.h.
Referenced by calculateOutputScaling(), map(), and setOffset().
double TanhFunction::alpha [private]
Internal coefficient.
Definition at line 26 of file TanhFunction.h.
Referenced by calculateOutputScaling(), and map().
double TanhFunction::beta [private]
Internal coefficient.
Definition at line 27 of file TanhFunction.h.
Referenced by calculateOutputScaling(), and map().
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/FunctionLib/TanhFunction.h
/Users/tim/dev/Jamoma/SourceCode/Framework/FunctionLib/TanhFunction.cpp