Jamoma: LowpassFunction Class Reference
LowpassFunction Class Reference
#include <LowpassFunction.h>
Public Member Functions
LowpassFunction ()
~LowpassFunction ()
double map (double x)
map x to y
Private Member Functions
TTErr clear ()
TTErr setCoefficient (const TTValue &newValue)
Private Attributes
TTFloat64 attrCoefficient
TTFloat64 one_minus_coefficient
TTFloat64 feedback
Detailed Description
Definition at line 20 of file LowpassFunction.h.
Constructor & Destructor Documentation
LowpassFunction::LowpassFunction ()
Definition at line 12 of file LowpassFunction.cpp.
References attrCoefficient, clear(), and setCoefficient().
LowpassFunction::~LowpassFunction ()
Definition at line 23 of file LowpassFunction.cpp.
Member Function Documentation
TTErr LowpassFunction::clear () [private]
Definition at line 36 of file LowpassFunction.cpp.
References feedback.
Referenced by LowpassFunction().
TTErr LowpassFunction::setCoefficient (const TTValue & newValue) [private]
Definition at line 43 of file LowpassFunction.cpp.
References attrCoefficient, and one_minus_coefficient.
Referenced by LowpassFunction().
double LowpassFunction::map (double x) [virtual]
map x to y
Implements FunctionUnit.
Definition at line 29 of file LowpassFunction.cpp.
References attrCoefficient, feedback, and one_minus_coefficient.
Member Data Documentation
TTFloat64 LowpassFunction::attrCoefficient [private]
Definition at line 22 of file LowpassFunction.h.
Referenced by LowpassFunction(), map(), and setCoefficient().
TTFloat64 LowpassFunction::one_minus_coefficient [private]
Definition at line 23 of file LowpassFunction.h.
Referenced by map(), and setCoefficient().
TTFloat64 LowpassFunction::feedback [private]
Definition at line 24 of file LowpassFunction.h.
Referenced by clear(), and map().
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/FunctionLib/LowpassFunction.h
/Users/tim/dev/Jamoma/SourceCode/Framework/FunctionLib/LowpassFunction.cpp