Jamoma: TimeDataspace Class Reference
TimeDataspace Class Reference
#include <TimeDataspace.h>
Public Member Functions
TimeDataspace ()
~TimeDataspace ()
Detailed Description
Definition at line 55 of file TimeDataspace.h.
Constructor & Destructor Documentation
TimeDataspace::TimeDataspace ()
Definition at line 89 of file TimeDataspace.cpp.
References DataspaceLib::neutralUnit, DataspaceLib::registerUnit(), DataspaceLib::setInputUnit(), and DataspaceLib::setOutputUnit().
TimeDataspace::~TimeDataspace ()
Definition at line 105 of file TimeDataspace.cpp.
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/TimeDataspace.h
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/TimeDataspace.cpp