Jamoma: FunctionLib Class Reference
FunctionLib Class Reference
#include <FunctionLib.h>
Static Public Member Functions
static JamomaError createUnit (const TTSymbol &unitName, FunctionUnit **unit)
Instantiate a function by name.
static void getUnitNames (TTValue &unitNames)
Return a list of all available functions.
Detailed Description
Definition at line 37 of file FunctionLib.h.
Member Function Documentation
JamomaError FunctionLib::createUnit (const TTSymbol & unitName, FunctionUnit ** unit) [static]
Instantiate a function by name.
Definition at line 44 of file FunctionLib.cpp.
References delete_functionunit(), and JAMOMA_ERR_NONE.
Referenced by map_doSetFunction(), and RampUnit::setFunction().
void FunctionLib::getUnitNames (TTValue & unitNames) [static]
Return a list of all available functions.
Definition at line 89 of file FunctionLib.cpp.
Referenced by main(), and map_getFunctions().
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/FunctionLib/FunctionLib.h
/Users/tim/dev/Jamoma/SourceCode/Framework/FunctionLib/FunctionLib.cpp