Jamoma: uiInternalObject Class Reference
uiInternalObject Class Reference
Public Member Functions
uiInternalObject (char *classname, char *subscribername, char *subscribertype, char *ramptype, char *description)
~uiInternalObject ()
void setAction (method aCallback, t_object *aCallbackArg)
Public Attributes
t_object * theObject
Detailed Description
Definition at line 16 of file jcom.ui.internals.cpp.
Constructor & Destructor Documentation
uiInternalObject::uiInternalObject (char * classname, char * subscribername, char * subscribertype, char * ramptype, char * description) [inline]
Definition at line 21 of file jcom.ui.internals.cpp.
References jcom_core_loadextern(), and theObject.
uiInternalObject::~uiInternalObject () [inline]
Definition at line 36 of file jcom.ui.internals.cpp.
References theObject.
Member Function Documentation
void uiInternalObject::setAction (method aCallback, t_object * aCallbackArg) [inline]
Definition at line 41 of file jcom.ui.internals.cpp.
References theObject.
Referenced by attr_set_hasbypass(), attr_set_hasfreeze(), attr_set_hasgain(), attr_set_hasmix(), attr_set_hasmute(), and attr_set_haspreview().
Member Data Documentation
t_object* uiInternalObject::theObject
Definition at line 18 of file jcom.ui.internals.cpp.
Referenced by setAction(), uiInternalObject(), and ~uiInternalObject().
The documentation for this class was generated from the following file:
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.ui/jcom.ui.internals.cpp