Jamoma: jcomList< T > Class Template Reference
jcomList< T > Class Template Reference
A template class for managing linked lists.
#include <jcom.list.h>
Public Types
typedef list< T >::iterator jcomListIterator
Public Member Functions
jcomList ()
jcomList (const T &rhs)
~jcomList ()
void push_front (const T &x)
Put an item at the front of the list.
void push_back (const T &x)
Put an item at the back of the list.
void remove (const T &x)
Remove an item from the list if it exists.
bool find (const T &x)
template<typename Predicate>
T & find_if (jcomListIterator first, jcomListIterator last, Predicate pred)
T & element (const T &x)
template<typename Compare>
void merge (const T &x, Compare comp)
Merges a new item into the list sorting it according to the function object comp.
int size ()
bool empty () const
jcomListIterator erase (jcomListIterator position)
Removes the list item at position.
void remove (jcomListIterator position)
Removes the list item at position.
jcomListIterator begin ()
jcomListIterator end ()
void clear ()
Removes all list items.
Private Attributes
list< T > ll
Detailed Description
template<class T>
class jcomList< T >
A template class for managing linked lists.
Definition at line 17 of file jcom.list.h.
Member Typedef Documentation
template<class T> typedef list<T>::iterator jcomList< T >::jcomListIterator
Definition at line 24 of file jcom.list.h.
Constructor & Destructor Documentation
template<class T> jcomList< T >::jcomList () [inline]
Definition at line 20 of file jcom.list.h.
template<class T> jcomList< T >::jcomList (const T & rhs) [inline]
Definition at line 21 of file jcom.list.h.
References jcomList< T >::ll.
template<class T> jcomList< T >::~jcomList () [inline]
Definition at line 24 of file jcom.list.h.
Member Function Documentation
template<class T> void jcomList< T >::push_front (const T & x) [inline]
Put an item at the front of the list.
Parameters:
x the item to add to the list
Definition at line 31 of file jcom.list.h.
References jcomList< T >::ll.
template<class T> void jcomList< T >::push_back (const T & x) [inline]
Put an item at the back of the list.
Parameters:
x the item to add to the list
Definition at line 36 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by hub_preset_parse(), and hub_preset_store().
template<class T> void jcomList< T >::remove (const T & x) [inline]
Remove an item from the list if it exists.
Parameters:
x the item in the list
Definition at line 42 of file jcom.list.h.
References jcomList< T >::find(), and jcomList< T >::ll.
Referenced by hub_presets_clear().
template<class T> bool jcomList< T >::find (const T & x) [inline]
Definition at line 49 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by jcomList< T >::element(), and jcomList< T >::remove().
template<class T> template<typename Predicate> T& jcomList< T >::find_if (jcomListIterator first, jcomListIterator last, Predicate pred) [inline]
Definition at line 54 of file jcom.list.h.
References jcomList< T >::ll.
template<class T> T& jcomList< T >::element (const T & x) [inline]
Definition at line 64 of file jcom.list.h.
References jcomList< T >::find(), and jcomList< T >::ll.
template<class T> template<typename Compare> void jcomList< T >::merge (const T & x, Compare comp) [inline]
Merges a new item into the list sorting it according to the function object comp.
Parameters:
x the new item to merge
comp A function object to determine where in the list the new item should be placed
Definition at line 76 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by hub_preset_copy(), hub_preset_parse(), hub_preset_store(), and hub_subscribe().
template<class T> int jcomList< T >::size () [inline]
Returns:
the number of elements in the list
Definition at line 83 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by hub_preset_copy(), hub_preset_store(), and hub_preset_store_next().
template<class T> bool jcomList< T >::empty () const [inline]
Returns:
true if the list is empty, false otherwise
Definition at line 85 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by hub_preset_store(), hub_preset_write(), and hub_presets_clear().
template<class T> jcomListIterator jcomList< T >::erase (jcomListIterator position) [inline]
Removes the list item at position.
Parameters:
position the position of the list item to remove
Returns:
an updated iterator pointing to the position that followed the removed item
Definition at line 90 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by hub_preset_store(), and hub_unsubscribe().
template<class T> void jcomList< T >::remove (jcomListIterator position) [inline]
Removes the list item at position.
Parameters:
position the position of the list item to remove
Definition at line 94 of file jcom.list.h.
References jcomList< T >::ll.
template<class T> jcomListIterator jcomList< T >::begin () [inline]
Returns:
an iterator to the front of the list
Definition at line 96 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by find_preset(), hub_bang(), hub_doautodoc(), hub_free(), hub_gui_build(), hub_init(), hub_messagenames_get(), hub_paramnames_get(), hub_paramvalues_get(), hub_preset_buildmenu(), hub_preset_copy(), hub_preset_dowrite(), hub_preset_parse(), hub_preset_recall(), hub_preset_store(), hub_preset_write(), hub_presets_clear(), hub_presets_dump(), hub_returnnames_get(), hub_symbol(), hub_ui_freeze(), hub_ui_refresh(), hub_unsubscribe(), and interpolate_presets().
template<class T> jcomListIterator jcomList< T >::end () [inline]
Returns:
an iterator to one past the end of the list
Definition at line 98 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by find_preset(), hub_bang(), hub_doautodoc(), hub_free(), hub_gui_build(), hub_init(), hub_messagenames_get(), hub_paramnames_get(), hub_paramvalues_get(), hub_preset_buildmenu(), hub_preset_copy(), hub_preset_dowrite(), hub_preset_recall(), hub_preset_store(), hub_presets_dump(), hub_returnnames_get(), hub_symbol(), hub_ui_freeze(), hub_ui_refresh(), hub_unsubscribe(), and interpolate_presets().
template<class T> void jcomList< T >::clear () [inline]
Removes all list items.
Definition at line 100 of file jcom.list.h.
References jcomList< T >::ll.
Referenced by hub_free().
Member Data Documentation
template<class T> list<T> jcomList< T >::ll [private]
Definition at line 103 of file jcom.list.h.
Referenced by jcomList< T >::begin(), jcomList< T >::clear(), jcomList< T >::element(), jcomList< T >::empty(), jcomList< T >::end(), jcomList< T >::erase(), jcomList< T >::find(), jcomList< T >::find_if(), jcomList< T >::jcomList(), jcomList< T >::merge(), jcomList< T >::push_back(), jcomList< T >::push_front(), jcomList< T >::remove(), and jcomList< T >::size().
The documentation for this class was generated from the following file:
/Users/tim/dev/Jamoma/SourceCode/Framework/source/jcom.list.h