Jamoma: DataspaceLib Class Reference
DataspaceLib Class Reference
#include <DataspaceLib.h>
Public Member Functions
DataspaceLib (char *cName, char *cNeutralUnit)
Constructor.
virtual ~DataspaceLib ()
Destructor.
JamomaError convert (long inputNumArgs, t_atom *inputAtoms, long *outputNumArgs, t_atom **outputAtoms)
converts input to output, possibly doing a unit conversion.
JamomaError setInputUnit (t_symbol *inUnitName)
set the input unit type for this dataspace object by it's name as a symbol
JamomaError setOutputUnit (t_symbol *outUnitName)
set the output unit type for this dataspace object by it's name as a symbol
void getAvailableUnits (long *numUnits, t_symbol ***unitNames)
return a list of all available units for this dataspace
Public Attributes
t_symbol * neutralUnit
t_symbol * name
Protected Member Functions
void registerUnit (void *unit, t_symbol *unitName)
Private Attributes
DataspaceUnit * inUnit
DataspaceUnit * outUnit
t_hashtab * unitHash
Detailed Description
Definition at line 55 of file DataspaceLib.h.
Constructor & Destructor Documentation
DataspaceLib::DataspaceLib (char * cName, char * cNeutralUnit)
Constructor.
This constructor maintains a cache of all DataspaceUnits that are associated with the given dataspace. To maintain the cache, the subclasses must register each unit.
Parameters:
cName The name of the total Dataspace as a C-string
cNativeUnit The name of the neutral unit that is used for translating between units within this Dataspace.
Definition at line 25 of file DataspaceLib.cpp.
References name, neutralUnit, and unitHash.
DataspaceLib::~DataspaceLib () [virtual]
Destructor.
Definition at line 34 of file DataspaceLib.cpp.
References unitHash.
Member Function Documentation
void DataspaceLib::registerUnit (void * unit, t_symbol * unitName) [protected]
Definition at line 90 of file DataspaceLib.cpp.
References unitHash.
Referenced by AngleDataspace::AngleDataspace(), ColorDataspace::ColorDataspace(), DistanceDataspace::DistanceDataspace(), GainDataspace::GainDataspace(), NoneDataspace::NoneDataspace(), PitchDataspace::PitchDataspace(), PositionDataspace::PositionDataspace(), TemperatureDataspace::TemperatureDataspace(), and TimeDataspace::TimeDataspace().
JamomaError DataspaceLib::convert (long inputNumArgs, t_atom * inputAtoms, long * outputNumArgs, t_atom ** outputAtoms)
converts input to output, possibly doing a unit conversion.
EXTREMELY IMPORTANT: We are expecting that **output atoms has its memory passed in already. We are not allocating it due to performance considerations
Definition at line 55 of file DataspaceLib.cpp.
References DataspaceUnit::convertFromNeutral(), DataspaceUnit::convertToNeutral(), inUnit, JAMOMA_ERR_NONE, DataspaceUnit::name, outUnit, and value.
Referenced by dataspace_float(), and dataspace_list().
JamomaError DataspaceLib::setInputUnit (t_symbol * inUnitName)
set the input unit type for this dataspace object by it's name as a symbol
Definition at line 72 of file DataspaceLib.cpp.
References inUnit, JAMOMA_ERR_NONE, DataspaceUnit::name, and unitHash.
Referenced by AngleDataspace::AngleDataspace(), ColorDataspace::ColorDataspace(), dataspace_setDataspaceActive(), DistanceDataspace::DistanceDataspace(), GainDataspace::GainDataspace(), NoneDataspace::NoneDataspace(), PitchDataspace::PitchDataspace(), PositionDataspace::PositionDataspace(), TemperatureDataspace::TemperatureDataspace(), and TimeDataspace::TimeDataspace().
JamomaError DataspaceLib::setOutputUnit (t_symbol * outUnitName)
set the output unit type for this dataspace object by it's name as a symbol
Definition at line 81 of file DataspaceLib.cpp.
References JAMOMA_ERR_NONE, DataspaceUnit::name, outUnit, and unitHash.
Referenced by AngleDataspace::AngleDataspace(), ColorDataspace::ColorDataspace(), dataspace_setDataspaceNative(), DistanceDataspace::DistanceDataspace(), GainDataspace::GainDataspace(), NoneDataspace::NoneDataspace(), PitchDataspace::PitchDataspace(), PositionDataspace::PositionDataspace(), TemperatureDataspace::TemperatureDataspace(), and TimeDataspace::TimeDataspace().
void DataspaceLib::getAvailableUnits (long * numUnits, t_symbol *** unitNames)
return a list of all available units for this dataspace
Definition at line 96 of file DataspaceLib.cpp.
References unitHash.
Referenced by dataspace_getUnits().
Member Data Documentation
DataspaceUnit* DataspaceLib::inUnit [private]
Definition at line 57 of file DataspaceLib.h.
Referenced by convert(), and setInputUnit().
DataspaceUnit* DataspaceLib::outUnit [private]
Definition at line 58 of file DataspaceLib.h.
Referenced by convert(), and setOutputUnit().
t_hashtab* DataspaceLib::unitHash [private]
Definition at line 59 of file DataspaceLib.h.
Referenced by DataspaceLib(), getAvailableUnits(), registerUnit(), setInputUnit(), setOutputUnit(), and ~DataspaceLib().
t_symbol* DataspaceLib::neutralUnit
Definition at line 65 of file DataspaceLib.h.
Referenced by AngleDataspace::AngleDataspace(), ColorDataspace::ColorDataspace(), dataspace_setDataspace(), DataspaceLib(), DistanceDataspace::DistanceDataspace(), GainDataspace::GainDataspace(), NoneDataspace::NoneDataspace(), PitchDataspace::PitchDataspace(), PositionDataspace::PositionDataspace(), TemperatureDataspace::TemperatureDataspace(), and TimeDataspace::TimeDataspace().
t_symbol* DataspaceLib::name
Definition at line 66 of file DataspaceLib.h.
Referenced by DataspaceLib().
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/DataspaceLib.h
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/DataspaceLib.cpp