Jamoma: NoneRamp Class Reference
NoneRamp Class Reference
#include <NoneRamp.h>
Public Member Functions
NoneRamp (RampUnitCallback aCallbackMethod, void *aBaton)
~NoneRamp ()
void go (TTUInt32 numValues, TTFloat64 *inValues, TTFloat64 time)
start a ramp over time in milliseconds
void stop ()
halt any current ramping
void tick ()
called every time a new ramp value should be sent
Detailed Description
Definition at line 17 of file NoneRamp.h.
Constructor & Destructor Documentation
NoneRamp::NoneRamp (RampUnitCallback aCallbackMethod, void * aBaton)
Definition at line 14 of file NoneRamp.cpp.
NoneRamp::~NoneRamp ()
Definition at line 21 of file NoneRamp.cpp.
Member Function Documentation
void NoneRamp::go (TTUInt32 numValues, TTFloat64 * values, TTFloat64 time) [virtual]
start a ramp over time in milliseconds
Implements RampUnit.
Definition at line 27 of file NoneRamp.cpp.
References RampUnit::numValues, RampUnit::setNumValues(), RampUnit::targetValue, and tick().
void NoneRamp::stop () [virtual]
halt any current ramping
Implements RampUnit.
Definition at line 38 of file NoneRamp.cpp.
void NoneRamp::tick () [virtual]
called every time a new ramp value should be sent
Implements RampUnit.
Definition at line 44 of file NoneRamp.cpp.
References RampUnit::baton, RampUnit::callback, RampUnit::currentValue, RampUnit::numValues, and RampUnit::targetValue.
Referenced by go().
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/RampLib/NoneRamp.h
/Users/tim/dev/Jamoma/SourceCode/Framework/RampLib/NoneRamp.cpp