Jamoma: PitchDataspace Class Reference
PitchDataspace Class Reference
#include <PitchDataspace.h>
Public Member Functions
PitchDataspace ()
~PitchDataspace ()
Detailed Description
Definition at line 38 of file PitchDataspace.h.
Constructor & Destructor Documentation
PitchDataspace::PitchDataspace ()
Definition at line 66 of file PitchDataspace.cpp.
References DataspaceLib::neutralUnit, DataspaceLib::registerUnit(), DataspaceLib::setInputUnit(), and DataspaceLib::setOutputUnit().
PitchDataspace::~PitchDataspace ()
Definition at line 79 of file PitchDataspace.cpp.
The documentation for this class was generated from the following files:
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/PitchDataspace.h
/Users/tim/dev/Jamoma/SourceCode/Framework/DataspaceLib/PitchDataspace.cpp