Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.dataspace/jcom.dataspace.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.dataspace/jcom.dataspace.cpp File Reference
#include "Jamoma.h"
Classes
struct t_dataspace
Functions
void * dataspace_new (t_symbol *name, long argc, t_atom *argv)
void dataspace_free (t_dataspace *obj)
void dataspace_assist (t_dataspace *obj, void *b, long m, long a, char *s)
void dataspace_int (t_dataspace *obj, long x)
void dataspace_float (t_dataspace *obj, double x)
void dataspace_list (t_dataspace *obj, t_symbol *msg, long argc, t_atom *argv)
void dataspace_getDataspaces (t_dataspace *obj)
void dataspace_getUnits (t_dataspace *obj)
t_max_err dataspace_setDataspace (t_dataspace *obj, void *attr, long argc, t_atom *argv)
t_max_err dataspace_setDataspaceActive (t_dataspace *obj, void *attr, long argc, t_atom *argv)
t_max_err dataspace_setDataspaceNative (t_dataspace *obj, void *attr, long argc, t_atom *argv)
int main (void)
Variables
t_class * dataspace_class
Function Documentation
void dataspace_assist (t_dataspace * obj, void * b, long m, long a, char * s)
Definition at line 124 of file jcom.dataspace.cpp.
Referenced by main().
void dataspace_float (t_dataspace * obj, double x)
Definition at line 143 of file jcom.dataspace.cpp.
References t_dataspace::ac, t_dataspace::av, DataspaceLib::convert(), t_dataspace::dataspace, t_dataspace::outlet_active, and t_dataspace::outlet_native.
Referenced by dataspace_int(), and main().
void dataspace_free (t_dataspace * obj)
Definition at line 112 of file jcom.dataspace.cpp.
References t_dataspace::av, and t_dataspace::dataspace.
Referenced by main().
void dataspace_getDataspaces (t_dataspace * obj)
Definition at line 162 of file jcom.dataspace.cpp.
References jamoma_getDataspaceList().
Referenced by main().
void dataspace_getUnits (t_dataspace * obj)
Definition at line 185 of file jcom.dataspace.cpp.
References t_dataspace::dataspace, and DataspaceLib::getAvailableUnits().
Referenced by main().
void dataspace_int (t_dataspace * obj, long x)
Definition at line 137 of file jcom.dataspace.cpp.
References dataspace_float().
Referenced by main().
void dataspace_list (t_dataspace * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 154 of file jcom.dataspace.cpp.
References t_dataspace::ac, t_dataspace::av, DataspaceLib::convert(), t_dataspace::dataspace, t_dataspace::outlet_active, and t_dataspace::outlet_native.
Referenced by main().
void * dataspace_new (t_symbol * name, long argc, t_atom * argv)
Definition at line 89 of file jcom.dataspace.cpp.
References dataspace_class.
Referenced by main().
t_max_err dataspace_setDataspace (t_dataspace * obj, void * attr, long argc, t_atom * argv)
Definition at line 209 of file jcom.dataspace.cpp.
References t_dataspace::attr_dataspace, t_dataspace::attr_dataspace_active, t_dataspace::attr_dataspace_native, t_dataspace::dataspace, jamoma_getDataspace(), and DataspaceLib::neutralUnit.
Referenced by main().
t_max_err dataspace_setDataspaceActive (t_dataspace * obj, void * attr, long argc, t_atom * argv)
Definition at line 220 of file jcom.dataspace.cpp.
References t_dataspace::attr_dataspace_active, t_dataspace::dataspace, and DataspaceLib::setInputUnit().
Referenced by main().
t_max_err dataspace_setDataspaceNative (t_dataspace * obj, void * attr, long argc, t_atom * argv)
Definition at line 229 of file jcom.dataspace.cpp.
References t_dataspace::attr_dataspace_native, t_dataspace::dataspace, and DataspaceLib::setOutputUnit().
Referenced by main().
int main (void)
Definition at line 49 of file jcom.dataspace.cpp.
References dataspace_assist(), dataspace_class, dataspace_float(), dataspace_free(), dataspace_getDataspaces(), dataspace_getUnits(), dataspace_int(), dataspace_list(), dataspace_new(), dataspace_setDataspace(), dataspace_setDataspaceActive(), dataspace_setDataspaceNative(), and jamoma_init().
Variable Documentation
t_class* dataspace_class
Definition at line 43 of file jcom.dataspace.cpp.
Referenced by dataspace_new(), and main().