Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.meter~/jcom.meter~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.meter~/jcom.meter~.cpp File Reference
#include "ext.h"
#include "ext_obex.h"
#include "ext_user.h"
#include "ext_common.h"
#include "Jamoma.h"
Classes
struct t_meter
Defines
#define RES_ID 10120
#define MAXWIDTH 1024L
#define MAXHEIGHT 512L
#define MINWIDTH 20L
#define MINHEIGHT 2L
#define DEFWIDTH 100
#define DEFHEIGHT 10
#define POLL_INTERVAL 150
Functions
void * meter_new (t_symbol *s, long argc, t_atom *argv)
void * meter_menu (void *p, long x, long y, long font)
void meter_free (t_meter *x)
void meter_assist (t_meter *x, void *b, long msg, long arg, char *dst)
void meter_bang (t_meter *x)
void meter_float (t_meter *x, double value)
void meter_int (t_meter *x, long value)
void meter_tick (t_meter *x)
t_int * meter_perform (t_int *w)
void meter_dsp (t_meter *x, t_signal **sp, short *count)
void meter_update (t_meter *x)
void meter_click (t_meter *x, Point pt, short modifiers)
void meter_psave (t_meter *x, void *w)
void meter_qfn (t_meter *x)
void meter_draw (t_meter *x)
t_max_err attr_set_defeat (t_meter *x, void *attr, long argc, t_atom *argv)
int main (void)
Variables
static t_class * meter_class
Define Documentation
#define DEFHEIGHT 10
Definition at line 39 of file jcom.meter~.cpp.
Referenced by meter_menu().
#define DEFWIDTH 100
Definition at line 38 of file jcom.meter~.cpp.
Referenced by meter_menu().
#define MAXHEIGHT 512L
Definition at line 35 of file jcom.meter~.cpp.
Referenced by meter_new(), and meter_update().
#define MAXWIDTH 1024L
Definition at line 34 of file jcom.meter~.cpp.
Referenced by meter_new(), and meter_update().
#define MINHEIGHT 2L
Definition at line 37 of file jcom.meter~.cpp.
Referenced by meter_new(), and meter_update().
#define MINWIDTH 20L
Definition at line 36 of file jcom.meter~.cpp.
Referenced by meter_new(), and meter_update().
#define POLL_INTERVAL 150
Definition at line 40 of file jcom.meter~.cpp.
Referenced by attr_set_defeat(), meter_dsp(), meter_tick(), and out_perform().
#define RES_ID 10120
Definition at line 33 of file jcom.meter~.cpp.
Function Documentation
t_max_err attr_set_defeat (t_meter * x, void * attr, long argc, t_atom * argv)
Definition at line 241 of file jcom.meter~.cpp.
References t_meter::attr_defeat, t_meter::clock, and POLL_INTERVAL.
Referenced by main().
int main (void)
Definition at line 83 of file jcom.meter~.cpp.
References attr_set_defeat(), jamoma_init(), meter_assist(), meter_bang(), meter_class, meter_click(), meter_dsp(), meter_float(), meter_free(), meter_int(), meter_menu(), meter_new(), meter_psave(), and meter_update().
void meter_assist (t_meter * x, void * b, long msg, long arg, char * dst)
Definition at line 206 of file jcom.meter~.cpp.
Referenced by main().
void meter_bang (t_meter * x)
Definition at line 220 of file jcom.meter~.cpp.
References t_meter::peak, and t_meter::qelem.
Referenced by main(), and meter_click().
void meter_click (t_meter * x, Point pt, short modifiers)
Definition at line 321 of file jcom.meter~.cpp.
References meter_bang().
Referenced by main().
void meter_draw (t_meter * x)
Definition at line 369 of file jcom.meter~.cpp.
References t_meter::envelope, t_meter::my_box, t_meter::peak, t_meter::peak_level, and t_meter::peak_position.
Referenced by meter_qfn(), and meter_update().
void meter_dsp (t_meter * x, t_signal ** sp, short * count)
Definition at line 283 of file jcom.meter~.cpp.
References t_meter::clock, meter_perform(), t_meter::peak, and POLL_INTERVAL.
Referenced by main().
void meter_float (t_meter * x, double value)
Definition at line 228 of file jcom.meter~.cpp.
References t_meter::envelope, and t_meter::qelem.
Referenced by main(), and meter_int().
void meter_free (t_meter * x)
Definition at line 193 of file jcom.meter~.cpp.
Referenced by main().
void meter_int (t_meter * x, long value)
Definition at line 235 of file jcom.meter~.cpp.
References meter_float().
Referenced by main().
void * meter_menu (void * p, long x, long y, long font)
Definition at line 178 of file jcom.meter~.cpp.
References DEFHEIGHT, DEFWIDTH, and meter_new().
Referenced by main().
void * meter_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 120 of file jcom.meter~.cpp.
References MAXHEIGHT, MAXWIDTH, meter_class, meter_qfn(), meter_tick(), MINHEIGHT, and MINWIDTH.
Referenced by main(), and meter_menu().
t_int * meter_perform (t_int * w)
Definition at line 265 of file jcom.meter~.cpp.
References t_meter::envelope.
Referenced by meter_dsp().
void meter_psave (t_meter * x, void * w)
Definition at line 328 of file jcom.meter~.cpp.
References t_meter::my_box.
Referenced by main().
void meter_qfn (t_meter * x)
Definition at line 354 of file jcom.meter~.cpp.
References meter_draw(), and t_meter::my_box.
Referenced by meter_new().
void meter_tick (t_meter * x)
Definition at line 253 of file jcom.meter~.cpp.
References t_meter::attr_defeat, t_meter::clock, POLL_INTERVAL, and t_meter::qelem.
Referenced by meter_new().
void meter_update (t_meter * x)
Definition at line 298 of file jcom.meter~.cpp.
References MAXHEIGHT, MAXWIDTH, meter_draw(), MINHEIGHT, MINWIDTH, t_meter::my_box, and t_meter::rect.
Referenced by main().
Variable Documentation
t_class* meter_class [static]
Definition at line 78 of file jcom.meter~.cpp.
Referenced by main(), and meter_new().