Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.parameter/jcom.parameter.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.parameter/jcom.parameter.cpp File Reference
#include "jcom.parameter.h"
Functions
int param_list_compare (t_atom *x, long lengthx, t_atom *y, long lengthy)
int main (void)
void * param_new (t_symbol *s, long argc, t_atom *argv)
void param_free (t_param *x)
t_max_err param_setvalueof (t_param *x, long argc, t_atom *argv)
t_max_err param_getvalueof (t_param *x, long *argc, t_atom **argv)
void param_reset (t_param *x)
void param_setcallback (t_param *x, method newCallback, t_object *callbackArg)
t_max_err param_attr_settype (t_param *x, void *attr, long argc, t_atom *argv)
t_max_err param_attr_setramp (t_param *x, void *attr, long argc, t_atom *argv)
t_max_err param_attr_getramp (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_setrampfunction (t_param *x, void *attr, long argc, t_atom *argv)
t_max_err param_attr_getrampfunction (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_gettype (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_getfreeze (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_getstepsize (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_getpriority (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_getvalue (t_param *x, void *attr, long *argc, t_atom **argv)
void param_getRampFunctionParameter (t_param *obj, t_symbol *msg, long argc, t_atom *argv)
void param_setRampFunctionParameter (t_param *obj, t_symbol *msg, long argc, t_atom *argv)
void param_getRampDriveParameter (t_param *obj, t_symbol *msg, long argc, t_atom *argv)
void param_setRampDriveParameter (t_param *obj, t_symbol *msg, long argc, t_atom *argv)
void param_assist (t_param *x, void *b, long msg, long arg, char *dst)
void param_dump (t_param *x)
void param_bang (t_param *x)
void param_output_generic (void *z)
void param_output_int (void *z)
void param_output_float (void *z)
void param_output_symbol (void *z)
void param_output_list (void *z)
void param_output_none (void *z)
void param_inc (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_dec (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_rampUpdate (t_param *x)
If the hub receives a bang, it's passed on to this method, and used to update value if @/ramp/drive is set to "async".
void param_int (t_param *x, long value)
void param_float (t_param *x, double value)
void param_symbol (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_ui_refresh (t_param *x)
void param_send_feedback (t_param *x)
void param_ui_queuefn (t_param *x)
void param_dispatched (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_list (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_ramp_callback_float (void *v, short, double *value)
void param_ramp_callback_int (void *v, short, double *value)
void param_ramp_callback_list (void *v, short argc, double *value)
void param_ramp_setup (t_param *x)
Variables
t_class * parameter_class
t_class * message_class
Function Documentation
int main (void)
Definition at line 21 of file jcom.parameter.cpp.
References attr_value, attr_valueDefault, jamoma_class_attr_array_new(), jamoma_class_attr_new(), jamoma_init(), jcom_core_subscriber_classinit_extended(), LISTSIZE, message_class, OBJECT_CLASS_NAME, param_assist(), param_attr_getfreeze(), param_attr_getpriority(), param_attr_getramp(), param_attr_getrampfunction(), param_attr_getstepsize(), param_attr_gettype(), param_attr_getvalue(), param_attr_setramp(), param_attr_setrampfunction(), param_attr_settype(), param_bang(), param_dec(), param_dispatched(), param_dump(), param_float(), param_free(), param_getRampDriveParameter(), param_getRampFunctionParameter(), param_inc(), param_int(), param_list(), param_new(), param_rampUpdate(), param_reset(), param_setcallback(), param_setRampDriveParameter(), param_setRampFunctionParameter(), param_symbol(), param_ui_refresh(), and parameter_class.
void param_assist (t_param * x, void * b, long msg, long arg, char * dst)
Definition at line 575 of file jcom.parameter.cpp.
References k_outlet_direct, k_outlet_dumpout, and k_outlet_set.
Referenced by main().
t_max_err param_attr_getfreeze (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 393 of file jcom.parameter.cpp.
References t_param::attr_ui_freeze.
Referenced by main().
t_max_err param_attr_getpriority (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 417 of file jcom.parameter.cpp.
References t_param::attr_priority.
Referenced by main().
t_max_err param_attr_getramp (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 345 of file jcom.parameter.cpp.
References t_param::attr_ramp.
Referenced by main().
t_max_err param_attr_getrampfunction (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 369 of file jcom.parameter.cpp.
References t_param::attr_rampfunction.
Referenced by main().
t_max_err param_attr_getstepsize (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 405 of file jcom.parameter.cpp.
References t_param::attr_stepsize.
Referenced by main().
t_max_err param_attr_gettype (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 381 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_type, and t_param::common.
Referenced by main().
t_max_err param_attr_getvalue (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 429 of file jcom.parameter.cpp.
References t_param::atom_list, and t_param::list_size.
Referenced by main().
t_max_err param_attr_setramp (t_param * x, void * attr, long argc, t_atom * argv)
Definition at line 334 of file jcom.parameter.cpp.
References t_param::attr_ramp, and t_param::ramp_qelem.
Referenced by main().
t_max_err param_attr_setrampfunction (t_param * x, void * attr, long argc, t_atom * argv)
Definition at line 357 of file jcom.parameter.cpp.
References t_param::attr_rampfunction, and t_param::ramper.
Referenced by main().
t_max_err param_attr_settype (t_param * x, void * attr, long argc, t_atom * argv)
Definition at line 287 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_type, t_param::common, t_jcom_core_subscriber_extended::module_name, t_param::name, t_param::param_output, param_output_float(), param_output_generic(), param_output_int(), param_output_list(), param_output_none(), param_output_symbol(), ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_list, ps_msg_none, ps_msg_symbol, ps_msg_toggle, and t_param::ramp_qelem.
Referenced by main().
void param_bang (t_param * x)
Definition at line 652 of file jcom.parameter.cpp.
References t_param::atom_list, t_param::callback, t_param::common, t_jcom_core_subscriber_extended::hub, jcom_core_atom_copy(), k_outlet_direct, k_outlet_set, t_param::list_size, t_param::name, t_param::name_atom, t_param::outlets, t_param::param_output, and ps_feedback.
Referenced by main().
void param_dec (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 827 of file jcom.parameter.cpp.
References t_param::attr_slavemode, t_param::attr_stepsize, t_jcom_core_subscriber_extended::attr_type, t_param::common, k_outlet_direct, t_param::outlets, param_dispatched(), param_output_int(), ps_dec, ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_toggle, ps_ramp, t_param::ramper, and RampUnit::stop().
Referenced by main().
void param_dispatched (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 1017 of file jcom.parameter.cpp.
References t_param::atom_list, t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_jcom_core_subscriber_extended::attr_type, t_param::common, jcom_core_atom_copy(), k_outlet_direct, t_param::list_size, t_param::outlets, param_list(), param_list_compare(), t_param::param_output, ps_msg_generic, t_param::ramper, and RampUnit::stop().
Referenced by main(), param_dec(), and param_inc().
void param_dump (t_param * x)
Definition at line 596 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_description, t_jcom_core_subscriber_extended::attr_name, t_param::attr_priority, t_param::attr_ramp, t_jcom_core_subscriber_extended::attr_range, t_jcom_core_subscriber_extended::attr_repetitions, t_jcom_core_subscriber_extended::attr_type, t_param::attr_ui_freeze, t_param::common, t_jcom_core_subscriber_extended::hub, jcom_core_atom_copy(), and ps_feedback.
Referenced by main().
void param_float (t_param * x, double value)
Definition at line 930 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_param::common, k_outlet_direct, t_param::list_size, t_param::outlets, t_param::param_output, t_param::ramper, and RampUnit::stop().
Referenced by main().
void param_free (t_param * x)
Definition at line 212 of file jcom.parameter.cpp.
References jcom_core_subscriber_common_free().
Referenced by main().
void param_getRampDriveParameter (t_param * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 507 of file jcom.parameter.cpp.
References t_param::ramper.
Referenced by main().
void param_getRampFunctionParameter (t_param * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 441 of file jcom.parameter.cpp.
References RampUnit::getFunctionParameterValue(), and t_param::ramper.
Referenced by main().
t_max_err param_getvalueof (t_param * x, long * argc, t_atom ** argv)
Definition at line 240 of file jcom.parameter.cpp.
References t_param::atom_list, and t_param::list_size.
void param_inc (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 757 of file jcom.parameter.cpp.
References t_param::attr_slavemode, t_param::attr_stepsize, t_jcom_core_subscriber_extended::attr_type, t_param::common, k_outlet_direct, t_param::outlets, param_dispatched(), param_output_int(), ps_inc, ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_toggle, ps_ramp, t_param::ramper, and RampUnit::stop().
Referenced by main().
void param_int (t_param * x, long value)
Definition at line 909 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_param::common, k_outlet_direct, t_param::list_size, t_param::outlets, t_param::param_output, t_param::ramper, and RampUnit::stop().
Referenced by main().
void param_list (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 1100 of file jcom.parameter.cpp.
References t_param::atom_list, t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_jcom_core_subscriber_extended::attr_type, t_param::common, RampUnit::go(), jcom_core_atom_copy(), k_outlet_direct, t_param::list_size, LISTSIZE, t_param::outlets, param_list_compare(), t_param::param_output, ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_list, ps_msg_none, ps_ramp, t_param::ramper, and RampUnit::set().
Referenced by main(), and param_dispatched().
int param_list_compare (t_atom * x, long lengthx, t_atom * y, long lengthy)
Definition at line 1072 of file jcom.parameter.cpp.
Referenced by param_dispatched(), and param_list().
void* param_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 136 of file jcom.parameter.cpp.
References jcom_core_subscriber_new_extended(), jcom_core_subscriber_subscribe(), k_outlet_dumpout, LISTSIZE, message_class, num_outlets, t_param::outlets, param_output_generic(), param_ramp_setup(), param_reset(), param_ui_queuefn(), parameter_class, ps_msg_generic, ps_none, ps_subscribe_message, ps_subscribe_parameter, and ps_type.
Referenced by main().
void param_output_float (void * z)
Definition at line 709 of file jcom.parameter.cpp.
References k_outlet_direct, t_param::outlets, param_clip_float(), and param_send_feedback().
Referenced by param_attr_settype(), and param_ramp_callback_float().
void param_output_generic (void * z)
Definition at line 675 of file jcom.parameter.cpp.
References t_param::atom_list, k_outlet_direct, t_param::list_size, t_param::outlets, param_clip_generic(), param_output_none(), and param_send_feedback().
Referenced by param_attr_settype(), and param_new().
void param_output_int (void * z)
Definition at line 699 of file jcom.parameter.cpp.
References k_outlet_direct, t_param::outlets, param_clip_int(), and param_send_feedback().
Referenced by param_attr_settype(), param_dec(), param_inc(), and param_ramp_callback_int().
void param_output_list (void * z)
Definition at line 728 of file jcom.parameter.cpp.
References t_param::atom_list, k_outlet_direct, t_param::list_size, t_param::outlets, param_clip_list(), and param_send_feedback().
Referenced by param_attr_settype(), and param_ramp_callback_list().
void param_output_none (void * z)
Definition at line 738 of file jcom.parameter.cpp.
References t_param::common, t_jcom_core_subscriber_extended::hub, jcom_core_atom_copy(), k_outlet_direct, t_param::name_atom, t_param::outlets, and ps_feedback.
Referenced by param_attr_settype(), and param_output_generic().
void param_output_symbol (void * z)
Definition at line 719 of file jcom.parameter.cpp.
References k_outlet_direct, t_param::outlets, and param_send_feedback().
Referenced by param_attr_settype().
void param_ramp_callback_float (void * v, short , double * value)
Definition at line 1187 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions, t_param::common, and param_output_float().
Referenced by param_ramp_setup().
void param_ramp_callback_int (void * v, short , double * value)
Definition at line 1199 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions, t_param::common, and param_output_int().
Referenced by param_ramp_setup().
void param_ramp_callback_list (void * v, short argc, double * value)
Definition at line 1213 of file jcom.parameter.cpp.
References t_param::atom_list, and param_output_list().
Referenced by param_ramp_setup().
void param_ramp_setup (t_param * x)
Definition at line 1226 of file jcom.parameter.cpp.
References t_param::attr_ramp, t_jcom_core_subscriber_extended::attr_type, t_param::common, RampLib::createUnit(), param_ramp_callback_float(), param_ramp_callback_int(), param_ramp_callback_list(), ps_msg_generic, ps_msg_int, ps_msg_list, ps_msg_none, ps_msg_symbol, ps_msg_toggle, and t_param::ramper.
Referenced by param_new().
void param_rampUpdate (t_param * x)
If the hub receives a bang, it's passed on to this method, and used to update value if @/ramp/drive is set to "async".
Definition at line 900 of file jcom.parameter.cpp.
References t_param::ramper, and RampUnit::tick().
Referenced by main().
void param_reset (t_param * x)
Definition at line 269 of file jcom.parameter.cpp.
References t_param::atom_list, t_param::atom_listDefault, t_param::list_size, and t_param::listDefault_size.
Referenced by main(), and param_new().
void param_send_feedback (t_param * x)
Definition at line 980 of file jcom.parameter.cpp.
References t_param::atom_list, t_param::attr_ui_freeze, t_param::callback, t_param::callbackArg, t_param::common, t_jcom_core_subscriber_extended::hub, jcom_core_atom_copy(), t_param::list_size, LISTSIZE, t_param::name, t_param::name_atom, ps_feedback, and t_param::ui_qelem.
Referenced by param_output_float(), param_output_generic(), param_output_int(), param_output_list(), and param_output_symbol().
void param_setcallback (t_param * x, method newCallback, t_object * callbackArg)
Definition at line 278 of file jcom.parameter.cpp.
References t_param::callback, and t_param::callbackArg.
Referenced by main().
void param_setRampDriveParameter (t_param * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 546 of file jcom.parameter.cpp.
References t_param::ramper.
Referenced by main().
void param_setRampFunctionParameter (t_param * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 485 of file jcom.parameter.cpp.
References t_param::ramper, and RampUnit::setFunctionParameterValue().
Referenced by main().
t_max_err param_setvalueof (t_param * x, long argc, t_atom * argv)
Definition at line 229 of file jcom.parameter.cpp.
References t_param::atom_list, t_param::list_size, and t_param::param_output.
void param_symbol (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 953 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_jcom_core_subscriber_extended::attr_type, t_param::common, jcom_core_atom_compare(), k_outlet_direct, t_param::list_size, t_param::outlets, and t_param::param_output.
Referenced by main().
void param_ui_queuefn (t_param * x)
Definition at line 1010 of file jcom.parameter.cpp.
References k_outlet_set, t_param::list_size, and t_param::outlets.
Referenced by param_new().
void param_ui_refresh (t_param * x)
Definition at line 972 of file jcom.parameter.cpp.
References t_param::attr_slavemode, k_outlet_set, t_param::list_size, and t_param::outlets.
Referenced by main().
Variable Documentation
t_class* message_class
Definition at line 14 of file jcom.parameter.cpp.
Referenced by main(), and param_new().
t_class* parameter_class
Definition at line 13 of file jcom.parameter.cpp.
Referenced by main(), and param_new().