Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.xfade~/jcom.xfade~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.xfade~/jcom.xfade~.cpp File Reference
#include "Jamoma.h"
Classes
struct t_fade
Defines
#define MAX_NUM_CHANNELS 16
Functions
void * fade_new (t_symbol *s, long argc, t_atom *argv)
t_int * fade_perform1 (t_int *w)
t_int * fade_perform2 (t_int *w)
void fade_dsp (t_fade *x, t_signal **sp, short *count)
void fade_assist (t_fade *x, void *b, long m, long a, char *s)
void fade_float (t_fade *x, double value)
void fade_free (t_fade *x)
t_max_err attr_set_position (t_fade *x, void *attr, long argc, t_atom *argv)
t_max_err attr_set_shape (t_fade *x, void *attr, long argc, t_atom *argv)
t_max_err attr_set_mode (t_fade *x, void *attr, long argc, t_atom *argv)
t_int * fade_perform_stereo_1 (t_int *w)
t_int * fade_perform_stereo_2 (t_int *w)
int main (void)
Variables
t_class * fade_class
t_symbol * ps_float32
t_symbol * ps_long
t_symbol * ps_dumpout
Define Documentation
#define MAX_NUM_CHANNELS 16
Definition at line 12 of file jcom.xfade~.cpp.
Function Documentation
t_max_err attr_set_mode (t_fade * x, void * attr, long argc, t_atom * argv)
Definition at line 200 of file jcom.xfade~.cpp.
References t_fade::attr_mode, and t_fade::xfade.
Referenced by main().
t_max_err attr_set_position (t_fade * x, void * attr, long argc, t_atom * argv)
Definition at line 177 of file jcom.xfade~.cpp.
References t_fade::attr_position, and t_fade::xfade.
Referenced by main().
t_max_err attr_set_shape (t_fade * x, void * attr, long argc, t_atom * argv)
Definition at line 188 of file jcom.xfade~.cpp.
References t_fade::attr_shape, and t_fade::xfade.
Referenced by main().
void fade_assist (t_fade * x, void * b, long m, long a, char * s)
Definition at line 154 of file jcom.xfade~.cpp.
Referenced by main().
void fade_dsp (t_fade * x, t_signal ** sp, short * count)
Definition at line 246 of file jcom.xfade~.cpp.
References fade_perform1(), fade_perform2(), and t_fade::num_chans.
Referenced by main().
void fade_float (t_fade * x, double value)
Definition at line 169 of file jcom.xfade~.cpp.
References t_fade::attr_position, and t_fade::xfade.
Referenced by main().
void fade_free (t_fade * x)
Definition at line 138 of file jcom.xfade~.cpp.
Referenced by main().
void * fade_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 102 of file jcom.xfade~.cpp.
References fade_class, MAX_NUM_CHANNELS, and ps_dumpout.
Referenced by main().
t_int * fade_perform1 (t_int * w)
Definition at line 212 of file jcom.xfade~.cpp.
References t_fade::signal_in, t_fade::signal_out, t_fade::x_obj, and t_fade::xfade.
Referenced by fade_dsp().
t_int * fade_perform2 (t_int * w)
Definition at line 228 of file jcom.xfade~.cpp.
References t_fade::signal_in, t_fade::signal_out, t_fade::x_obj, and t_fade::xfade.
Referenced by fade_dsp().
t_int* fade_perform_stereo_1 (t_int * w)
t_int* fade_perform_stereo_2 (t_int * w)
int main (void)
Definition at line 52 of file jcom.xfade~.cpp.
References attr_set_mode(), attr_set_position(), attr_set_shape(), fade_assist(), fade_class, fade_dsp(), fade_float(), fade_free(), fade_new(), jamoma_init(), ps_dumpout, ps_float32, and ps_long.
Variable Documentation
t_class* fade_class
Definition at line 43 of file jcom.xfade~.cpp.
Referenced by fade_new(), and main().
t_symbol* ps_dumpout
Definition at line 46 of file jcom.xfade~.cpp.
t_symbol* ps_float32
Definition at line 44 of file jcom.xfade~.cpp.
t_symbol* ps_long
Definition at line 45 of file jcom.xfade~.cpp.