Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.stats/jcom.stats.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.stats/jcom.stats.cpp File Reference
#include "Jamoma.h"
Classes
struct t_stats
Functions
void * stats_new (t_symbol *s, long argc, t_atom *argv)
void stats_free (t_stats *x)
void stats_setwindowed (t_stats *x, void *attr, long argc, t_atom *argv)
void stats_bang (t_stats *x)
void stats_int (t_stats *x, long n)
void stats_float (t_stats *x, double f)
void stats_clear (t_stats *x)
void stats_window (t_stats *x, long n)
void stats_set (t_stats *x, double f)
void stats_assist (t_stats *x, void *b, long msg, long arg, char *dst)
int main (void)
Variables
t_class * this_class
Function Documentation
int main (void)
Definition at line 54 of file jcom.stats.cpp.
References jamoma_init(), stats_assist(), stats_bang(), stats_clear(), stats_float(), stats_free(), stats_int(), stats_new(), stats_set(), stats_setwindowed(), stats_window(), and this_class.
void stats_assist (t_stats * x, void * b, long msg, long arg, char * dst)
Definition at line 313 of file jcom.stats.cpp.
Referenced by main().
void stats_bang (t_stats * x)
Definition at line 159 of file jcom.stats.cpp.
References t_stats::max, t_stats::min, t_stats::outlet, t_stats::outlet2, t_stats::outlet3, t_stats::outlet4, t_stats::outlet5, t_stats::sumOfSquaredValues, t_stats::sumOfValues, and t_stats::valueCount.
Referenced by main(), stats_float(), and stats_int().
void stats_clear (t_stats * x)
Definition at line 297 of file jcom.stats.cpp.
References t_stats::index, t_stats::max, t_stats::min, t_stats::sumOfSquaredValues, t_stats::sumOfValues, t_stats::valueCount, t_stats::values, and t_stats::windowSize.
Referenced by main(), stats_new(), stats_setwindowed(), and stats_window().
void stats_float (t_stats * x, double f)
Definition at line 200 of file jcom.stats.cpp.
References stats_bang(), and stats_set().
Referenced by main().
void stats_free (t_stats * x)
Definition at line 141 of file jcom.stats.cpp.
References t_stats::values.
Referenced by main().
void stats_int (t_stats * x, long n)
Definition at line 192 of file jcom.stats.cpp.
References stats_bang(), and stats_set().
Referenced by main().
void * stats_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 93 of file jcom.stats.cpp.
References stats_clear(), and this_class.
Referenced by main().
void stats_set (t_stats * x, double f)
Definition at line 209 of file jcom.stats.cpp.
References t_stats::attr_windowed, t_stats::index, t_stats::max, t_stats::min, t_stats::sumOfSquaredValues, t_stats::sumOfValues, t_stats::valueCount, t_stats::values, and t_stats::windowSize.
Referenced by main(), stats_float(), and stats_int().
void stats_setwindowed (t_stats * x, void * attr, long argc, t_atom * argv)
Definition at line 152 of file jcom.stats.cpp.
References t_stats::attr_windowed, and stats_clear().
Referenced by main().
void stats_window (t_stats * x, long n)
Definition at line 284 of file jcom.stats.cpp.
References t_stats::maxWindowSize, stats_clear(), and t_stats::windowSize.
Referenced by main().
Variable Documentation
t_class* this_class
Definition at line 48 of file jcom.stats.cpp.