Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/source/jcom.sendreceive.h File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/source/jcom.sendreceive.h File Reference
#include "ext_linklist.h"
#include "ext_hashtab.h"
Classes
struct t_receive
Receive Object.
struct t_send
Send Object.
struct t_jcom_callback
Callback Object This is an internal object that is used for binding to symbols independed of jcom.receive instantiations.
struct t_jcom_receivemaster
ReceiveMaster Object This is an internal object that manages message dispatching to jcom.receive instances.
Typedefs
typedef void(* t_receive_callback)(t_symbol *name, t_symbol *msg, long argc, t_atom *argv)
Functions
void receive_initclass ()
void receivemaster_initclass ()
void send_initclass ()
Typedef Documentation
typedef void(* t_receive_callback)(t_symbol *name, t_symbol *msg, long argc, t_atom *argv)
Definition at line 16 of file jcom.sendreceive.h.
Function Documentation
void receive_initclass ()
Definition at line 29 of file jcom.receive.cpp.
References receive_assist(), receive_dispatch(), receive_free(), receive_new(), receive_setcallback(), receive_setname(), and s_receive_class.
Referenced by jamoma_init().
void receivemaster_initclass ()
Definition at line 28 of file jcom.receivemaster.cpp.
References receivemaster_add(), receivemaster_dispatch(), receivemaster_free(), receivemaster_new(), receivemaster_remove(), and s_receivemaster_class.
Referenced by jamoma_init().
void send_initclass ()
Definition at line 29 of file jcom.send.cpp.
References s_send_class, send_assist(), send_bang(), send_float(), send_int(), send_list(), and send_new().
Referenced by jamoma_init().