Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.sum%/jcom.sum%.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.sum/jcom.sum%.cpp File Reference
#include "jamoma.h"
#include "jit.common.h"
Classes
struct t_jit_sum
Defines
#define MATRIX_GET_CHAR_2D(bp, info, plane, x, y) (*(((uchar *)(bp))+(plane)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y))))
#define MATRIX_GET_LONG_2D(bp, info, plane, x, y) (*(long *)(((uchar *)(bp))+(plane*4)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y))))
#define MATRIX_GET_FLOAT32_2D(bp, info, plane, x, y) (*(float *)(((uchar *)(bp))+(plane*4)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y))))
#define MATRIX_GET_FLOAT64_2D(bp, info, plane, x, y) (*(double *)(((uchar *)(bp))+(plane*8)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y))))
#define MATRIX_SET_CHAR_2D(bp, info, plane, x, y, val) (*(((uchar *)(bp))+(plane)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y)))=(val))
#define MATRIX_SET_LONG_2D(bp, info, plane, x, y, val) (*(long *)(((uchar *)(bp))+(plane*4)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y)))=(val))
#define MATRIX_SET_FLOAT32_2D(bp, info, plane, x, y, val) (*(float *)(((uchar *)(bp))+(plane*4)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y)))=(val))
#define MATRIX_SET_FLOAT64_2D(bp, info, plane, x, y, val) (*(double *)(((uchar *)(bp))+(plane*8)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y)))=(val))
Functions
void * jit_sum_new (t_symbol *s, long argc, t_atom *argv)
void jit_sum_free (t_jit_sum *x)
void jit_sum_assist (t_jit_sum *x, void *b, long m, long a, char *s)
void jit_sum_jit_matrix (t_jit_sum *x, t_symbol *s, long argc, t_atom *argv)
void jit_sum_calculate_ndim (t_jit_sum *x, long dimcount, long *dim, t_atom *a_coord, t_jit_matrix_info *in_minfo, char *bip)
void jit_sum_change_calculate_ndim (t_jit_sum *x, t_jit_matrix_info *in_minfo, char *in_mdata)
int main (void)
Variables
t_class * jit_sum_class
t_symbol * ps_done
Define Documentation
#define MATRIX_GET_CHAR_2D (bp, info, plane, x, y) (*(((uchar *)(bp))+(plane)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y))))
Definition at line 33 of file jcom.sum%.cpp.
#define MATRIX_GET_FLOAT32_2D (bp, info, plane, x, y) (*(float *)(((uchar *)(bp))+(plane*4)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y))))
Definition at line 39 of file jcom.sum%.cpp.
#define MATRIX_GET_FLOAT64_2D (bp, info, plane, x, y) (*(double *)(((uchar *)(bp))+(plane*8)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y))))
Definition at line 42 of file jcom.sum%.cpp.
#define MATRIX_GET_LONG_2D (bp, info, plane, x, y) (*(long *)(((uchar *)(bp))+(plane*4)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y))))
Definition at line 36 of file jcom.sum%.cpp.
#define MATRIX_SET_CHAR_2D (bp, info, plane, x, y, val) (*(((uchar *)(bp))+(plane)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y)))=(val))
Definition at line 45 of file jcom.sum%.cpp.
#define MATRIX_SET_FLOAT32_2D (bp, info, plane, x, y, val) (*(float *)(((uchar *)(bp))+(plane*4)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y)))=(val))
Definition at line 51 of file jcom.sum%.cpp.
#define MATRIX_SET_FLOAT64_2D (bp, info, plane, x, y, val) (*(double *)(((uchar *)(bp))+(plane*8)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y)))=(val))
Definition at line 54 of file jcom.sum%.cpp.
#define MATRIX_SET_LONG_2D (bp, info, plane, x, y, val) (*(long *)(((uchar *)(bp))+(plane*4)+((info)->dimstride[0]*(x))+((info)->dimstride[1]*(y)))=(val))
Definition at line 48 of file jcom.sum%.cpp.
Function Documentation
void jit_sum_assist (t_jit_sum * x, void * b, long m, long a, char * s)
Definition at line 182 of file jcom.sum%.cpp.
Referenced by main().
void jit_sum_calculate_ndim (t_jit_sum * x, long dimcount, long * dim, t_atom * a_coord, t_jit_matrix_info * in_minfo, char * bip)
Definition at line 249 of file jcom.sum%.cpp.
References t_jit_sum::mode, and t_jit_sum::valout.
Referenced by jit_sum_jit_matrix().
void jit_sum_change_calculate_ndim (t_jit_sum * x, t_jit_matrix_info * in_minfo, char * in_mdata)
Definition at line 464 of file jcom.sum%.cpp.
References t_jit_sum::matrix, and t_jit_sum::valout.
Referenced by jit_sum_jit_matrix().
void jit_sum_free (t_jit_sum * x)
Definition at line 170 of file jcom.sum%.cpp.
References t_jit_sum::matrix, and t_jit_sum::matrix_name.
Referenced by main().
void jit_sum_jit_matrix (t_jit_sum * x, t_symbol * s, long argc, t_atom * argv)
Definition at line 199 of file jcom.sum%.cpp.
References jit_sum_calculate_ndim(), jit_sum_change_calculate_ndim(), t_jit_sum::mode, and ps_done.
Referenced by main().
void * jit_sum_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 143 of file jcom.sum%.cpp.
References jit_sum_class.
Referenced by main().
int main (void)
Definition at line 106 of file jcom.sum%.cpp.
References jamoma_init(), jit_sum_assist(), jit_sum_class, jit_sum_free(), jit_sum_jit_matrix(), jit_sum_new(), and ps_done.
Variable Documentation
t_class* jit_sum_class
Definition at line 99 of file jcom.sum%.cpp.
Referenced by jit_sum_new(), and main().
t_symbol* ps_done
Definition at line 100 of file jcom.sum%.cpp.