Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.ui/jcom.ui.h File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.ui/jcom.ui.h File Reference
#include "ext.h"
#include "ext_obex.h"
#include "ext_user.h"
#include "ext_common.h"
#include "jpatcher_api.h"
#include "jgraphics.h"
#include "Jamoma.h"
#include "ext_symobject.h"
Classes
struct t_ui
Functions
t_ui * ui_new (t_symbol *s, short argc, t_atom *argv)
void ui_free (t_ui *x)
void ui_notify (t_ui *x, t_symbol *s, t_symbol *msg, void *sender, void *data)
void ui_bang (t_ui *x)
void ui_paint (t_ui *x, t_object *view)
void ui_mousedown (t_ui *x, t_object *patcherview, t_pt pt, long modifiers)
void ui_mousedragdelta (t_ui *x, t_object *patcherview, t_pt pt, long modifiers)
void ui_mouseup (t_ui *x, t_object *patcherview)
void * ui_oksize (t_ui *x, t_rect *rect)
void ui_menu_do (t_ui *x, t_object *patcherview, t_pt px, long modifiers)
void ui_menu_qfn (t_ui *x)
void ui_menu_build (t_ui *x)
void ui_refmenu_do (t_ui *x, t_object *patcherview, t_pt px, long modifiers)
void ui_refmenu_qfn (t_ui *x)
void ui_refmenu_build (t_ui *x)
void ui_internals_destroy (t_ui *x)
t_max_err attr_set_mute (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_bypass (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_mix (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_gain (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_freeze (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_preview (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasmute (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasbypass (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasmix (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasgain (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasfreeze (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_haspreview (t_ui *obj, void *attr, long argc, t_atom *argv)
Function Documentation
t_max_err attr_set_bypass (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 134 of file jcom.ui.internals.cpp.
References t_ui::attr_isbypassed, t_ui::hash_internals, and value.
t_max_err attr_set_freeze (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 182 of file jcom.ui.internals.cpp.
References t_ui::attr_isfrozen, t_ui::hash_internals, and value.
Referenced by main().
t_max_err attr_set_gain (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 166 of file jcom.ui.internals.cpp.
References t_ui::attr_gain, t_ui::hash_internals, and value.
t_max_err attr_set_hasbypass (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 242 of file jcom.ui.internals.cpp.
References t_ui::attr_hasbypass, t_ui::hash_internals, uiInternalObject::setAction(), and ui_bypass().
Referenced by main().
t_max_err attr_set_hasfreeze (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 305 of file jcom.ui.internals.cpp.
References t_ui::attr_hasfreeze, t_ui::hash_internals, uiInternalObject::setAction(), and ui_freeze().
Referenced by main().
t_max_err attr_set_hasgain (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 284 of file jcom.ui.internals.cpp.
References t_ui::attr_hasgain, t_ui::hash_internals, uiInternalObject::setAction(), and ui_gain().
Referenced by main().
t_max_err attr_set_hasmix (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 263 of file jcom.ui.internals.cpp.
References t_ui::attr_hasmix, t_ui::hash_internals, uiInternalObject::setAction(), and ui_mix().
Referenced by main().
t_max_err attr_set_hasmute (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 219 of file jcom.ui.internals.cpp.
References t_ui::attr_hasmute, t_ui::hash_internals, uiInternalObject::setAction(), and ui_mute().
Referenced by main().
t_max_err attr_set_haspreview (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 326 of file jcom.ui.internals.cpp.
References t_ui::attr_haspreview, t_ui::hash_internals, uiInternalObject::setAction(), and ui_preview().
Referenced by main().
t_max_err attr_set_mix (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 150 of file jcom.ui.internals.cpp.
References t_ui::attr_mix, t_ui::hash_internals, and value.
t_max_err attr_set_mute (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 118 of file jcom.ui.internals.cpp.
References t_ui::attr_ismuted, t_ui::hash_internals, and value.
Referenced by main().
t_max_err attr_set_preview (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 198 of file jcom.ui.internals.cpp.
References t_ui::attr_ispreviewing, t_ui::hash_internals, and value.
Referenced by main().
void ui_bang (t_ui * x)
Definition at line 257 of file jcom.ui.cpp.
void ui_free (t_ui * x)
Definition at line 213 of file jcom.ui.cpp.
References t_ui::box, t_ui::menu_items, t_ui::menu_qelem, t_ui::obj_remote, t_ui::presets, t_ui::refmenu_items, t_ui::refmenu_qelem, and ui_internals_destroy().
Referenced by main().
void ui_internals_destroy (t_ui * x)
Definition at line 48 of file jcom.ui.internals.cpp.
References t_ui::hash_internals.
Referenced by ui_free().
void ui_menu_build (t_ui * x)
Definition at line 779 of file jcom.ui.cpp.
References t_ui::attr_hasmeters, t_ui::menu_items, t_ui::presets, and t_ui::refmenu_items.
Referenced by ui_new(), and ui_notify().
void ui_menu_do (t_ui * x, t_object * patcherview, t_pt px, long modifiers)
Definition at line 716 of file jcom.ui.cpp.
References JAMOMA_MENU_FONT, and JAMOMA_MENU_FONTSIZE.
Referenced by ui_mousedown().
void ui_menu_qfn (t_ui * x)
Definition at line 766 of file jcom.ui.cpp.
References t_ui::attr_metersdefeated, t_ui::menu_items, and t_ui::menu_selection.
Referenced by ui_new().
void ui_mousedown (t_ui * x, t_object * patcherview, t_pt pt, long modifiers)
Definition at line 581 of file jcom.ui.cpp.
References ui_menu_do(), and ui_refmenu_do().
Referenced by main().
void ui_mousedragdelta (t_ui * x, t_object * patcherview, t_pt pt, long modifiers)
Definition at line 660 of file jcom.ui.cpp.
Referenced by main().
void ui_mouseup (t_ui * x, t_object * patcherview)
Definition at line 696 of file jcom.ui.cpp.
Referenced by main().
t_ui* ui_new (t_symbol * s, short argc, t_atom * argv)
Definition at line 147 of file jcom.ui.cpp.
References t_ui::box, t_ui::hash_internals, jcom_core_loadextern(), t_ui::menu_items, t_ui::menu_qelem, t_ui::obj_remote, t_ui::outlet, t_ui::presets, ps__gui__, t_ui::refmenu_items, t_ui::refmenu_qelem, s_ui_class, ui_menu_build(), ui_menu_qfn(), ui_refmenu_build(), and ui_refmenu_qfn().
Referenced by main().
void ui_notify (t_ui * x, t_symbol * s, t_symbol * msg, void * sender, void * data)
Definition at line 237 of file jcom.ui.cpp.
References t_ui::box, and ui_menu_build().
Referenced by main().
void* ui_oksize (t_ui * x, t_rect * rect)
Definition at line 924 of file jcom.ui.cpp.
References JAMOMA_UNIT_HEIGHT, JAMOMA_UNIT_WIDTH, and s_color_text.
Referenced by main().
void ui_paint (t_ui * x, t_object * view)
Definition at line 266 of file jcom.ui.cpp.
References t_ui::attr_hasbypass, t_ui::attr_hasfreeze, t_ui::attr_hasgain, t_ui::attr_hasinspector, t_ui::attr_hasmix, t_ui::attr_hasmute, t_ui::attr_haspreview, t_ui::attr_isbypassed, t_ui::attr_isfrozen, t_ui::attr_ismuted, t_ui::attr_ispreviewing, t_ui::box, JAMOMA_BUTTON_FONT, t_ui::rect_bypass, t_ui::rect_freeze, t_ui::rect_gain, t_ui::rect_inspector, t_ui::rect_mix, t_ui::rect_mute, t_ui::rect_preview, s_color_background_audio, s_color_background_button, s_color_blue_button, s_color_border_audio, s_color_border_button, s_color_green_button, s_color_orange_button, s_color_red_button, s_color_text_button_off, s_color_text_button_on, and s_color_titlebar_audio.
Referenced by main().
void ui_refmenu_build (t_ui * x)
Definition at line 880 of file jcom.ui.cpp.
References t_ui::refmenu_items.
Referenced by ui_new().
void ui_refmenu_do (t_ui * x, t_object * patcherview, t_pt px, long modifiers)
Definition at line 824 of file jcom.ui.cpp.
References JAMOMA_MENU_FONT, and JAMOMA_MENU_FONTSIZE.
Referenced by ui_mousedown().
void ui_refmenu_qfn (t_ui * x)
Definition at line 868 of file jcom.ui.cpp.
References t_ui::refmenu_items, and t_ui::refmenu_selection.
Referenced by ui_new().