Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.phasor~/jcom.phasor~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.phasor~/jcom.phasor~.cpp File Reference
#include "Jamoma.h"
Classes
struct t_phasor
Functions
void * phasor_new (t_symbol *s, long argc, t_atom *argv)
void phasor_free (t_phasor *x)
t_int * phasor_perform (t_int *w)
void phasor_dsp (t_phasor *x, t_signal **sp, short *count)
t_max_err phasor_attr_setperiod (t_phasor *x, void *attr, long argc, t_atom *argv)
int main (void)
Variables
static t_class * phasor_class
Function Documentation
int main (void)
Definition at line 39 of file jcom.phasor~.cpp.
References jamoma_init(), phasor_attr_setperiod(), phasor_class, phasor_dsp(), phasor_free(), and phasor_new().
t_max_err phasor_attr_setperiod (t_phasor * x, void * attr, long argc, t_atom * argv)
Definition at line 148 of file jcom.phasor~.cpp.
References t_phasor::attr_period, DEFAULT_TICKS_PER_SECOND, and t_phasor::frequency.
Referenced by main().
void phasor_dsp (t_phasor * x, t_signal ** sp, short * count)
Definition at line 139 of file jcom.phasor~.cpp.
References jamoma_dsp(), t_phasor::one_over_sr, and phasor_perform().
Referenced by main().
void phasor_free (t_phasor * x)
Definition at line 99 of file jcom.phasor~.cpp.
Referenced by main().
void * phasor_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 75 of file jcom.phasor~.cpp.
References DEFAULT_SAMPLE_RATE, and phasor_class.
Referenced by main().
t_int * phasor_perform (t_int * w)
Definition at line 109 of file jcom.phasor~.cpp.
References t_phasor::attr_period, jamoma_scheduler_getphase(), t_phasor::lastoutput, and t_phasor::obj.
Referenced by phasor_dsp().
Variable Documentation
t_class* phasor_class [static]
Definition at line 33 of file jcom.phasor~.cpp.
Referenced by main(), and phasor_new().