Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.route/jcom.route.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.route/jcom.route.cpp File Reference
#include "Jamoma.h"
Classes
struct t_route
Defines
#define MAX_LIST_LENGTH 100
Functions
void * route_new (t_symbol *s, long argc, t_atom *argv)
void route_assist (t_route *x, void *b, long msg, long arg, char *dst)
void route_symbol (t_route *x, t_symbol *msg, long argc, t_atom *argv)
void route_list (t_route *x, t_symbol *msg, long argc, t_atom *argv)
void route_bang (t_route *x)
char find_match (t_route *x, t_symbol *input, short position)
int main (void)
Variables
t_class * route_class
Define Documentation
#define MAX_LIST_LENGTH 100
Definition at line 12 of file jcom.route.cpp.
Function Documentation
char find_match (t_route * x, t_symbol * input, short position)
Definition at line 153 of file jcom.route.cpp.
References MAX_LIST_LENGTH, t_route::partialmatch, t_route::searchpositions, and t_route::searchsymbol.
Referenced by route_list(), and route_symbol().
int main (void)
Definition at line 42 of file jcom.route.cpp.
References jamoma_init(), MAX_LIST_LENGTH, route_assist(), route_bang(), route_class, route_list(), route_new(), and route_symbol().
void route_assist (t_route * x, void * b, long msg, long arg, char * dst)
Definition at line 121 of file jcom.route.cpp.
Referenced by main().
void route_bang (t_route * x)
Definition at line 135 of file jcom.route.cpp.
References t_route::searchlist, t_route::searchlistlen, and t_route::searchsymbol.
Referenced by main(), route_list(), and route_symbol().
void route_list (t_route * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 222 of file jcom.route.cpp.
References find_match(), t_route::my_outlet, and route_bang().
Referenced by main().
void * route_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 93 of file jcom.route.cpp.
References route_class.
Referenced by main().
void route_symbol (t_route * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 181 of file jcom.route.cpp.
References find_match(), t_route::my_outlet, and route_bang().
Referenced by main().
Variable Documentation
t_class* route_class
Definition at line 37 of file jcom.route.cpp.
Referenced by main(), and route_new().