Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.change/jcom.change.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.change/jcom.change.cpp File Reference
#include "Jamoma.h"
Classes
struct t_change
Defines
#define MAX_LIST_SIZE 256
Enumerations
enum type { msg_new, msg_int, msg_float, msg_list }
Functions
void change_assist (t_change *x, void *b, long m, long a, char *s)
void * change_new (void)
void change_free (t_change *x)
void change_anything (t_change *x, Symbol *msg, long argc, Atom *argv)
void change_int (t_change *x, long value)
void change_float (t_change *x, double value)
float atom_getvalue (long index, long argc, t_atom *argv)
void atom_copy (t_atom *dst, t_atom *src)
bool atom_compare (Atom *in1, Atom *in2)
int main (void)
void change_anything (t_change *x, t_symbol *msg, long argc, t_atom *argv)
Variables
t_class * change_class
Define Documentation
#define MAX_LIST_SIZE 256
Definition at line 12 of file jcom.change.cpp.
Referenced by change_new().
Enumeration Type Documentation
enum type
Enumerator:
msg_new
msg_int
msg_float
msg_list
Definition at line 14 of file jcom.change.cpp.
Function Documentation
bool atom_compare (Atom * in1, Atom * in2)
Definition at line 218 of file jcom.change.cpp.
Referenced by change_anything().
void atom_copy (t_atom * dst, t_atom * src)
Definition at line 194 of file jcom.change.cpp.
Referenced by change_anything().
float atom_getvalue (long index, long argc, t_atom * argv)
void change_anything (t_change * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 159 of file jcom.change.cpp.
References atom_compare(), atom_copy(), and msg_list.
void change_anything (t_change * x, Symbol * msg, long argc, Atom * argv)
Referenced by main().
void change_assist (t_change * x, void * b, long m, long a, char * s)
Definition at line 114 of file jcom.change.cpp.
Referenced by main().
void change_float (t_change * x, double value)
Definition at line 143 of file jcom.change.cpp.
References msg_float.
Referenced by main().
void change_free (t_change * x)
Definition at line 104 of file jcom.change.cpp.
References t_change::inlet_right.
Referenced by main().
void change_int (t_change * x, long value)
Definition at line 129 of file jcom.change.cpp.
References msg_int.
Referenced by main().
void * change_new (void)
Definition at line 83 of file jcom.change.cpp.
References change_class, t_change::last_input_type, MAX_LIST_SIZE, and msg_new.
Referenced by main().
int main (void)
Definition at line 54 of file jcom.change.cpp.
References change_anything(), change_assist(), change_class, change_float(), change_free(), change_int(), change_new(), and jamoma_init().
Variable Documentation
t_class* change_class
Definition at line 49 of file jcom.change.cpp.
Referenced by change_new(), and main().