Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.return/jcom.return.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.return/jcom.return.cpp File Reference
#include "Jamoma.h"
Classes
struct t_return
Enumerations
enum outlets {
k_outlet_return = 0, k_outlet_dumpout, k_num_outlets, k_outlet_set = 0,
k_outlet_direct, k_outlet_dumpout, num_outlets, k_outlet_value = 0,
k_outlet_dumpout, num_outlets, k_outlet_thru = 0, k_outlet_dumpout,
num_outlets
}
Functions
void * return_new (t_symbol *s, long argc, t_atom *argv)
void return_assist (t_return *x, void *b, long msg, long arg, char *dst)
void return_bang (t_return *x)
void return_int (t_return *x, long n)
void return_float (t_return *x, double f)
void return_symbol (t_return *x, t_symbol *msg, long argc, t_atom *argv)
void return_list (t_return *x, t_symbol *msg, long argc, t_atom *argv)
void return_send_feedback (t_return *x)
void return_dump (t_return *x)
t_max_err return_attr_gettype (t_return *x, void *attr, long *argc, t_atom **argv)
int main (void)
Variables
t_class * return_class
Enumeration Type Documentation
enum outlets
Enumerator:
k_outlet_return
k_outlet_dumpout
k_num_outlets
k_outlet_set
k_outlet_direct
k_outlet_dumpout
num_outlets
k_outlet_value
k_outlet_dumpout
num_outlets
k_outlet_thru
k_outlet_dumpout
num_outlets
Definition at line 12 of file jcom.return.cpp.
Function Documentation
int main (void)
Definition at line 47 of file jcom.return.cpp.
References jamoma_class_attr_new(), jamoma_init(), jcom_core_subscriber_classinit_extended(), jcom_core_subscriber_common_free(), return_assist(), return_attr_gettype(), return_bang(), return_class, return_dump(), return_float(), return_int(), return_list(), return_new(), and return_symbol().
void return_assist (t_return * x, void * b, long msg, long arg, char * dst)
Definition at line 120 of file jcom.return.cpp.
References k_outlet_dumpout.
Referenced by main().
t_max_err return_attr_gettype (t_return * x, void * attr, long * argc, t_atom ** argv)
Definition at line 174 of file jcom.return.cpp.
References t_jcom_core_subscriber_extended::attr_type, and t_return::common.
Referenced by main().
void return_bang (t_return * x)
Definition at line 199 of file jcom.return.cpp.
References t_jcom_core_subscriber_extended::attr_name, t_return::common, t_jcom_core_subscriber_extended::hub, k_outlet_thru, t_return::outlets, t_return::output, t_return::output_len, and ps_return.
Referenced by main().
void return_dump (t_return * x)
Definition at line 134 of file jcom.return.cpp.
References t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_description, t_jcom_core_subscriber_extended::attr_name, t_jcom_core_subscriber_extended::attr_range, t_jcom_core_subscriber_extended::attr_repetitions, t_jcom_core_subscriber_extended::attr_type, t_return::common, t_jcom_core_subscriber_extended::hub, and ps_feedback.
Referenced by main().
void return_float (t_return * x, double f)
Definition at line 221 of file jcom.return.cpp.
References k_outlet_thru, t_return::outlets, t_return::output, t_return::output_len, and return_send_feedback().
Referenced by main().
void return_int (t_return * x, long n)
Definition at line 210 of file jcom.return.cpp.
References k_outlet_thru, t_return::outlets, t_return::output, t_return::output_len, and return_send_feedback().
Referenced by main().
void return_list (t_return * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 249 of file jcom.return.cpp.
References jcom_core_atom_copy(), k_outlet_thru, t_return::outlets, t_return::output, t_return::output_len, and return_send_feedback().
Referenced by main().
void * return_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 90 of file jcom.return.cpp.
References jcom_core_subscriber_new_extended(), jcom_core_subscriber_subscribe(), k_outlet_dumpout, k_outlet_thru, t_return::outlets, ps_subscribe_return, and return_class.
Referenced by main().
void return_send_feedback (t_return * x)
Definition at line 186 of file jcom.return.cpp.
References t_return::common, t_jcom_core_subscriber_extended::has_wildcard, t_jcom_core_subscriber_extended::hub, t_return::output, t_return::output_len, ps_return, and ps_return_extended.
Referenced by return_float(), return_int(), return_list(), and return_symbol().
void return_symbol (t_return * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 232 of file jcom.return.cpp.
References jcom_core_atom_copy(), k_outlet_thru, t_return::outlets, t_return::output, t_return::output_len, and return_send_feedback().
Referenced by main().
Variable Documentation
t_class* return_class
Definition at line 41 of file jcom.return.cpp.
Referenced by main(), and return_new().