Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.limiter~/jcom.limiter~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.limiter~/jcom.limiter~.cpp File Reference
#include "Jamoma.h"
Classes
struct t_limiter
Defines
#define NUM_INPUTS 2
#define NUM_OUTPUTS 2
Functions
void * limiter_new (t_symbol *s, long argc, t_atom *argv)
t_int * limiter_perform (t_int *w)
t_int * limiter_perform2 (t_int *w)
void limiter_dsp (t_limiter *x, t_signal **sp, short *count)
void limiter_assist (t_limiter *x, void *b, long msg, long arg, char *dst)
t_max_err limiter_setthreshold (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setpreamp (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setpostamp (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setmode (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setrelease (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setlookahead (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setbypass_limiter (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setbypass_dcblocker (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setbypass (t_limiter *x, void *attr, long argc, t_atom *argv)
t_max_err limiter_setmute (t_limiter *x, void *attr, long argc, t_atom *argv)
void limiter_anything (t_limiter *x, t_symbol *msg, long argc, t_atom *argv)
void limiter_clear (t_limiter *x)
void limiter_free (t_limiter *x)
int main (void)
Variables
t_class * limiter_class
t_symbol * ps_linear
t_symbol * ps_exponential
t_symbol * ps_symbol
t_symbol * ps_long
t_symbol * ps_float32
t_symbol * ps_dumpout
Define Documentation
#define NUM_INPUTS 2
Definition at line 12 of file jcom.limiter~.cpp.
Referenced by limiter_free(), limiter_new(), saturation_free(), saturation_new(), zerox_free(), and zerox_new().
#define NUM_OUTPUTS 2
Definition at line 13 of file jcom.limiter~.cpp.
Referenced by limiter_free(), limiter_new(), saturation_free(), saturation_new(), zerox_free(), and zerox_new().
Function Documentation
void limiter_anything (t_limiter * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 323 of file jcom.limiter~.cpp.
Referenced by main().
void limiter_assist (t_limiter * x, void * b, long msg, long arg, char * dst)
Definition at line 221 of file jcom.limiter~.cpp.
Referenced by main().
void limiter_clear (t_limiter * x)
Definition at line 236 of file jcom.limiter~.cpp.
References t_limiter::limiter.
Referenced by main().
void limiter_dsp (t_limiter * x, t_signal ** sp, short * count)
Definition at line 392 of file jcom.limiter~.cpp.
References t_limiter::limiter, limiter_perform(), and limiter_perform2().
Referenced by main().
void limiter_free (t_limiter * x)
Definition at line 204 of file jcom.limiter~.cpp.
References NUM_INPUTS, and NUM_OUTPUTS.
Referenced by main().
void * limiter_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 165 of file jcom.limiter~.cpp.
References limiter_class, NUM_INPUTS, NUM_OUTPUTS, ps_dumpout, and ps_exponential.
Referenced by main().
t_int * limiter_perform (t_int * w)
Definition at line 350 of file jcom.limiter~.cpp.
References t_limiter::attr_bypass, t_limiter::attr_mute, t_limiter::copy, t_limiter::limiter, t_limiter::signal_in, t_limiter::signal_out, and t_limiter::x_obj.
Referenced by limiter_dsp().
t_int * limiter_perform2 (t_int * w)
Definition at line 370 of file jcom.limiter~.cpp.
References t_limiter::attr_bypass, t_limiter::attr_mute, t_limiter::copy, t_limiter::limiter, t_limiter::signal_in, t_limiter::signal_out, and t_limiter::x_obj.
Referenced by limiter_dsp().
t_max_err limiter_setbypass (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 308 of file jcom.limiter~.cpp.
References t_limiter::attr_bypass.
Referenced by main().
t_max_err limiter_setbypass_dcblocker (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 298 of file jcom.limiter~.cpp.
References t_limiter::attr_bypass_dcblocker, and t_limiter::limiter.
Referenced by main().
t_max_err limiter_setbypass_limiter (t_limiter * x, void * attr, long argc, t_atom * argv)
t_max_err limiter_setlookahead (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 287 of file jcom.limiter~.cpp.
References t_limiter::attr_lookahead, and t_limiter::limiter.
Referenced by main().
t_max_err limiter_setmode (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 330 of file jcom.limiter~.cpp.
References t_limiter::attr_mode, t_limiter::limiter, ps_exponential, and ps_linear.
Referenced by main().
t_max_err limiter_setmute (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 315 of file jcom.limiter~.cpp.
References t_limiter::attr_mute.
Referenced by main().
t_max_err limiter_setpostamp (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 265 of file jcom.limiter~.cpp.
References t_limiter::attr_postamp, and t_limiter::limiter.
Referenced by main().
t_max_err limiter_setpreamp (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 254 of file jcom.limiter~.cpp.
References t_limiter::attr_preamp, and t_limiter::limiter.
Referenced by main().
t_max_err limiter_setrelease (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 276 of file jcom.limiter~.cpp.
References t_limiter::attr_release, and t_limiter::limiter.
Referenced by main().
t_max_err limiter_setthreshold (t_limiter * x, void * attr, long argc, t_atom * argv)
Definition at line 243 of file jcom.limiter~.cpp.
References t_limiter::attr_threshold, and t_limiter::limiter.
Referenced by main().
int main (void)
Definition at line 66 of file jcom.limiter~.cpp.
References jamoma_init(), limiter_anything(), limiter_assist(), limiter_class, limiter_clear(), limiter_dsp(), limiter_free(), limiter_new(), limiter_setbypass(), limiter_setbypass_dcblocker(), limiter_setlookahead(), limiter_setmode(), limiter_setmute(), limiter_setpostamp(), limiter_setpreamp(), limiter_setrelease(), limiter_setthreshold(), ps_dumpout, ps_exponential, ps_float32, ps_linear, ps_long, and ps_symbol.
Variable Documentation
t_class* limiter_class
Definition at line 55 of file jcom.limiter~.cpp.
Referenced by limiter_new(), and main().
t_symbol* ps_dumpout
Definition at line 61 of file jcom.limiter~.cpp.
t_symbol* ps_exponential
Definition at line 57 of file jcom.limiter~.cpp.
Referenced by limiter_new(), limiter_setmode(), and main().
t_symbol* ps_float32
Definition at line 60 of file jcom.limiter~.cpp.
t_symbol* ps_linear
Definition at line 56 of file jcom.limiter~.cpp.
t_symbol* ps_long
Definition at line 59 of file jcom.limiter~.cpp.
t_symbol* ps_symbol
Definition at line 58 of file jcom.limiter~.cpp.