Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.cpp File Reference
#include "jcom.hub.h"
#include <functional>
Classes
struct _subIsLess
A function object for determining if one t_subscriber object should follow another t_subscriber.
Defines
#define value value_list[0]
Functions
int main (void)
void * hub_new (t_symbol *s, long argc, t_atom *argv)
The jcom.hub constructor.
void hub_examine_context (t_hub *x)
void hub_free (t_hub *x)
The hub deconstructor, free's any memory used by the hub.
t_symbol * hub_subscribe (t_hub *x, t_symbol *name, t_object *subscriber_object, t_symbol *type)
This is called by clients who wish to register their parameters with the hub.
void hub_unsubscribe (t_hub *x, t_object *subscriber_object)
Unsubscribe a client from the hub.
void hub_receive (t_hub *x, t_symbol *name, long argc, t_atom *argv)
void hub_private (t_hub *x, t_symbol *name, long argc, t_atom *argv)
void hub_return (t_hub *x, t_symbol *name, long argc, t_atom *argv)
void hub_return_extended (t_hub *x, t_symbol *name, long argc, t_atom *argv)
void hub_outlet_return (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
t_symbol * hub_modulename_get (t_hub *x)
t_symbol * core_modulename_get (t_hub *x)
Returns the name of the module.
t_symbol * hub_algorithmtype_get (t_hub *x)
void hub_init (t_hub *x, t_symbol *, long, t_atom *)
Initializes any jcom.init objects that are subscribed to the hub by sending them a 'bang'.
void hub_qfn_init (t_hub *x)
void hub_gui_build (t_hub *x)
void hub_assist (t_hub *x, void *b, long msg, long arg, char *dst)
t_object * hub_getobj_audioin (t_hub *x)
t_object * hub_getobj_audioout (t_hub *x)
void hub_paramnames_get (t_hub *x)
void hub_paramvalues_get (t_hub *x)
void hub_messagenames_get (t_hub *x)
void hub_returnnames_get (t_hub *x)
void hub_allnames_get (t_hub *x)
void hub_symbol (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
void hub_module_view_alg (t_hub *x, t_symbol *, long, t_atom *)
void hub_ui_freeze (t_hub *x, t_symbol *, long argc, t_atom *argv)
Freeze updating of the UI.
void hub_ui_refresh (t_hub *x, t_symbol *, long, t_atom *)
Refresh the UI.
void hub_receive_callback (void *z, t_symbol *msg, long argc, t_atom *argv)
void hub_bang (t_hub *x)
When the hub receives a bang, it ask all parameters and messages using /drive async to update.
Variables
static t_class * s_hub_class
static t_object * s_jcom_send_notifications = NULL
_subIsLess subscriberIsLess
Define Documentation
#define value value_list[0]
Definition at line 14 of file jcom.hub.cpp.
Referenced by attr_set_bypass(), attr_set_freeze(), attr_set_gain(), attr_set_mix(), attr_set_mute(), attr_set_preview(), DataspaceLib::convert(), HSVUnit::convertFromNeutral(), HSVUnit::convertToNeutral(), count_tilde_perform(), interpolate_presets(), rgb2hsv(), round_list(), round_symbol(), and teabox_perform().
Function Documentation
t_symbol* core_modulename_get (t_hub * x)
Returns the name of the module.
Only really used by jcom.core.cpp
Returns:
the name of the module
Definition at line 599 of file jcom.hub.cpp.
References t_hub::attr_name.
Referenced by main().
t_symbol* hub_algorithmtype_get (t_hub * x)
Definition at line 604 of file jcom.hub.cpp.
References t_hub::attr_algorithm_type.
Referenced by main().
void hub_allnames_get (t_hub * x)
Definition at line 834 of file jcom.hub.cpp.
References hub_messagenames_get(), hub_paramnames_get(), and hub_returnnames_get().
Referenced by main().
void hub_assist (t_hub * x, void * b, long msg, long arg, char * dst)
Definition at line 704 of file jcom.hub.cpp.
References k_outlet_dumpout, and k_outlet_return.
Referenced by main().
void hub_bang (t_hub * x)
When the hub receives a bang, it ask all parameters and messages using /drive async to update.
Definition at line 1013 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_subscriber::object, ps_subscribe_message, ps_subscribe_parameter, t_hub::subscriber, and t_subscriber::type.
Referenced by main().
void hub_examine_context (t_hub * x)
Definition at line 207 of file jcom.hub.cpp.
References t_hub::attr_name, t_hub::container, jamoma_hub_register(), jamoma_patcher_getargs(), jamoma_patcher_getcontext(), jamoma_patcher_getvarname(), t_hub::osc_name, and s_jcom_send_notifications.
Referenced by hub_new().
void hub_free (t_hub * x)
The hub deconstructor, free's any memory used by the hub.
Parameters:
x the hub who's memory should be freed
See also:
hub_free
Definition at line 295 of file jcom.hub.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::clear(), jcomList< T >::end(), hub_internals_destroy(), hub_presets_clear(), t_hub::init_qelem, jamoma_hub_remove(), t_hub::jcom_receive, t_hub::jcom_send, t_hub::jcom_send_broadcast, t_hub::osc_name, t_hub::preset, ps_release, s_jcom_send_notifications, and t_hub::subscriber.
Referenced by main().
t_object* hub_getobj_audioin (t_hub * x)
Definition at line 722 of file jcom.hub.cpp.
References t_hub::attr_type, t_hub::in_object, and ps_audio.
Referenced by main().
t_object* hub_getobj_audioout (t_hub * x)
Definition at line 732 of file jcom.hub.cpp.
References t_hub::attr_type, t_hub::out_object, and ps_audio.
Referenced by main().
void hub_gui_build (t_hub * x)
Definition at line 637 of file jcom.hub.cpp.
References t_hub::attr_algorithm_type, t_hub::attr_inspector, t_hub::attr_name, t_hub::attr_size, t_hub::attr_skin, t_hub::attr_type, jcomList< T >::begin(), jcomList< T >::end(), t_hub::gui_object, t_subscriber::name, t_hub::osc_name, ps_algorithm_type, ps_ATTRIBUTES, ps_BUILD, ps_dispatched, ps_inspector, ps_MODULE_NAME, ps_MODULE_TITLE, ps_module_type, ps_PARAMETER, ps_size, ps_skin, ps_subscribe_message, ps_subscribe_parameter, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_qfn_init().
void hub_init (t_hub * x, t_symbol * , long , t_atom *)
Initializes any jcom.init objects that are subscribed to the hub by sending them a 'bang'.
Parameters:
x the hub who's subscribed jcom.init objects should be banged
Definition at line 610 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_preset_default(), ps_go, ps_subscribe_init, and t_hub::subscriber.
Referenced by hub_internals_create(), and hub_qfn_init().
void hub_messagenames_get (t_hub * x)
Definition at line 791 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_outlet_return(), t_subscriber::name, ps_message_name, ps_message_names_end, ps_message_names_start, ps_subscribe_message, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_allnames_get(), and main().
void hub_module_view_alg (t_hub * x, t_symbol * , long , t_atom *)
Definition at line 926 of file jcom.hub.cpp.
References hub_outlet_return(), t_hub::in_object, ps_open, and ps_slash_module_view_internals.
Referenced by hub_internals_create(), and hub_private().
t_symbol * hub_modulename_get (t_hub * x)
Definition at line 584 of file jcom.hub.cpp.
References t_hub::attr_name, hub_outlet_return(), and t_hub::osc_name.
Referenced by main().
void* hub_new (t_symbol * s, long argc, t_atom * argv)
The jcom.hub constructor.
Definition at line 126 of file jcom.hub.cpp.
References hub_examine_context(), hub_internals_create(), hub_qfn_init(), hub_receive_callback(), jamoma_object_getpatcher(), jcom_core_loadextern(), k_num_outlets, k_outlet_dumpout, MAX_NUM_CHANNELS, t_hub::outlets, ps_1U_half, ps_control, ps_default, ps_jcom_broadcast_fromHub, ps_jcom_receive, ps_jcom_remote_fromModule, ps_jcom_remote_toModule, ps_jcom_send, ps_setcallback, s_hub_class, and s_jcom_send_notifications.
Referenced by main().
void hub_outlet_return (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 566 of file jcom.hub.cpp.
References t_hub::jcom_send, k_outlet_return, t_hub::osc_name, and t_hub::outlets.
Referenced by hub_doautodoc(), hub_messagenames_get(), hub_module_view_alg(), hub_modulename_get(), hub_paramnames_get(), hub_paramvalues_get(), hub_receive(), hub_return(), hub_return_extended(), and hub_returnnames_get().
void hub_paramnames_get (t_hub * x)
Definition at line 742 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_outlet_return(), t_subscriber::name, ps_parameter_name, ps_parameter_names_end, ps_parameter_names_start, ps_subscribe_parameter, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_allnames_get(), and main().
void hub_paramvalues_get (t_hub * x)
Definition at line 764 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_outlet_return(), t_subscriber::name, t_subscriber::object, ps_parameter_value, ps_parameter_values_end, ps_parameter_values_start, ps_subscribe_parameter, ps_value, t_hub::subscriber, and t_subscriber::type.
Referenced by main().
void hub_private (t_hub * x, t_symbol * name, long argc, t_atom * argv)
Definition at line 477 of file jcom.hub.cpp.
References hub_module_view_alg(), hub_preset_copy(), hub_preset_default(), hub_preset_read(), hub_preset_recall(), hub_preset_store(), hub_preset_store_next(), hub_preset_write(), hub_symbol(), hub_ui_freeze(), hub_ui_refresh(), ps__gui__, ps_slash_module_view_internals, ps_slash_preset_slash_copy, ps_slash_preset_slash_default, ps_slash_preset_slash_load, ps_slash_preset_slash_recall, ps_slash_preset_slash_store, ps_slash_preset_slash_storenext, ps_slash_preset_slash_write, ps_slash_ui_slash_freeze, and ps_slash_ui_slash_refresh.
Referenced by main().
void hub_qfn_init (t_hub * x)
Definition at line 629 of file jcom.hub.cpp.
References hub_gui_build(), and hub_init().
Referenced by hub_new().
void hub_receive (t_hub * x, t_symbol * name, long argc, t_atom * argv)
Definition at line 454 of file jcom.hub.cpp.
References hub_internals_dispatch(), hub_outlet_return(), t_hub::in_object, t_hub::out_object, and ps_algorithm_message.
Referenced by main().
void hub_receive_callback (void * z, t_symbol * msg, long argc, t_atom * argv)
Definition at line 970 of file jcom.hub.cpp.
References t_hub::attr_name, t_hub::osc_name, and t_hub::using_wildcard.
Referenced by hub_new().
void hub_return (t_hub * x, t_symbol * name, long argc, t_atom * argv)
Definition at line 527 of file jcom.hub.cpp.
References hub_outlet_return().
Referenced by main().
void hub_return_extended (t_hub * x, t_symbol * name, long argc, t_atom * argv)
Definition at line 540 of file jcom.hub.cpp.
References hub_outlet_return().
Referenced by main().
void hub_returnnames_get (t_hub * x)
Definition at line 812 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_outlet_return(), t_subscriber::name, ps_message_return, ps_return_names_end, ps_return_names_start, ps_subscribe_return, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_allnames_get(), and main().
t_symbol* hub_subscribe (t_hub * x, t_symbol * name, t_object * param_object, t_symbol * type)
This is called by clients who wish to register their parameters with the hub.
Meaning these is typically called by jcom.parameter
Parameters:
x the hub the client wants to subscribe to
name the name of the subscribing object
param_object a pointer to the subscribing object itself
type the type of the object subscribing to the hub
Returns:
the name of the hub subscribed to
See also:
hub_unsubscribe
Definition at line 334 of file jcom.hub.cpp.
References t_hub::attr_name, t_hub::gui_object, t_hub::in_object, t_hub::init_qelem, MAX_NUM_CHANNELS, jcomList< T >::merge(), t_hub::meter_object, t_subscriber::name, t_hub::num_parameters, t_subscriber::object, t_hub::osc_name, t_hub::out_object, t_hub::preview_object, ps___preview__, ps__gui__, ps_link_in, ps_link_out, ps_register_meter, ps_register_preview, ps_subscribe_in, ps_subscribe_out, ps_subscribe_parameter, ps_subscribe_remote, t_hub::subscriber, subscriberIsLess, and t_subscriber::type.
Referenced by main().
void hub_symbol (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 843 of file jcom.hub.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::end(), jcom_core_atom_copy(), MAX_STRING_LEN, t_subscriber::name, t_subscriber::object, t_hub::osc_name, t_hub::out_object, ps_algorithm_message, ps_audio_meters_freeze, ps_dispatched, ps_slash_audio_meters_freeze, ps_star, ps_subscribe_message, ps_subscribe_parameter, ps_subscribe_return, t_hub::subscriber, t_subscriber::type, and t_hub::using_wildcard.
Referenced by hub_preset_recall(), hub_private(), interpolate_presets(), and main().
void hub_ui_freeze (t_hub * x, t_symbol * , long argc, t_atom * argv)
Freeze updating of the UI.
Parameters:
x a pointer to the hub
value non-zero to freeze UI updates, 0 to enable updating the UI
See also:
hub_ui_refresh
Definition at line 935 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_subscriber::object, ps_subscribe_parameter, ps_ui_slash_freeze, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_internals_create(), and hub_private().
void hub_ui_refresh (t_hub * x, t_symbol * , long , t_atom *)
Refresh the UI.
Parameters:
x a pointer to the hub
See also:
hub_ui_freeze
Definition at line 953 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_subscriber::object, ps_subscribe_parameter, ps_ui_slash_refresh, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_internals_create(), and hub_private().
void hub_unsubscribe (t_hub * x, t_object * subscriber_object)
Unsubscribe a client from the hub.
Parameters:
x the hub to be unsubscribed from
subscriber_object the object to unsubscribe
See also:
hub_subscribe
XXX why does this need to be here? It seems Microsoft's compiler is generating code that will preincrement (++) the item iterator in the for loop despite the fact that the for loops if condition has been met and following conditional statement shouldn't execute. Either that or something awkward about the the behavior of their STL implementation
Definition at line 403 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), jcomList< T >::erase(), t_hub::in_object, MAX_NUM_CHANNELS, t_subscriber::name, t_hub::num_parameters, t_subscriber::object, t_hub::out_object, ps_subscribe_in, ps_subscribe_out, ps_subscribe_parameter, ps_subscribe_remote, ps_unlink_in, ps_unlink_out, t_hub::subscriber, and t_subscriber::type.
Referenced by main().
int main (void)
Definition at line 32 of file jcom.hub.cpp.
References core_modulename_get(), hub_algorithmtype_get(), hub_allnames_get(), hub_assist(), hub_bang(), hub_free(), hub_getobj_audioin(), hub_getobj_audioout(), hub_messagenames_get(), hub_modulename_get(), hub_new(), hub_paramnames_get(), hub_paramvalues_get(), hub_private(), hub_receive(), hub_return(), hub_return_extended(), hub_returnnames_get(), hub_subscribe(), hub_symbol(), hub_unsubscribe(), jamoma_init(), and s_hub_class.
Variable Documentation
t_class* s_hub_class [static]
Definition at line 17 of file jcom.hub.cpp.
Referenced by hub_new(), and main().
t_object* s_jcom_send_notifications = NULL [static]
Definition at line 18 of file jcom.hub.cpp.
Referenced by hub_examine_context(), hub_free(), and hub_new().
_subIsLess subscriberIsLess
Referenced by hub_subscribe().