Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.pass/jcom.pass.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.pass/jcom.pass.cpp File Reference
#include "Jamoma.h"
Classes
struct t_pass
Defines
#define MAX_ARGCOUNT 100
#define MAX_MESS_SIZE 2048
Functions
void * pass_new (t_symbol *s, long argc, t_atom *argv)
void pass_assist (t_pass *x, void *b, long msg, long arg, char *dst)
void pass_int (t_pass *x, long n)
void pass_float (t_pass *x, double f)
void pass_symbol (t_pass *x, t_symbol *msg, long argc, t_atom *argv)
void pass_list (t_pass *x, t_symbol *msg, long argc, t_atom *argv)
int main (void)
Variables
t_class * pass_class
Define Documentation
#define MAX_ARGCOUNT 100
Definition at line 12 of file jcom.pass.cpp.
#define MAX_MESS_SIZE 2048
Definition at line 13 of file jcom.pass.cpp.
Function Documentation
int main (void)
Definition at line 41 of file jcom.pass.cpp.
References jamoma_init(), pass_assist(), pass_class, pass_float(), pass_int(), pass_list(), pass_new(), and pass_symbol().
void pass_assist (t_pass * x, void * b, long msg, long arg, char * dst)
Definition at line 128 of file jcom.pass.cpp.
References t_pass::arguments.
Referenced by main().
void pass_float (t_pass * x, double f)
Definition at line 175 of file jcom.pass.cpp.
References t_pass::arguments, t_pass::num_args, t_pass::outlet_overflow, and t_pass::outlets.
Referenced by main().
void pass_int (t_pass * x, long n)
Definition at line 158 of file jcom.pass.cpp.
References t_pass::arguments, t_pass::num_args, t_pass::outlet_overflow, and t_pass::outlets.
Referenced by main().
void pass_list (t_pass * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 221 of file jcom.pass.cpp.
References t_pass::arguments, t_pass::attr_strip, t_pass::num_args, t_pass::outlet_overflow, and t_pass::outlets.
Referenced by main().
void * pass_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 82 of file jcom.pass.cpp.
References MAX_MESS_SIZE, t_pass::outlet_overflow, and pass_class.
Referenced by main().
void pass_symbol (t_pass * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 192 of file jcom.pass.cpp.
References t_pass::arguments, t_pass::attr_strip, t_pass::attr_stripnonmatches, t_pass::num_args, t_pass::outlet_overflow, and t_pass::outlets.
Referenced by main().
Variable Documentation
t_class* pass_class
Definition at line 35 of file jcom.pass.cpp.
Referenced by main(), and pass_new().