Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.cubic_interpolate/jcom.cubic_interpolate.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.cubic_interpolate/jcom.cubic_interpolate.cpp File Reference
#include "Jamoma.h"
Classes
struct t_cubic_interp
Functions
void * cubic_interpolate_new (t_symbol *msg, long argc, t_atom *argv)
t_max_err cubic_interpolation_setstep (t_cubic_interp *x, void *attr, long argc, t_atom *argv)
void cubic_interpolate_bang (t_cubic_interp *x)
void cubic_interpolate_int (t_cubic_interp *x, long n)
void cubic_interpolate_float (t_cubic_interp *x, double f)
void cubic_interpolate_clear (t_cubic_interp *x)
void cubic_interpolate_assist (t_cubic_interp *x, void *b, long msg, long arg, char *dst)
int main (void)
Variables
t_class * this_class
Function Documentation
void cubic_interpolate_assist (t_cubic_interp * x, void * b, long msg, long arg, char * dst)
Definition at line 189 of file jcom.cubic_interpolate.cpp.
Referenced by main().
void cubic_interpolate_bang (t_cubic_interp * x)
Definition at line 116 of file jcom.cubic_interpolate.cpp.
References t_cubic_interp::attr_step, t_cubic_interp::clearflag, t_cubic_interp::mu, t_cubic_interp::outlet, t_cubic_interp::outlet2, and t_cubic_interp::value.
Referenced by main().
void cubic_interpolate_clear (t_cubic_interp * x)
Definition at line 181 of file jcom.cubic_interpolate.cpp.
References t_cubic_interp::clearflag, and t_cubic_interp::mu.
Referenced by cubic_interpolate_new(), and main().
void cubic_interpolate_float (t_cubic_interp * x, double f)
Definition at line 163 of file jcom.cubic_interpolate.cpp.
References t_cubic_interp::clearflag, and t_cubic_interp::value.
Referenced by cubic_interpolate_int(), and main().
void cubic_interpolate_int (t_cubic_interp * x, long n)
Definition at line 156 of file jcom.cubic_interpolate.cpp.
References cubic_interpolate_float().
Referenced by main().
void * cubic_interpolate_new (t_symbol * msg, long argc, t_atom * argv)
Definition at line 80 of file jcom.cubic_interpolate.cpp.
References t_cubic_interp::attr_step, cubic_interpolate_clear(), t_cubic_interp::outlet, t_cubic_interp::outlet2, and this_class.
Referenced by main().
t_max_err cubic_interpolation_setstep (t_cubic_interp * x, void * attr, long argc, t_atom * argv)
Definition at line 103 of file jcom.cubic_interpolate.cpp.
References t_cubic_interp::attr_step.
Referenced by main().
int main (void)
Definition at line 42 of file jcom.cubic_interpolate.cpp.
References cubic_interpolate_assist(), cubic_interpolate_bang(), cubic_interpolate_clear(), cubic_interpolate_float(), cubic_interpolate_int(), cubic_interpolate_new(), cubic_interpolation_setstep(), jamoma_init(), and this_class.
Variable Documentation
t_class* this_class
Definition at line 35 of file jcom.cubic_interpolate.cpp.