Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.delta/jcom.delta.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.delta/jcom.delta.cpp File Reference
#include "Jamoma.h"
Classes
struct t_delta
Functions
void * delta_new (void)
void delta_bang (t_delta *x)
void delta_int (t_delta *x, long n)
void delta_float (t_delta *x, double f)
void delta_clear (t_delta *x)
void delta_set (t_delta *x, Symbol *s, short ac, Atom *setval)
void delta_assist (t_delta *x, void *b, long msg, long arg, char *dst)
int main (void)
Variables
t_class * this_class
Function Documentation
void delta_assist (t_delta * x, void * b, long msg, long arg, char * dst)
Definition at line 239 of file jcom.delta.cpp.
Referenced by main().
void delta_bang (t_delta * x)
Definition at line 168 of file jcom.delta.cpp.
References t_delta::delta, and t_delta::outlet.
Referenced by delta_float(), and main().
void delta_clear (t_delta * x)
Definition at line 231 of file jcom.delta.cpp.
References t_delta::clearflag, and t_delta::delta.
Referenced by delta_new(), and main().
void delta_float (t_delta * x, double f)
Definition at line 185 of file jcom.delta.cpp.
References t_delta::clearflag, t_delta::delta, delta_bang(), and t_delta::prev.
Referenced by delta_int(), and main().
void delta_int (t_delta * x, long n)
Definition at line 175 of file jcom.delta.cpp.
References delta_float().
Referenced by main().
void * delta_new (void)
Definition at line 149 of file jcom.delta.cpp.
References delta_clear(), and this_class.
Referenced by main().
void delta_set (t_delta * x, Symbol * s, short ac, Atom * setval)
Definition at line 201 of file jcom.delta.cpp.
References t_delta::clearflag, t_delta::delta, and t_delta::prev.
Referenced by main().
int main (void)
Definition at line 115 of file jcom.delta.cpp.
References delta_assist(), delta_bang(), delta_clear(), delta_float(), delta_int(), delta_new(), delta_set(), jamoma_init(), and this_class.
Variable Documentation
t_class* this_class
Definition at line 108 of file jcom.delta.cpp.