Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.gang/jcom.gang.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.gang/jcom.gang.cpp File Reference
#include "Jamoma.h"
Classes
struct t_gang
Defines
#define NUM_INLETS 4
#define NUM_OUTLETS 4
#define MAX_LIST_LENGTH 256
Functions
void * gang_new (t_symbol *msg, long argc, t_atom *argv)
void gang_free (t_gang *x)
void gang_assist (t_gang *x, void *b, long msg, long arg, char *dst)
void gang_int (t_gang *x, long value)
void gang_float (t_gang *x, double value)
void gang_list (t_gang *x, t_symbol *msg, long argc, t_atom *argv)
void gang_qfn_send_pp (t_gang *x)
void gang_qfn_send_ui (t_gang *x)
void gang_qfn_send_pattr (t_gang *x)
void gang_qfn_send_scope (t_gang *x)
float gang_bitsafe (double in)
int main (void)
Variables
t_class * gang_class
Define Documentation
#define MAX_LIST_LENGTH 256
Definition at line 8 of file jcom.gang.cpp.
Referenced by find_match(), gang_list(), and main().
#define NUM_INLETS 4
Definition at line 6 of file jcom.gang.cpp.
Referenced by gang_free(), and gang_new().
#define NUM_OUTLETS 4
Definition at line 7 of file jcom.gang.cpp.
Referenced by gang_new().
Function Documentation
void gang_assist (t_gang * x, void * b, long msg, long arg, char * dst)
Definition at line 124 of file jcom.gang.cpp.
Referenced by main().
float gang_bitsafe (double in)
Definition at line 293 of file jcom.gang.cpp.
Referenced by gang_float(), and gang_list().
void gang_float (t_gang * x, double value)
Definition at line 154 of file jcom.gang.cpp.
References gang_bitsafe().
Referenced by gang_int(), and main().
void gang_free (t_gang * x)
Definition at line 107 of file jcom.gang.cpp.
References t_gang::inlets, NUM_INLETS, t_gang::qelem_send_pattr, t_gang::qelem_send_pp, t_gang::qelem_send_scope, and t_gang::qelem_send_ui.
Referenced by main().
void gang_int (t_gang * x, long value)
Definition at line 147 of file jcom.gang.cpp.
References gang_float().
Referenced by main().
void gang_list (t_gang * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 191 of file jcom.gang.cpp.
References gang_bitsafe(), and MAX_LIST_LENGTH.
Referenced by main().
void * gang_new (t_symbol * msg, long argc, t_atom * argv)
Definition at line 74 of file jcom.gang.cpp.
References gang_class, gang_qfn_send_pattr(), gang_qfn_send_pp(), gang_qfn_send_scope(), gang_qfn_send_ui(), NUM_INLETS, and NUM_OUTLETS.
Referenced by main().
void gang_qfn_send_pattr (t_gang * x)
Definition at line 268 of file jcom.gang.cpp.
References t_gang::argc, t_gang::argv, t_gang::outlets, t_gang::parameter_value, t_gang::parameter_value_pp, t_gang::set_by_pp, and t_gang::type_is_list.
Referenced by gang_new().
void gang_qfn_send_pp (t_gang * x)
Definition at line 256 of file jcom.gang.cpp.
References t_gang::argc, t_gang::argv, t_gang::outlets, t_gang::parameter_value, t_gang::parameter_value_pp, t_gang::set_by_pp, and t_gang::type_is_list.
Referenced by gang_new().
void gang_qfn_send_scope (t_gang * x)
Definition at line 280 of file jcom.gang.cpp.
References t_gang::argc, t_gang::argv, t_gang::outlets, t_gang::parameter_value, t_gang::parameter_value_pp, t_gang::set_by_pp, and t_gang::type_is_list.
Referenced by gang_new().
void gang_qfn_send_ui (t_gang * x)
Definition at line 244 of file jcom.gang.cpp.
References t_gang::argc, t_gang::argv, t_gang::outlets, t_gang::parameter_value, t_gang::parameter_value_pp, t_gang::set_by_pp, and t_gang::type_is_list.
Referenced by gang_new().
int main (void)
Definition at line 49 of file jcom.gang.cpp.
References gang_assist(), gang_class, gang_float(), gang_free(), gang_int(), gang_list(), gang_new(), and jamoma_init().
Variable Documentation
t_class* gang_class
Definition at line 43 of file jcom.gang.cpp.
Referenced by gang_new(), and main().