Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/source/jcom.core.h File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/source/jcom.core.h File Reference
#include "ext.h"
#include "ext_obex.h"
#include "ext_critical.h"
#include "z_dsp.h"
Classes
struct t_jcom_core_subscriber_common
shared common subscriber data members !!! WARNING !!! This struct MUST be the first member of the object in which it is contained !!!
struct t_jcom_core_subscriber_extended
shared extended subscriber data members an extended subscriber is something such as jcom.parameter, jcom.message or jcom.return !!! WARNING !!! This struct MUST be the first member of the object in which it is contained !!!
Typedefs
typedef void(* t_receive_obex_callback)(void *x, t_symbol *msg, long argc, t_atom *argv)
typedef void(* t_subscribe_method)(void *x)
Functions
t_object * jcom_core_subscribe (t_object *x, t_symbol *name, t_object *container, t_symbol *object_type)
Register (or unregister) a client (such as jcom.parameter or jcom.in~) with the jcom.hub object.
void jcom_core_unsubscribe (t_object *hub, void *object)
Unsubscribe a client from the hub.
void jcom_core_atom_copy (t_atom *dst, t_atom *src)
Utility function to perform an atom copy.
bool jcom_core_atom_compare (t_symbol *type, t_atom *a1, t_atom *a2)
Utility function to compare two t_atom's.
void jcom_core_file_writeline (t_filehandle *fh, long *the_eof, char *the_text)
Utility for writing newline terminated text to a file with the Max API.
bool jcom_core_string_compare (char *s1, char *s2)
Compares two strings.
bool jcom_core_loadextern (t_symbol *objectname, long argc, t_atom *argv, t_object **object)
Load obex externals for use within other externals.
void jcom_core_getfilepath (short in_path, char *in_filename, char *out_filepath)
Translates a Max path+filename combo into a correct absolutepath.
void jcom_core_subscriber_classinit_common (t_class *c, t_object *attr, long offset, bool define_name=true)
Add methods and attributes that are common to all subscribers.
void jcom_core_subscriber_classinit_extended (t_class *c, t_object *attr, long offset, bool define_name=true)
Add methods and attributes that are common to extended subscribers (such as parameter, message, and return).
void jcom_core_subscriber_new_common (t_jcom_core_subscriber_common *x, t_symbol *name, t_symbol *subscriber_type)
Call this when initing a new common-based instance to set defaults.
void jcom_core_subscriber_new_extended (t_jcom_core_subscriber_extended *x, t_symbol *name, t_symbol *subscriber_type)
Call this when initing a new extended-based instance to set defaults.
t_max_err jcom_core_subscriber_attribute_common_setname (t_jcom_core_subscriber_common *x, void *attr, long argc, t_atom *argv)
Attribute setter used for the parameter name as referenced in jcom_core_subscriber_attributes_common WARNING: This method REQUIRES that the t_jcom_core_subscriber data structure is the second member of the object's struct!
void jcom_core_subscriber_subscribe (t_jcom_core_subscriber_common *x)
Subscribe to the hub.
void jcom_core_subscriber_hubrelease (t_jcom_core_subscriber_common *x)
Receive notification that the hub has been freed, so we shouldn't call it anymore.
void jcom_core_subscriber_setcustomsubscribe_method (t_jcom_core_subscriber_common *x, t_subscribe_method meth)
Provide a function for doing additional setup at subscription time.
void jcom_core_subscriber_common_free (t_jcom_core_subscriber_common *x)
This should be called by subscribers when they are being freed.
void jcom_core_broadcast_callback (void *z, t_symbol *msg, long argc, t_atom *argv)
This method is called when the jcom.receive in a subscriber receives the hub's broadcast messages.
t_max_err jcom_core_attr_getname (t_jcom_core_subscriber_extended *x, void *attr, long *argc, t_atom **argv)
t_max_err jcom_core_attr_setrange (t_jcom_core_subscriber_extended *x, void *attr, long argc, t_atom *argv)
t_max_err jcom_core_attr_getrange (t_jcom_core_subscriber_extended *x, void *attr, long *argc, t_atom **argv)
t_max_err jcom_core_attr_getrepetitions (t_jcom_core_subscriber_extended *x, void *attr, long *argc, t_atom **argv)
t_max_err jcom_core_attr_getclipmode (t_jcom_core_subscriber_extended *x, void *attr, long *argc, t_atom **argv)
t_max_err jcom_core_attr_getdescription (t_jcom_core_subscriber_extended *x, void *attr, long *argc, t_atom **argv)
Typedef Documentation
typedef void(* t_receive_obex_callback)(void *x, t_symbol *msg, long argc, t_atom *argv)
Definition at line 27 of file jcom.core.h.
typedef void(* t_subscribe_method)(void *x)
Definition at line 28 of file jcom.core.h.
Function Documentation
bool jcom_core_atom_compare (t_symbol * type, t_atom * a1, t_atom * a2)
Utility function to compare two t_atom's.
Parameters:
type the atom type of a1
a1 a t_atom
a2 the t_atom to compare against
Returns:
true if the t_atom's are the same
Definition at line 98 of file jcom.core.cpp.
References ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_list, ps_msg_symbol, and ps_msg_toggle.
Referenced by param_symbol().
void jcom_core_atom_copy (t_atom * dst, t_atom * src)
Utility function to perform an atom copy.
Parameters:
dst the destination t_atom
src the t_atom to be copied
Definition at line 91 of file jcom.core.cpp.
Referenced by hub_symbol(), param_bang(), param_dispatched(), param_dump(), param_list(), param_output_none(), param_send_feedback(), remote_list(), remote_symbol(), return_list(), and return_symbol().
t_max_err jcom_core_attr_getclipmode (t_jcom_core_subscriber_extended * x, void * attr, long * argc, t_atom ** argv)
Definition at line 451 of file jcom.core.cpp.
References t_jcom_core_subscriber_extended::attr_clipmode.
Referenced by jcom_core_subscriber_classinit_extended().
t_max_err jcom_core_attr_getdescription (t_jcom_core_subscriber_extended * x, void * attr, long * argc, t_atom ** argv)
Definition at line 463 of file jcom.core.cpp.
References t_jcom_core_subscriber_extended::attr_description.
Referenced by jcom_core_subscriber_classinit_extended().
t_max_err jcom_core_attr_getname (t_jcom_core_subscriber_extended * x, void * attr, long * argc, t_atom ** argv)
Definition at line 391 of file jcom.core.cpp.
References t_jcom_core_subscriber_extended::attr_name.
Referenced by jcom_core_subscriber_classinit_common().
t_max_err jcom_core_attr_getrange (t_jcom_core_subscriber_extended * x, void * attr, long * argc, t_atom ** argv)
Definition at line 415 of file jcom.core.cpp.
References t_jcom_core_subscriber_extended::attr_description, and t_jcom_core_subscriber_extended::attr_range.
Referenced by jcom_core_subscriber_classinit_extended().
t_max_err jcom_core_attr_getrepetitions (t_jcom_core_subscriber_extended * x, void * attr, long * argc, t_atom ** argv)
Definition at line 439 of file jcom.core.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions.
Referenced by jcom_core_subscriber_classinit_extended().
t_max_err jcom_core_attr_setrange (t_jcom_core_subscriber_extended * x, void * attr, long argc, t_atom * argv)
Definition at line 405 of file jcom.core.cpp.
References t_jcom_core_subscriber_extended::attr_range.
Referenced by jcom_core_subscriber_classinit_extended().
void jcom_core_broadcast_callback (void * z, t_symbol * msg, long argc, t_atom * argv)
This method is called when the jcom.receive in a subscriber receives the hub's broadcast messages.
Definition at line 368 of file jcom.core.cpp.
References jcom_core_subscriber_subscribe().
Referenced by jcom_core_subscriber_new_common().
void jcom_core_file_writeline (t_filehandle * fh, long * the_eof, char * the_text)
Utility for writing newline terminated text to a file with the Max API.
Definition at line 139 of file jcom.core.cpp.
Referenced by hub_autodoc_css(), hub_doautodoc(), hub_preset_dowrite(), and table_heading().
void jcom_core_getfilepath (short in_path, char * in_filename, char * out_filepath)
Translates a Max path+filename combo into a correct absolutepath.
Parameters:
in_path
in_filename the filename
filepath the path
Definition at line 214 of file jcom.core.cpp.
Referenced by hub_preset_doread(), and hub_preset_validate().
bool jcom_core_loadextern (t_symbol * objectname, long argc, t_atom * argv, t_object ** object)
Load obex externals for use within other externals.
Parameters:
objectname the object name (i.e. gensym("jcom.send"))
argc number of arguments to the external to be loaded
argv pointer to the first of an array of atom arguments to the external that is to be loaded
object if successful pointer to the object pointer
Returns:
true if successfully loaded, otherwise false
Definition at line 183 of file jcom.core.cpp.
References ps_box.
Referenced by hub_new(), hubInternalObject::hubInternalObject(), jcom_core_subscriber_new_common(), paramui_new(), ui_new(), and uiInternalObject::uiInternalObject().
bool jcom_core_string_compare (char * s1, char * s2)
Compares two strings.
Returns:
true if the strings are the same
Definition at line 158 of file jcom.core.cpp.
Referenced by _subIsLess::operator()().
t_object* jcom_core_subscribe (t_object * x, t_symbol * name, t_object * container, t_symbol * object_type)
Register (or unregister) a client (such as jcom.parameter or jcom.in~) with the jcom.hub object.
Parameters:
x pointer to the object that is subscribing
name name of the parameter, message, return, in, out, etc.
container pointer to patcher containg the parameter, in, out, etc.
Returns:
a pointer to the hub object
Definition at line 19 of file jcom.core.cpp.
References max5, ps_jcom_hub, and ps_subscribe.
Referenced by jcom_core_subscriber_subscribe().
t_max_err jcom_core_subscriber_attribute_common_setname (t_jcom_core_subscriber_common * x, void * attr, long argc, t_atom * argv)
Attribute setter used for the parameter name as referenced in jcom_core_subscriber_attributes_common WARNING: This method REQUIRES that the t_jcom_core_subscriber data structure is the second member of the object's struct!
Definition at line 378 of file jcom.core.cpp.
References t_jcom_core_subscriber_common::attr_name, and t_jcom_core_subscriber_common::has_wildcard.
Referenced by jcom_core_subscriber_classinit_common(), and jcom_core_subscriber_new_common().
void jcom_core_subscriber_classinit_common (t_class * c, t_object * attr, long offset, bool define_name = true)
Add methods and attributes that are common to all subscribers.
Parameters:
pointer to the class that is being constructed
pointer to the attr list being constructed for this class
common a pointer to the struct that contains all of the common members for the object
optional bool parameter (default = true) that says whether or not to define a name attribute for this class
Definition at line 235 of file jcom.core.cpp.
References jamoma_class_attr_new(), jcom_core_attr_getname(), jcom_core_subscriber_attribute_common_setname(), and jcom_core_subscriber_hubrelease().
Referenced by jcom_core_subscriber_classinit_extended(), and main().
void jcom_core_subscriber_classinit_extended (t_class * c, t_object * attr, long offset, bool define_name = true)
Add methods and attributes that are common to extended subscribers (such as parameter, message, and return).
Parameters:
pointer to the class that is being constructed
pointer to the attr list being constructed for this class
common a pointer to the struct that contains all of the common members for the object
optional bool parameter (default = true) that says whether or not to define a name attribute for this class
Definition at line 254 of file jcom.core.cpp.
References jamoma_class_attr_array_new(), jamoma_class_attr_new(), jcom_core_attr_getclipmode(), jcom_core_attr_getdescription(), jcom_core_attr_getrange(), jcom_core_attr_getrepetitions(), jcom_core_attr_setrange(), and jcom_core_subscriber_classinit_common().
Referenced by main().
void jcom_core_subscriber_common_free (t_jcom_core_subscriber_common * x)
This should be called by subscribers when they are being freed.
If the module has no other special freeing to do, then this can be called as the destructor.
Definition at line 358 of file jcom.core.cpp.
References t_jcom_core_subscriber_common::hub, jcom_core_unsubscribe(), and t_jcom_core_subscriber_common::obj_hub_broadcast.
Referenced by in_free(), main(), out_free(), and param_free().
void jcom_core_subscriber_hubrelease (t_jcom_core_subscriber_common * x)
Receive notification that the hub has been freed, so we shouldn't call it anymore.
Definition at line 344 of file jcom.core.cpp.
References t_jcom_core_subscriber_common::hub.
Referenced by in_release(), jcom_core_subscriber_classinit_common(), and out_release().
void jcom_core_subscriber_new_common (t_jcom_core_subscriber_common * x, t_symbol * name, t_symbol * subscriber_type)
Call this when initing a new common-based instance to set defaults.
Definition at line 290 of file jcom.core.cpp.
References t_jcom_core_subscriber_common::container, t_jcom_core_subscriber_common::custom_subscribe, t_jcom_core_subscriber_common::hub, jamoma_object_getpatcher(), jcom_core_broadcast_callback(), jcom_core_loadextern(), jcom_core_subscriber_attribute_common_setname(), t_jcom_core_subscriber_common::module_name, t_jcom_core_subscriber_common::obj_hub_broadcast, ps_jcom_broadcast_fromHub, ps_jcom_receive, ps_setcallback, and t_jcom_core_subscriber_common::subscriber_type.
Referenced by in_new(), init_new(), jcom_core_subscriber_new_extended(), out_new(), and remote_new().
void jcom_core_subscriber_new_extended (t_jcom_core_subscriber_extended * x, t_symbol * name, t_symbol * subscriber_type)
Call this when initing a new extended-based instance to set defaults.
Definition at line 317 of file jcom.core.cpp.
References jcom_core_subscriber_new_common(), ps_msg_generic, and ps_none.
Referenced by param_new(), and return_new().
void jcom_core_subscriber_setcustomsubscribe_method (t_jcom_core_subscriber_common * x, t_subscribe_method meth)
Provide a function for doing additional setup at subscription time.
Definition at line 351 of file jcom.core.cpp.
References t_jcom_core_subscriber_common::custom_subscribe.
Referenced by in_new(), out_new(), and remote_new().
void jcom_core_subscriber_subscribe (t_jcom_core_subscriber_common * x)
Subscribe to the hub.
Definition at line 331 of file jcom.core.cpp.
References t_jcom_core_subscriber_common::attr_name, t_jcom_core_subscriber_common::hub, jcom_core_subscribe(), and ps_core_module_name_get.
Referenced by in_new(), init_new(), jcom_core_broadcast_callback(), out_new(), param_new(), remote_new(), and return_new().
void jcom_core_unsubscribe (t_object * hub, void * object)
Unsubscribe a client from the hub.
Parameters:
hub pointer to the hub
object pointer to the parameter/message/in/out/etc object that we are removing
Definition at line 79 of file jcom.core.cpp.
References ps_unsubscribe.
Referenced by jcom_core_subscriber_common_free().