Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.parameter/jcom.parameter.h File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.parameter/jcom.parameter.h File Reference
#include "Jamoma.h"
Classes
struct t_param
Defines
#define OBJECT_CLASS_NAME "jcom.parameter"
#define LISTSIZE 512
#define attr_value atom_list[0]
#define attr_valueDefault atom_listDefault[0]
Typedefs
typedef void(* pf_noargs)(void *x)
Enumerations
enum outlets {
k_outlet_return = 0, k_outlet_dumpout, k_num_outlets, k_outlet_set = 0,
k_outlet_direct, k_outlet_dumpout, num_outlets, k_outlet_value = 0,
k_outlet_dumpout, num_outlets, k_outlet_thru = 0, k_outlet_dumpout,
num_outlets
}
Functions
void * param_new (t_symbol *s, long argc, t_atom *argv)
void param_free (t_param *x)
void param_assist (t_param *x, void *b, long msg, long arg, char *dst)
void param_dump (t_param *x)
void param_bang (t_param *x)
void param_output_int (void *z)
void param_output_float (void *z)
void param_output_symbol (void *z)
void param_output_generic (void *z)
void param_output_list (void *z)
void param_output_none (void *z)
void param_inc (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_dec (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_rampUpdate (t_param *x)
If the hub receives a bang, it's passed on to this method, and used to update value if @/ramp/drive is set to "async".
void param_int (t_param *x, long n)
void param_float (t_param *x, double f)
void param_symbol (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_send_feedback (t_param *x)
void param_list (t_param *x, t_symbol *msg, long argc, t_atom *argv)
void param_ramp_callback_float (void *v, float value)
void param_ramp_callback_int (void *v, float value)
void param_ramp_callback_list (void *v, short argc, double *value)
void atom_clip (t_param *x, t_atom *a)
void param_dispatched (t_param *x, t_symbol *msg, long argc, t_atom *argv)
t_max_err param_attr_setramp (t_param *x, void *attr, long argc, t_atom *argv)
t_max_err param_attr_getramp (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_settype (t_param *x, void *attr, long argc, t_atom *argv)
t_max_err param_attr_gettype (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_getfreeze (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_getstepsize (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_getpriority (t_param *x, void *attr, long *argc, t_atom **argv)
t_max_err param_attr_getvalue (t_param *x, void *attr, long *argc, t_atom **argv)
void param_ramp_setup (t_param *x)
void param_ui_refresh (t_param *x)
void param_ui_queuefn (t_param *x)
t_max_err param_setvalueof (t_param *x, long argc, t_atom *argv)
t_max_err param_getvalueof (t_param *x, long *argc, t_atom **argv)
void param_reset (t_param *x)
void param_setcallback (t_param *x, method newCallback, t_object *callbackArg)
t_max_err param_attr_setrampfunction (t_param *x, void *attr, long argc, t_atom *argv)
t_max_err param_attr_getrampfunction (t_param *x, void *attr, long *argc, t_atom **argv)
void param_getRampFunctionParameter (t_param *obj, t_symbol *msg, long argc, t_atom *argv)
void param_setRampFunctionParameter (t_param *obj, t_symbol *msg, long argc, t_atom *argv)
void param_getRampDriveParameter (t_param *obj, t_symbol *msg, long argc, t_atom *argv)
void param_setRampDriveParameter (t_param *obj, t_symbol *msg, long argc, t_atom *argv)
void param_clip_generic (t_param *x)
void param_clip_int (t_param *x)
void param_clip_float (t_param *x)
void param_clip_list (t_param *x)
Define Documentation
#define attr_value atom_list[0]
Definition at line 34 of file jcom.parameter.h.
Referenced by main().
#define attr_valueDefault atom_listDefault[0]
Definition at line 35 of file jcom.parameter.h.
Referenced by main().
#define LISTSIZE 512
Definition at line 23 of file jcom.parameter.h.
#define OBJECT_CLASS_NAME "jcom.parameter"
Definition at line 16 of file jcom.parameter.h.
Referenced by main().
Typedef Documentation
typedef void(* pf_noargs)(void *x)
Definition at line 32 of file jcom.parameter.h.
Enumeration Type Documentation
enum outlets
Enumerator:
k_outlet_return
k_outlet_dumpout
k_num_outlets
k_outlet_set
k_outlet_direct
k_outlet_dumpout
num_outlets
k_outlet_value
k_outlet_dumpout
num_outlets
k_outlet_thru
k_outlet_dumpout
num_outlets
Definition at line 25 of file jcom.parameter.h.
Function Documentation
void atom_clip (t_param * x, t_atom * a)
void param_assist (t_param * x, void * b, long msg, long arg, char * dst)
Definition at line 575 of file jcom.parameter.cpp.
References k_outlet_direct, k_outlet_dumpout, and k_outlet_set.
Referenced by main().
t_max_err param_attr_getfreeze (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 393 of file jcom.parameter.cpp.
References t_param::attr_ui_freeze.
Referenced by main().
t_max_err param_attr_getpriority (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 417 of file jcom.parameter.cpp.
References t_param::attr_priority.
Referenced by main().
t_max_err param_attr_getramp (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 345 of file jcom.parameter.cpp.
References t_param::attr_ramp.
Referenced by main().
t_max_err param_attr_getrampfunction (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 369 of file jcom.parameter.cpp.
References t_param::attr_rampfunction.
Referenced by main().
t_max_err param_attr_getstepsize (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 405 of file jcom.parameter.cpp.
References t_param::attr_stepsize.
Referenced by main().
t_max_err param_attr_gettype (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 381 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_type, and t_param::common.
Referenced by main().
t_max_err param_attr_getvalue (t_param * x, void * attr, long * argc, t_atom ** argv)
Definition at line 429 of file jcom.parameter.cpp.
References t_param::atom_list, and t_param::list_size.
Referenced by main().
t_max_err param_attr_setramp (t_param * x, void * attr, long argc, t_atom * argv)
Definition at line 334 of file jcom.parameter.cpp.
References t_param::attr_ramp, and t_param::ramp_qelem.
Referenced by main().
t_max_err param_attr_setrampfunction (t_param * x, void * attr, long argc, t_atom * argv)
Definition at line 357 of file jcom.parameter.cpp.
References t_param::attr_rampfunction, and t_param::ramper.
Referenced by main().
t_max_err param_attr_settype (t_param * x, void * attr, long argc, t_atom * argv)
Definition at line 287 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_type, t_param::common, t_jcom_core_subscriber_extended::module_name, t_param::name, t_param::param_output, param_output_float(), param_output_generic(), param_output_int(), param_output_list(), param_output_none(), param_output_symbol(), ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_list, ps_msg_none, ps_msg_symbol, ps_msg_toggle, and t_param::ramp_qelem.
Referenced by main().
void param_bang (t_param * x)
Definition at line 652 of file jcom.parameter.cpp.
References t_param::atom_list, t_param::callback, t_param::common, t_jcom_core_subscriber_extended::hub, jcom_core_atom_copy(), k_outlet_direct, k_outlet_set, t_param::list_size, t_param::name, t_param::name_atom, t_param::outlets, t_param::param_output, and ps_feedback.
Referenced by main().
void param_clip_float (t_param * x)
Definition at line 42 of file jcom.parameter.clip.cpp.
References t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_range, t_param::common, ps_both, ps_high, and ps_low.
Referenced by param_clip_generic(), and param_output_float().
void param_clip_generic (t_param * x)
Definition at line 14 of file jcom.parameter.clip.cpp.
References t_param::atom_list, t_param::list_size, param_clip_float(), param_clip_int(), and param_clip_list().
Referenced by param_output_generic().
void param_clip_int (t_param * x)
Definition at line 26 of file jcom.parameter.clip.cpp.
References t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_range, t_param::common, ps_both, ps_high, and ps_low.
Referenced by param_clip_generic(), and param_output_int().
void param_clip_list (t_param * x)
Definition at line 58 of file jcom.parameter.clip.cpp.
References t_param::atom_list, t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_range, t_param::common, t_param::list_size, ps_both, ps_high, and ps_low.
Referenced by param_clip_generic(), and param_output_list().
void param_dec (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 827 of file jcom.parameter.cpp.
References t_param::attr_slavemode, t_param::attr_stepsize, t_jcom_core_subscriber_extended::attr_type, t_param::common, k_outlet_direct, t_param::outlets, param_dispatched(), param_output_int(), ps_dec, ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_toggle, ps_ramp, t_param::ramper, and RampUnit::stop().
Referenced by main().
void param_dispatched (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 1017 of file jcom.parameter.cpp.
References t_param::atom_list, t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_jcom_core_subscriber_extended::attr_type, t_param::common, jcom_core_atom_copy(), k_outlet_direct, t_param::list_size, t_param::outlets, param_list(), param_list_compare(), t_param::param_output, ps_msg_generic, t_param::ramper, and RampUnit::stop().
Referenced by main(), param_dec(), and param_inc().
void param_dump (t_param * x)
Definition at line 596 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_description, t_jcom_core_subscriber_extended::attr_name, t_param::attr_priority, t_param::attr_ramp, t_jcom_core_subscriber_extended::attr_range, t_jcom_core_subscriber_extended::attr_repetitions, t_jcom_core_subscriber_extended::attr_type, t_param::attr_ui_freeze, t_param::common, t_jcom_core_subscriber_extended::hub, jcom_core_atom_copy(), and ps_feedback.
Referenced by main().
void param_float (t_param * x, double f)
Definition at line 930 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_param::common, k_outlet_direct, t_param::list_size, t_param::outlets, t_param::param_output, t_param::ramper, and RampUnit::stop().
Referenced by main().
void param_free (t_param * x)
Definition at line 212 of file jcom.parameter.cpp.
References jcom_core_subscriber_common_free().
Referenced by main().
void param_getRampDriveParameter (t_param * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 507 of file jcom.parameter.cpp.
References t_param::ramper.
Referenced by main().
void param_getRampFunctionParameter (t_param * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 441 of file jcom.parameter.cpp.
References RampUnit::getFunctionParameterValue(), and t_param::ramper.
Referenced by main().
t_max_err param_getvalueof (t_param * x, long * argc, t_atom ** argv)
Definition at line 240 of file jcom.parameter.cpp.
References t_param::atom_list, and t_param::list_size.
void param_inc (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 757 of file jcom.parameter.cpp.
References t_param::attr_slavemode, t_param::attr_stepsize, t_jcom_core_subscriber_extended::attr_type, t_param::common, k_outlet_direct, t_param::outlets, param_dispatched(), param_output_int(), ps_inc, ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_toggle, ps_ramp, t_param::ramper, and RampUnit::stop().
Referenced by main().
void param_int (t_param * x, long n)
Definition at line 909 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_param::common, k_outlet_direct, t_param::list_size, t_param::outlets, t_param::param_output, t_param::ramper, and RampUnit::stop().
Referenced by main().
void param_list (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 1100 of file jcom.parameter.cpp.
References t_param::atom_list, t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_jcom_core_subscriber_extended::attr_type, t_param::common, RampUnit::go(), jcom_core_atom_copy(), k_outlet_direct, t_param::list_size, LISTSIZE, t_param::outlets, param_list_compare(), t_param::param_output, ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_list, ps_msg_none, ps_ramp, t_param::ramper, and RampUnit::set().
Referenced by main(), and param_dispatched().
void* param_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 136 of file jcom.parameter.cpp.
References jcom_core_subscriber_new_extended(), jcom_core_subscriber_subscribe(), k_outlet_dumpout, LISTSIZE, message_class, num_outlets, t_param::outlets, param_output_generic(), param_ramp_setup(), param_reset(), param_ui_queuefn(), parameter_class, ps_msg_generic, ps_none, ps_subscribe_message, ps_subscribe_parameter, and ps_type.
Referenced by main().
void param_output_float (void * z)
Definition at line 709 of file jcom.parameter.cpp.
References k_outlet_direct, t_param::outlets, param_clip_float(), and param_send_feedback().
Referenced by param_attr_settype(), and param_ramp_callback_float().
void param_output_generic (void * z)
Definition at line 675 of file jcom.parameter.cpp.
References t_param::atom_list, k_outlet_direct, t_param::list_size, t_param::outlets, param_clip_generic(), param_output_none(), and param_send_feedback().
Referenced by param_attr_settype(), and param_new().
void param_output_int (void * z)
Definition at line 699 of file jcom.parameter.cpp.
References k_outlet_direct, t_param::outlets, param_clip_int(), and param_send_feedback().
Referenced by param_attr_settype(), param_dec(), param_inc(), and param_ramp_callback_int().
void param_output_list (void * z)
Definition at line 728 of file jcom.parameter.cpp.
References t_param::atom_list, k_outlet_direct, t_param::list_size, t_param::outlets, param_clip_list(), and param_send_feedback().
Referenced by param_attr_settype(), and param_ramp_callback_list().
void param_output_none (void * z)
Definition at line 738 of file jcom.parameter.cpp.
References t_param::common, t_jcom_core_subscriber_extended::hub, jcom_core_atom_copy(), k_outlet_direct, t_param::name_atom, t_param::outlets, and ps_feedback.
Referenced by param_attr_settype(), and param_output_generic().
void param_output_symbol (void * z)
Definition at line 719 of file jcom.parameter.cpp.
References k_outlet_direct, t_param::outlets, and param_send_feedback().
Referenced by param_attr_settype().
void param_ramp_callback_float (void * v, float value)
void param_ramp_callback_int (void * v, float value)
void param_ramp_callback_list (void * v, short argc, double * value)
Definition at line 1213 of file jcom.parameter.cpp.
References t_param::atom_list, and param_output_list().
Referenced by param_ramp_setup().
void param_ramp_setup (t_param * x)
Definition at line 1226 of file jcom.parameter.cpp.
References t_param::attr_ramp, t_jcom_core_subscriber_extended::attr_type, t_param::common, RampLib::createUnit(), param_ramp_callback_float(), param_ramp_callback_int(), param_ramp_callback_list(), ps_msg_generic, ps_msg_int, ps_msg_list, ps_msg_none, ps_msg_symbol, ps_msg_toggle, and t_param::ramper.
Referenced by param_new().
void param_rampUpdate (t_param * x)
If the hub receives a bang, it's passed on to this method, and used to update value if @/ramp/drive is set to "async".
Definition at line 900 of file jcom.parameter.cpp.
References t_param::ramper, and RampUnit::tick().
Referenced by main().
void param_reset (t_param * x)
Definition at line 269 of file jcom.parameter.cpp.
References t_param::atom_list, t_param::atom_listDefault, t_param::list_size, and t_param::listDefault_size.
Referenced by main(), and param_new().
void param_send_feedback (t_param * x)
Definition at line 980 of file jcom.parameter.cpp.
References t_param::atom_list, t_param::attr_ui_freeze, t_param::callback, t_param::callbackArg, t_param::common, t_jcom_core_subscriber_extended::hub, jcom_core_atom_copy(), t_param::list_size, LISTSIZE, t_param::name, t_param::name_atom, ps_feedback, and t_param::ui_qelem.
Referenced by param_output_float(), param_output_generic(), param_output_int(), param_output_list(), and param_output_symbol().
void param_setcallback (t_param * x, method newCallback, t_object * callbackArg)
Definition at line 278 of file jcom.parameter.cpp.
References t_param::callback, and t_param::callbackArg.
Referenced by main().
void param_setRampDriveParameter (t_param * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 546 of file jcom.parameter.cpp.
References t_param::ramper.
Referenced by main().
void param_setRampFunctionParameter (t_param * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 485 of file jcom.parameter.cpp.
References t_param::ramper, and RampUnit::setFunctionParameterValue().
Referenced by main().
t_max_err param_setvalueof (t_param * x, long argc, t_atom * argv)
Definition at line 229 of file jcom.parameter.cpp.
References t_param::atom_list, t_param::list_size, and t_param::param_output.
void param_symbol (t_param * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 953 of file jcom.parameter.cpp.
References t_jcom_core_subscriber_extended::attr_repetitions, t_param::attr_slavemode, t_jcom_core_subscriber_extended::attr_type, t_param::common, jcom_core_atom_compare(), k_outlet_direct, t_param::list_size, t_param::outlets, and t_param::param_output.
Referenced by main().
void param_ui_queuefn (t_param * x)
Definition at line 1010 of file jcom.parameter.cpp.
References k_outlet_set, t_param::list_size, and t_param::outlets.
Referenced by param_new().
void param_ui_refresh (t_param * x)
Definition at line 972 of file jcom.parameter.cpp.
References t_param::attr_slavemode, k_outlet_set, t_param::list_size, and t_param::outlets.
Referenced by main().