Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.xyz2aed/jcom.xyz2aed.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.xyz2aed/jcom.xyz2aed.cpp File Reference
#include "Jamoma.h"
Classes
struct t_xyz2aed
Functions
void * xyz2aed_new (void)
void xyz2aed_bang (t_xyz2aed *x)
void xyz2aed_assist (t_xyz2aed *x, void *b, long m, long a, char *s)
void xyz2aed_list (t_xyz2aed *x, Symbol *msg, long argc, t_atom *argv)
int main (void)
Variables
double deg2rad
double rad2deg
t_class * this_class
Function Documentation
int main (void)
Definition at line 45 of file jcom.xyz2aed.cpp.
References deg2rad, jamoma_init(), rad2deg, this_class, xyz2aed_assist(), xyz2aed_bang(), xyz2aed_list(), and xyz2aed_new().
void xyz2aed_assist (t_xyz2aed * x, void * b, long m, long a, char * s)
Definition at line 98 of file jcom.xyz2aed.cpp.
Referenced by main().
void xyz2aed_bang (t_xyz2aed * x)
Definition at line 136 of file jcom.xyz2aed.cpp.
References t_xyz2aed::outlet, and t_xyz2aed::outlist.
Referenced by main(), and xyz2aed_list().
void xyz2aed_list (t_xyz2aed * x, Symbol * msg, long argc, t_atom * argv)
Definition at line 114 of file jcom.xyz2aed.cpp.
References t_xyz2aed::outlist, rad2deg, and xyz2aed_bang().
Referenced by main().
void * xyz2aed_new (void)
Definition at line 76 of file jcom.xyz2aed.cpp.
References this_class.
Referenced by main().
Variable Documentation
double deg2rad
Definition at line 18 of file jcom.xyz2aed.cpp.
double rad2deg
Definition at line 19 of file jcom.xyz2aed.cpp.
t_class* this_class
Definition at line 32 of file jcom.xyz2aed.cpp.