Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.envexp/jcom.envexp.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.envexp/jcom.envexp.cpp File Reference
#include "Jamoma.h"
Classes
struct t_envExp
Defines
#define NUM_OF_POINTS 128
maximum number of points that line~ accepts
Functions
void * envExp_new (Symbol *s, short argc, t_atom *argv)
Creates new instance.
void envExp_bang (t_envExp *x)
Trigger new amplitude envelope using currenlty stored values.
void envExp_float (t_envExp *x, double f)
Set peak amplitude attribute and trigger output.
void envExp_assist (t_envExp *x, void *b, long msg, long arg, char *dst)
Provides assistance cues.
void envExp_setattack (t_envExp *x, void *attr, long argc, t_atom *argv)
Set attack time in ms.
void envExp_setamplitude (t_envExp *x, void *attr, long argc, t_atom *argv)
Sets the peak amplitude.
void envExp_setdecayrate (t_envExp *x, void *attr, long argc, t_atom *argv)
Sets the decay rate attribute.
void envExp_setthreshold (t_envExp *x, void *attr, long argc, t_atom *argv)
Sets the threshold attribute.
void envExp_steal (t_envExp *x, long var)
Sets the note stealing attribute.
void envExp_calculate (t_envExp *x)
Calculates array of envelope points.
int main (void)
Class Definition.
Variables
t_class * this_class
Required. Global pointing to this class.
t_symbol * ps_symbol
t_symbol * ps_long
t_symbol * ps_float32
t_symbol * ps_dumpout
Define Documentation
#define NUM_OF_POINTS 128
maximum number of points that line~ accepts
Definition at line 60 of file jcom.envexp.cpp.
Referenced by envExp_bang(), and envExp_calculate().
Function Documentation
void envExp_assist (t_envExp * x, void * b, long msg, long arg, char * dst)
Provides assistance cues.
Returns:
pointer to assistance cue
Definition at line 299 of file jcom.envexp.cpp.
Referenced by main().
void envExp_bang (t_envExp * x)
Trigger new amplitude envelope using currenlty stored values.
Returns:
array of data points for envelope
Definition at line 222 of file jcom.envexp.cpp.
References t_envExp::attr_steal, t_envExp::envelope, NUM_OF_POINTS, and t_envExp::outlet.
Referenced by envExp_float(), and main().
void envExp_calculate (t_envExp * x)
Calculates array of envelope points.
Definition at line 321 of file jcom.envexp.cpp.
References t_envExp::attr_amplitude, t_envExp::attr_attack, t_envExp::attr_decayrate, t_envExp::attr_threshold, t_envExp::envelope, and NUM_OF_POINTS.
Referenced by envExp_float(), envExp_new(), envExp_setamplitude(), envExp_setattack(), envExp_setdecayrate(), and envExp_setthreshold().
void envExp_float (t_envExp * x, double f)
Set peak amplitude attribute and trigger output.
Returns:
array of data points for envelope
Definition at line 231 of file jcom.envexp.cpp.
References t_envExp::attr_amplitude, envExp_bang(), and envExp_calculate().
Referenced by main().
void * envExp_new (Symbol * s, short argc, t_atom * argv)
Creates new instance.
Definition at line 191 of file jcom.envexp.cpp.
References envExp_calculate(), ps_dumpout, and this_class.
Referenced by main().
void envExp_setamplitude (t_envExp * x, void * attr, long argc, t_atom * argv)
Sets the peak amplitude.
Definition at line 255 of file jcom.envexp.cpp.
References t_envExp::attr_amplitude, and envExp_calculate().
Referenced by main().
void envExp_setattack (t_envExp * x, void * attr, long argc, t_atom * argv)
Set attack time in ms.
Definition at line 240 of file jcom.envexp.cpp.
References t_envExp::attr_attack, and envExp_calculate().
Referenced by main().
void envExp_setdecayrate (t_envExp * x, void * attr, long argc, t_atom * argv)
Sets the decay rate attribute.
Definition at line 266 of file jcom.envexp.cpp.
References t_envExp::attr_decayrate, and envExp_calculate().
Referenced by main().
void envExp_setthreshold (t_envExp * x, void * attr, long argc, t_atom * argv)
Sets the threshold attribute.
Definition at line 283 of file jcom.envexp.cpp.
References t_envExp::attr_threshold, and envExp_calculate().
Referenced by main().
void envExp_steal (t_envExp * x, long var)
Sets the note stealing attribute.
int main (void)
Class Definition.
Definition at line 128 of file jcom.envexp.cpp.
References envExp_assist(), envExp_bang(), envExp_float(), envExp_new(), envExp_setamplitude(), envExp_setattack(), envExp_setdecayrate(), envExp_setthreshold(), jamoma_init(), ps_dumpout, ps_float32, ps_long, ps_symbol, and this_class.
Variable Documentation
t_symbol* ps_dumpout
Definition at line 123 of file jcom.envexp.cpp.
t_symbol* ps_float32
Definition at line 122 of file jcom.envexp.cpp.
Referenced by main().
t_symbol* ps_long
Definition at line 121 of file jcom.envexp.cpp.
Referenced by main().
t_symbol* ps_symbol
Definition at line 120 of file jcom.envexp.cpp.
Referenced by main().
t_class* this_class
Required. Global pointing to this class.
Definition at line 119 of file jcom.envexp.cpp.