Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.presets.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.presets.cpp File Reference
#include "jcom.hub.h"
#include "libxml/xmlreader.h"
#include "libxml/xmlschemas.h"
#include <functional>
Classes
struct _byName
struct _byNum
struct _presetIsLess
A function object for determining if one t_preset object should follow another t_preset.
Defines
#define value value_list[0]
Functions
void hub_preset_copy (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Copies a preset by number or name.
void hub_preset_recall (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Recalls a preset by number or name.
t_preset * find_preset (presetList *presetll, t_symbol *name)
void interpolate_presets (t_hub *x, t_preset *p1, t_preset *p2, float position)
void hub_preset_interpolate (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
void hub_preset_store (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Stores a preset by number or name.
void hub_preset_store_next (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Stores a preset in the next slot by name.
void hub_preset_default (t_hub *x, t_symbol *, long, t_atom *)
Recall the default file and recall the first preset.
void hub_preset_read (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Read an XML preset file.
void hub_preset_doread (t_hub *x, t_symbol *userpath)
This does the actual work for hub_preset_read since the actual act of reading the file is defered to the low priority thread.
int coerceType (const char *s)
void hub_preset_parse (t_hub *x, char *path)
Reads in and parses an XML file of presets.
short hub_preset_validate (t_hub *x, char *xml_path)
Given a path to an XML file it validates that it is a valid XML file.
void hub_presets_clear (t_hub *x, t_symbol *, long, t_atom *)
Clears all presets loaded in memory.
void hub_presets_dump (t_hub *x, t_symbol *, long, t_atom *)
Dump all presets.
void hub_preset_write (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Writes an XML preset file.
void writeList (t_filehandle *fh, long *eof, t_preset_item *item)
void hub_preset_dowrite (t_hub *x, t_symbol *userpath)
This does the actual work for hub_preset_write since the actual act of writing the file is defered to the low priority thread.
void hub_preset_buildmenu (t_hub *x)
Adds presets to the GUI menu.
Variables
_byName presetByName
_byNum presetByNumber
_presetIsLess presetIsLess
Define Documentation
#define value value_list[0]
Definition at line 15 of file jcom.hub.presets.cpp.
Function Documentation
int coerceType (const char * s)
Definition at line 472 of file jcom.hub.presets.cpp.
Referenced by hub_preset_parse().
t_preset* find_preset (presetList * presetll, t_symbol * name)
Definition at line 178 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), and t_preset::name.
Referenced by hub_preset_interpolate().
void hub_preset_buildmenu (t_hub * x)
Adds presets to the GUI menu.
Parameters:
x a pointer to the hub whose preset menu will be updated
Definition at line 958 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_hub::gui_object, t_preset::name, t_hub::preset, ps_dispatched, ps_MENU_REBUILD, ps_NEW_PRESETS, and ps_NEW_PRESETS_START.
Referenced by hub_preset_copy(), hub_preset_doread(), and hub_preset_store().
void hub_preset_copy (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Copies a preset by number or name.
Parameters:
x the hub containing the preset
msg
argc the argument count for argv
argv the number or name of the preset to recall
See also:
hub_preset_store
Definition at line 35 of file jcom.hub.presets.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::end(), hub_preset_buildmenu(), t_preset::item, jcomList< T >::merge(), t_preset::name, t_preset::number, t_hub::preset, presetIsLess, and jcomList< T >::size().
Referenced by hub_internals_create(), and hub_private().
void hub_preset_default (t_hub * x, t_symbol * , long , t_atom *)
Recall the default file and recall the first preset.
Parameters:
x the hub whose default preset should be recalled
Definition at line 413 of file jcom.hub.presets.cpp.
References t_hub::attr_name, hub_preset_doread(), and hub_preset_recall().
Referenced by hub_init(), hub_internals_create(), and hub_private().
void hub_preset_doread (t_hub * x, t_symbol * userpath)
This does the actual work for hub_preset_read since the actual act of reading the file is defered to the low priority thread.
See also:
hub_preset_read
Definition at line 444 of file jcom.hub.presets.cpp.
References t_hub::attr_name, hub_preset_buildmenu(), hub_preset_parse(), and jcom_core_getfilepath().
Referenced by hub_preset_default(), and hub_preset_read().
void hub_preset_dowrite (t_hub * x, t_symbol * userpath)
This does the actual work for hub_preset_write since the actual act of writing the file is defered to the low priority thread.
See also:
hub_preset_write
Definition at line 861 of file jcom.hub.presets.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::end(), t_preset::item, jcom_core_file_writeline(), t_preset_item::list_size, t_preset::name, t_preset::number, t_preset_item::param_name, t_hub::preset, t_preset_item::priority, t_preset_item::type, and writeList().
Referenced by hub_preset_write().
void hub_preset_interpolate (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 256 of file jcom.hub.presets.cpp.
References t_hub::attr_name, find_preset(), interpolate_presets(), and t_hub::preset.
Referenced by hub_internals_create().
void hub_preset_parse (t_hub * x, char * path)
Reads in and parses an XML file of presets.
Parameters:
x the hub to which the loaded presets should be attached
path the path the XML file to read
Definition at line 497 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), coerceType(), hub_preset_validate(), hub_presets_clear(), t_preset::item, t_preset_item::list_size, jcomList< T >::merge(), t_preset::name, t_preset::number, t_preset_item::param_name, t_hub::preset, presetIsLess, t_preset_item::priority, ps_msg_generic, ps_msg_int, ps_msg_symbol, ps_msg_toggle, jcomList< T >::push_back(), t_preset_item::type, and t_preset_item::value_list.
Referenced by hub_preset_doread().
void hub_preset_read (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Read an XML preset file.
Parameters:
x the hub to the preset file should be loaded for
userpath path to the XML file to load
See also:
hub_preset_doread hub_preset_write hub_preset_dowrite
Definition at line 431 of file jcom.hub.presets.cpp.
References hub_preset_doread().
Referenced by hub_internals_create(), and hub_private().
void hub_preset_recall (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Recalls a preset by number or name.
Parameters:
x the hub containing the preset
msg
argc the argument count for argv
argv the number or name of the preset to recall
See also:
hub_preset_store
Definition at line 89 of file jcom.hub.presets.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::end(), hub_symbol(), t_preset_item::list_size, t_preset_item::param_name, t_hub::preset, t_preset_item::priority, and t_preset_item::value_list.
Referenced by hub_internals_create(), hub_preset_default(), and hub_private().
void hub_preset_store (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Stores a preset by number or name.
Parameters:
x the hub containing the preset
msg
argc the argument count for argv
argv the number of the preset with an optional name
See also:
hub_preset_recall
Definition at line 287 of file jcom.hub.presets.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::empty(), jcomList< T >::end(), jcomList< T >::erase(), hub_preset_buildmenu(), t_preset::item, t_preset_item::list_size, jcomList< T >::merge(), t_subscriber::name, t_preset::name, t_preset::number, t_subscriber::object, t_preset_item::param_name, t_hub::preset, presetIsLess, t_preset_item::priority, ps_priority, ps_subscribe_parameter, ps_type, ps_value, jcomList< T >::push_back(), jcomList< T >::size(), t_hub::subscriber, t_preset_item::type, t_subscriber::type, and t_preset_item::value_list.
Referenced by hub_internals_create(), hub_preset_store_next(), hub_preset_write(), and hub_private().
void hub_preset_store_next (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Stores a preset in the next slot by name.
Parameters:
x the hub containing the preset
msg
argc the argument count for argv
argv the number of the preset with an optional name
See also:
hub_preset_recall
Definition at line 404 of file jcom.hub.presets.cpp.
References hub_preset_store(), t_hub::preset, and jcomList< T >::size().
Referenced by hub_internals_create(), and hub_private().
short hub_preset_validate (t_hub * x, char * xml_path)
Given a path to an XML file it validates that it is a valid XML file.
Parameters:
x the hub for which the XML preset file should be validated for
xml_path the path to the XML file
Returns:
0 if succesfully validated, non-zero otherwise
Definition at line 657 of file jcom.hub.presets.cpp.
References t_hub::attr_name, and jcom_core_getfilepath().
Referenced by hub_preset_parse().
void hub_preset_write (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Writes an XML preset file.
Parameters:
x the hub whose presets should be written to disk
userpath path to the XML file to write
See also:
hub_preset_dowrite hub_preset_read hub_preset_doread
Definition at line 793 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::empty(), hub_preset_dowrite(), hub_preset_store(), t_hub::preset, and ps_default.
Referenced by hub_internals_create(), and hub_private().
void hub_presets_clear (t_hub * x, t_symbol * , long , t_atom *)
Clears all presets loaded in memory.
Parameters:
x the hub whose presets should be cleared
Definition at line 727 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::empty(), t_preset::item, t_hub::preset, and jcomList< T >::remove().
Referenced by hub_free(), hub_internals_create(), and hub_preset_parse().
void hub_presets_dump (t_hub * x, t_symbol * , long , t_atom *)
Dump all presets.
Parameters:
x a pointer to the hub whose presets should be dumped
Definition at line 757 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_preset::item, t_preset::name, t_preset::number, t_preset_item::param_name, t_hub::preset, t_preset_item::priority, ps_msg_int, ps_msg_symbol, ps_msg_toggle, and t_preset_item::type.
Referenced by hub_internals_create().
void interpolate_presets (t_hub * x, t_preset * p1, t_preset * p2, float position)
Definition at line 194 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_symbol(), t_preset::item, t_preset_item::list_size, LISTSIZE, t_preset_item::param_name, ps_msg_float, ps_msg_int, ps_msg_list, ps_msg_symbol, ps_msg_toggle, t_preset_item::type, value, and t_preset_item::value_list.
Referenced by hub_preset_interpolate().
void writeList (t_filehandle * fh, long * eof, t_preset_item * item)
Definition at line 822 of file jcom.hub.presets.cpp.
References t_preset_item::list_size, t_preset_item::param_name, t_preset_item::priority, t_preset_item::type, and t_preset_item::value_list.
Referenced by hub_preset_dowrite().
Variable Documentation
_byName presetByName
_byNum presetByNumber
_presetIsLess presetIsLess
Referenced by hub_preset_copy(), hub_preset_parse(), and hub_preset_store().