Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/Internals/jcom.receivemaster.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/Internals/jcom.receivemaster.cpp File Reference
#include "Jamoma.h"
Functions
void * receivemaster_new (t_symbol *msg, long argc, t_atom *argv)
void receivemaster_free (t_jcom_receivemaster *x)
void receivemaster_dispatch (t_jcom_receivemaster *x, t_symbol *name, t_symbol *msg, long argc, t_atom *argv)
void receivemaster_add (t_jcom_receivemaster *x, t_symbol *name, t_object *obj)
void receivemaster_remove (t_jcom_receivemaster *x, t_symbol *name, t_object *obj)
void receivemaster_initclass ()
long linklist_match (void *a, void *b)
void linklist_chuckobject (t_linklist *x, void *o)
Variables
static t_class * s_receivemaster_class = NULL
Required: Global pointer the jcom.receivemaster class.
static t_hashtab * s_receive_lists = NULL
hash full of linked lists, keyed on the name of the jcom.receive instances
Function Documentation
void linklist_chuckobject (t_linklist * x, void * o)
Definition at line 100 of file jcom.receivemaster.cpp.
References linklist_match().
Referenced by receivemaster_remove().
long linklist_match (void * a, void * b)
Definition at line 95 of file jcom.receivemaster.cpp.
Referenced by linklist_chuckobject().
void receivemaster_add (t_jcom_receivemaster * x, t_symbol * name, t_object * obj)
Definition at line 80 of file jcom.receivemaster.cpp.
References s_receive_lists.
Referenced by receivemaster_initclass().
void receivemaster_dispatch (t_jcom_receivemaster * x, t_symbol * name, t_symbol * msg, long argc, t_atom * argv)
Definition at line 71 of file jcom.receivemaster.cpp.
References ps_dispatch, and s_receive_lists.
Referenced by receivemaster_initclass().
void receivemaster_free (t_jcom_receivemaster * x)
Definition at line 61 of file jcom.receivemaster.cpp.
Referenced by receivemaster_initclass().
void receivemaster_initclass ()
Definition at line 28 of file jcom.receivemaster.cpp.
References receivemaster_add(), receivemaster_dispatch(), receivemaster_free(), receivemaster_new(), receivemaster_remove(), and s_receivemaster_class.
Referenced by jamoma_init().
void * receivemaster_new (t_symbol * msg, long argc, t_atom * argv)
Definition at line 52 of file jcom.receivemaster.cpp.
References s_receive_lists, and s_receivemaster_class.
Referenced by receivemaster_initclass().
void receivemaster_remove (t_jcom_receivemaster * x, t_symbol * name, t_object * obj)
Definition at line 111 of file jcom.receivemaster.cpp.
References linklist_chuckobject(), and s_receive_lists.
Referenced by receivemaster_initclass().
Variable Documentation
t_hashtab* s_receive_lists = NULL [static]
hash full of linked lists, keyed on the name of the jcom.receive instances
Definition at line 23 of file jcom.receivemaster.cpp.
Referenced by receivemaster_add(), receivemaster_dispatch(), receivemaster_new(), and receivemaster_remove().
t_class* s_receivemaster_class = NULL [static]
Required: Global pointer the jcom.receivemaster class.
Definition at line 22 of file jcom.receivemaster.cpp.
Referenced by receivemaster_initclass(), and receivemaster_new().