Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.equals/jcom.equals.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.equals/jcom.equals.cpp File Reference
#include "ext.h"
Classes
struct t_symbEqual
Functions
void symbEqual_anything (t_symbEqual *x, Symbol *s, short ac, Atom *av)
void symbEqual_assist (t_symbEqual *x, void *b, long msg, long arg, char *dst)
void * symbEqual_new (Symbol *s)
void symbEqual_free (t_symbEqual *x)
int main (void)
Variables
void * symbEqual_class
Function Documentation
int main (void)
Definition at line 35 of file jcom.equals.cpp.
References symbEqual_anything(), symbEqual_assist(), symbEqual_class, symbEqual_free(), and symbEqual_new().
void symbEqual_anything (t_symbEqual * x, Symbol * s, short ac, Atom * av)
Definition at line 80 of file jcom.equals.cpp.
Referenced by main().
void symbEqual_assist (t_symbEqual * x, void * b, long msg, long arg, char * dst)
Definition at line 66 of file jcom.equals.cpp.
Referenced by main().
void symbEqual_free (t_symbEqual * x)
Definition at line 56 of file jcom.equals.cpp.
References t_symbEqual::proxy.
Referenced by main().
void * symbEqual_new (Symbol * s)
Definition at line 47 of file jcom.equals.cpp.
References t_symbEqual::out, t_symbEqual::proxy, t_symbEqual::rightSymbol, and symbEqual_class.
Referenced by main().
Variable Documentation
void* symbEqual_class
Definition at line 29 of file jcom.equals.cpp.
Referenced by main(), and symbEqual_new().