Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.teabox.count~/jcom.teabox.count~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.teabox.count~/jcom.teabox.count~.cpp File Reference
#include "ext.h"
#include "ext_strings.h"
#include "z_dsp.h"
Classes
struct t_count_tilde
Functions
void count_tilde_dsp (t_count_tilde *x, t_signal **sp, short *count)
void count_tilde_assist (t_count_tilde *x, void *b, long m, long a, char *s)
void * count_tilde_new (t_symbol *s, long argc, t_atom *argv)
t_int * count_tilde_perform (t_int *w)
void count_tilde_free (t_count_tilde *x)
void count_tilde_activate (t_count_tilde *x, short toggle)
int main (void)
Variables
t_class * count_tilde_class
Function Documentation
void count_tilde_activate (t_count_tilde * x, short toggle)
void count_tilde_assist (t_count_tilde * x, void * b, long m, long a, char * s)
Definition at line 80 of file jcom.teabox.count~.cpp.
Referenced by main().
void count_tilde_dsp (t_count_tilde * x, t_signal ** sp, short * count)
Definition at line 115 of file jcom.teabox.count~.cpp.
References count_tilde_perform().
Referenced by main().
void count_tilde_free (t_count_tilde * x)
void * count_tilde_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 66 of file jcom.teabox.count~.cpp.
References count_tilde_class.
Referenced by main().
t_int * count_tilde_perform (t_int * w)
Definition at line 88 of file jcom.teabox.count~.cpp.
References t_count_tilde::ob, t_count_tilde::value, and value.
Referenced by count_tilde_dsp().
int main (void)
Definition at line 51 of file jcom.teabox.count~.cpp.
References count_tilde_assist(), count_tilde_class, count_tilde_dsp(), and count_tilde_new().
Variable Documentation
t_class* count_tilde_class
Definition at line 29 of file jcom.teabox.count~.cpp.
Referenced by count_tilde_new(), and main().