Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.internals.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.internals.cpp File Reference
#include "jcom.hub.h"
Classes
class hubInternalObject
Functions
void hub_internals_create (t_hub *x)
Create parameters, messages, and other internal subscribers to the hub.
void hub_internals_destroy (t_hub *x)
Destroy (free) parameters, messages, etc.
void hub_internals_dispatch (t_hub *x, t_symbol *osc_name, long argc, t_atom *argv)
Send a message to the appropriate internal parameter or message.
Function Documentation
void hub_internals_create (t_hub * x)
Create parameters, messages, and other internal subscribers to the hub.
Parameters:
x the hub
See also:
hub_internals_destroy
Definition at line 42 of file jcom.hub.internals.cpp.
References hubInternalObject::action, t_hub::hash_internals, hub_autodoc(), hub_init(), hub_module_view_alg(), hub_preset_copy(), hub_preset_default(), hub_preset_interpolate(), hub_preset_read(), hub_preset_recall(), hub_preset_store(), hub_preset_store_next(), hub_preset_write(), hub_presets_clear(), hub_presets_dump(), hub_ui_freeze(), and hub_ui_refresh().
Referenced by hub_new().
void hub_internals_destroy (t_hub * x)
Destroy (free) parameters, messages, etc.
that are internal to hub.
Parameters:
x the hub
See also:
hub_internals_create
Definition at line 110 of file jcom.hub.internals.cpp.
References t_hub::hash_internals.
Referenced by hub_free().
void hub_internals_dispatch (t_hub * x, t_symbol * osc_name, long argc, t_atom * argv)
Send a message to the appropriate internal parameter or message.
Parameters:
x the hub
osc_name the osc name of the parameter or message
argc the number of values to send to the parameter or message
argv the actual values to send to the parameter or message
Definition at line 132 of file jcom.hub.internals.cpp.
References t_hub::hash_internals.
Referenced by hub_receive().