Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.init/jcom.init.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.init/jcom.init.cpp File Reference
#include "Jamoma.h"
Classes
struct t_init
Functions
void * init_new (t_symbol *s, long argc, t_atom *argv)
void init_assist (t_init *x, void *b, long m, long a, char *s)
void init_go (t_init *x)
void init_bang (t_init *x)
int main (void)
Variables
t_class * g_init_class
Function Documentation
void init_assist (t_init * x, void * b, long m, long a, char * s)
Definition at line 95 of file jcom.init.cpp.
Referenced by main().
void init_bang (t_init * x)
Definition at line 114 of file jcom.init.cpp.
References t_init::common, t_jcom_core_subscriber_common::hub, and ps_init.
Referenced by main().
void init_go (t_init * x)
Definition at line 108 of file jcom.init.cpp.
References t_init::outlet.
Referenced by main().
void * init_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 66 of file jcom.init.cpp.
References t_init::dumpout, g_init_class, jcom_core_subscriber_new_common(), jcom_core_subscriber_subscribe(), t_init::outlet, ps_dumpout, and ps_subscribe_init.
Referenced by main().
int main (void)
Definition at line 33 of file jcom.init.cpp.
References g_init_class, init_assist(), init_bang(), init_go(), init_new(), jamoma_init(), jcom_core_subscriber_classinit_common(), and jcom_core_subscriber_common_free().
Variable Documentation
t_class* g_init_class
Definition at line 27 of file jcom.init.cpp.
Referenced by init_new(), and main().