Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.in/jcom.in.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.in/jcom.in.cpp File Reference
#include "Jamoma.h"
#include "jcom.in.h"
Functions
int main (void)
void * in_new (t_symbol *s, long argc, t_atom *argv)
jcom.in constructor
void in_subscribe (void *z)
Method for subscribing to jcom.hub.
void in_free (t_in *x)
jcom.in deconstructor
void in_release (t_in *x)
Unsubscribe from jcom.hub.
void in_assist (t_in *x, void *b, long msg, long arg, char *dst)
void in_algorithm_message (t_in *x, t_symbol *msg, long argc, t_atom *argv)
void in_view_internals (t_in *x, t_symbol *msg, long argc, t_atom *argv)
void in_dispatched (t_in *x, t_symbol *msg, long argc, t_atom *argv)
Dispatch method for communication with the hub.
void in_link (t_in *x, t_object *y)
void in_unlink (t_in *x)
void in_bang (t_in *x)
void in_int (t_in *x, long value)
int handler for jcom.in
void in_float (t_in *x, double value)
float handler for jcom.in
void in_anything (t_in *x, t_symbol *msg, long argc, t_atom *argv)
t_int * in_perform (t_int *w)
jcom.in~ MSP perform method
void in_remoteaudio (t_in *x, float *audioVectors[], long numAudioVectors)
void in_dsp (t_in *x, t_signal **sp, short *count)
jcom.in~ DSP method
void in_alloc (t_in *x, int vector_size)
Variables
t_class * in_class
t_atom ga_zero
Function Documentation
void in_algorithm_message (t_in * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 234 of file jcom.in.cpp.
References t_in::algout, t_in::attr_bypass, t_in::attr_freeze, t_in::attr_mute, ps_audio_mute, ps_mute, ps_slash_audio_mute, ps_slash_video_bypass, ps_slash_video_freeze, ps_slash_video_mute, ps_video_bypass, ps_video_freeze, and ps_video_mute.
Referenced by main().
void in_alloc (t_in * x, int vector_size)
Definition at line 422 of file jcom.in.cpp.
References MAX_NUM_CHANNELS, t_in::remote_vectors, t_in::signal_in, and t_in::vector_size.
Referenced by in_dsp(), and in_new().
void in_anything (t_in * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 329 of file jcom.in.cpp.
References t_in::attr_bypass, t_in::attr_freeze, t_in::attr_mute, t_in::out_object, ps_sendbypassedvalue, and ps_sendlastvalue.
Referenced by main().
void in_assist (t_in * x, void * b, long msg, long arg, char * dst)
Definition at line 218 of file jcom.in.cpp.
References t_in::num_inputs.
Referenced by main().
void in_bang (t_in * x)
Definition at line 284 of file jcom.in.cpp.
References t_in::attr_bypass, t_in::attr_freeze, t_in::attr_mute, t_in::out_object, ps_sendbypassedvalue, and ps_sendlastvalue.
Referenced by main().
void in_dispatched (t_in * x, t_symbol * msg, long argc, t_atom * argv)
Dispatch method for communication with the hub.
Definition at line 265 of file jcom.in.cpp.
Referenced by main().
void in_dsp (t_in * x, t_signal ** sp, short * count)
jcom.in~ DSP method
Definition at line 398 of file jcom.in.cpp.
References in_alloc(), in_perform(), t_in::num_inputs, t_in::out_vectors, and t_in::signal_in.
Referenced by main().
void in_float (t_in * x, double value)
float handler for jcom.in
Definition at line 313 of file jcom.in.cpp.
References t_in::attr_bypass, t_in::attr_freeze, t_in::attr_mute, t_in::out_object, t_in::outlet, ps_sendbypassedvalue, and ps_sendlastvalue.
Referenced by main().
void in_free (t_in * x)
jcom.in deconstructor
Definition at line 196 of file jcom.in.cpp.
References jcom_core_subscriber_common_free().
Referenced by main().
void in_int (t_in * x, long value)
int handler for jcom.in
Definition at line 297 of file jcom.in.cpp.
References t_in::attr_bypass, t_in::attr_freeze, t_in::attr_mute, t_in::out_object, t_in::outlet, ps_sendbypassedvalue, and ps_sendlastvalue.
Referenced by main().
void in_link (t_in * x, t_object * y)
Definition at line 272 of file jcom.in.cpp.
References t_in::out_object.
Referenced by main().
void* in_new (t_symbol * s, long argc, t_atom * argv)
jcom.in constructor
Definition at line 106 of file jcom.in.cpp.
References t_in::algout, t_in::dumpout, in_alloc(), in_class, in_subscribe(), jcom_core_subscriber_new_common(), jcom_core_subscriber_setcustomsubscribe_method(), jcom_core_subscriber_subscribe(), MAX_NUM_CHANNELS, ps__jcom_in__, ps_dumpout, and ps_subscribe_in.
Referenced by main().
t_int* in_perform (t_int * w)
jcom.in~ MSP perform method
Definition at line 344 of file jcom.in.cpp.
References t_in::num_inputs, t_in::out_vectors, t_in::remote_vectors, t_in::signal_in, and t_in::vector_size.
Referenced by in_dsp().
void in_release (t_in * x)
Unsubscribe from jcom.hub.
Definition at line 207 of file jcom.in.cpp.
References t_in::common, jcom_core_subscriber_hubrelease(), and t_in::out_object.
Referenced by main().
void in_remoteaudio (t_in * x, float * audioVectors[], long numAudioVectors)
Definition at line 381 of file jcom.in.cpp.
References t_in::remote_vectors, and t_in::vector_size.
Referenced by main().
void in_subscribe (void * z)
Method for subscribing to jcom.hub.
Definition at line 165 of file jcom.in.cpp.
References t_in::attr_algorithm_type, t_in::common, t_jcom_core_subscriber_common::hub, ps_algorithm_type, ps_audio, ps_control, ps_default, ps_jitter, ps_module_type, ps_poly, and ps_video.
Referenced by in_new().
void in_unlink (t_in * x)
Definition at line 278 of file jcom.in.cpp.
References t_in::out_object.
Referenced by main().
void in_view_internals (t_in * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 258 of file jcom.in.cpp.
References t_in::algout, and ps_open.
Referenced by main().
int main (void)
Definition at line 33 of file jcom.in.cpp.
References ga_zero, in_algorithm_message(), in_anything(), in_assist(), in_bang(), in_class, in_dispatched(), in_dsp(), in_float(), in_free(), in_int(), in_link(), in_new(), in_release(), in_remoteaudio(), in_unlink(), in_view_internals(), jamoma_init(), and jcom_core_subscriber_classinit_common().
Variable Documentation
t_atom ga_zero
Definition at line 27 of file jcom.in.cpp.
Referenced by main().
t_class* in_class
Definition at line 26 of file jcom.in.cpp.
Referenced by in_new(), and main().