Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.send~/jcom.send~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.send~/jcom.send~.cpp File Reference
#include "Jamoma.h"
Classes
struct t_audiosend
Functions
void * audiosend_new (t_symbol *s, long argc, t_atom *argv)
void audiosend_free (t_audiosend *x)
void audiosend_assist (t_audiosend *x, void *b, long msg, long arg, char *dst)
void audiosend_bang (t_audiosend *x)
t_int * audiosend_perform (t_int *w)
void audiosend_dsp (t_audiosend *x, t_signal **sp, short *count)
t_max_err audiosend_attr_settarget (t_audiosend *x, void *attr, long argc, t_atom *argv)
int main (void)
Variables
static t_class * s_audiosend_class
Function Documentation
void audiosend_assist (t_audiosend * x, void * b, long msg, long arg, char * dst)
Definition at line 139 of file jcom.send~.cpp.
Referenced by main().
t_max_err audiosend_attr_settarget (t_audiosend * x, void * attr, long argc, t_atom * argv)
Definition at line 211 of file jcom.send~.cpp.
References t_audiosend::attr_target, jamoma_get_hub_for_module_named(), t_audiosend::obj_direct_target, and t_audiosend::obj_target.
Referenced by main().
void audiosend_bang (t_audiosend * x)
Definition at line 148 of file jcom.send~.cpp.
References t_audiosend::dumpout, and jamoma_get_all_module_names().
Referenced by main().
void audiosend_dsp (t_audiosend * x, t_signal ** sp, short * count)
Definition at line 179 of file jcom.send~.cpp.
References t_audiosend::attr_target, t_audiosend::audio_in, audiosend_perform(), jamoma_get_hub_for_module_named(), t_audiosend::num_inputs, t_audiosend::obj_direct_target, and t_audiosend::obj_target.
Referenced by main().
void audiosend_free (t_audiosend * x)
Definition at line 129 of file jcom.send~.cpp.
Referenced by main().
void * audiosend_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 101 of file jcom.send~.cpp.
References t_audiosend::attr_target, t_audiosend::dumpout, t_audiosend::num_inputs, and s_audiosend_class.
Referenced by main().
t_int * audiosend_perform (t_int * w)
Definition at line 170 of file jcom.send~.cpp.
References t_audiosend::audio_in, and t_audiosend::obj_direct_target.
Referenced by audiosend_dsp().
int main (void)
Definition at line 59 of file jcom.send~.cpp.
References audiosend_assist(), audiosend_attr_settarget(), audiosend_bang(), audiosend_dsp(), audiosend_free(), audiosend_new(), jamoma_init(), and s_audiosend_class.
Variable Documentation
t_class* s_audiosend_class [static]
Definition at line 54 of file jcom.send~.cpp.
Referenced by audiosend_new(), and main().