Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.saturation~/jcom.saturation~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.saturation~/jcom.saturation~.cpp File Reference
#include "Jamoma.h"
Classes
struct t_saturation
Defines
#define NUM_INPUTS 2
#define NUM_OUTPUTS 2
Functions
void * saturation_new (t_symbol *s, long argc, t_atom *argv)
t_int * saturation_perform (t_int *w)
t_int * saturation_perform2 (t_int *w)
void saturation_dsp (t_saturation *x, t_signal **sp, short *count)
void saturation_assist (t_saturation *x, void *b, long msg, long arg, char *dst)
t_max_err saturation_setsaturation (t_saturation *x, void *attr, long argc, t_atom *argv)
t_max_err saturation_setbypass_dcblocker (t_saturation *x, void *attr, long argc, t_atom *argv)
t_max_err saturation_setbypass_overdrive (t_saturation *x, void *attr, long argc, t_atom *argv)
t_max_err saturation_setmode (t_saturation *x, void *attr, long argc, t_atom *argv)
t_max_err saturation_setpreamp (t_saturation *x, void *attr, long argc, t_atom *argv)
t_max_err saturation_setmute (t_saturation *x, void *attr, long argc, t_atom *argv)
void saturation_anything (t_saturation *x, t_symbol *msg, long argc, t_atom *argv)
void set_bypass (t_saturation *x)
void saturation_clear (t_saturation *x)
void saturation_free (t_saturation *x)
int main (void)
Variables
t_class * saturation_class
t_symbol * ps_symbol
t_symbol * ps_long
t_symbol * ps_float32
t_symbol * ps_dumpout
Define Documentation
#define NUM_INPUTS 2
Definition at line 12 of file jcom.saturation~.cpp.
#define NUM_OUTPUTS 2
Definition at line 13 of file jcom.saturation~.cpp.
Function Documentation
int main (void)
Definition at line 58 of file jcom.saturation~.cpp.
References jamoma_init(), ps_dumpout, ps_float32, ps_long, ps_symbol, saturation_anything(), saturation_assist(), saturation_class, saturation_clear(), saturation_dsp(), saturation_free(), saturation_new(), saturation_setbypass_dcblocker(), saturation_setmode(), saturation_setmute(), saturation_setpreamp(), and saturation_setsaturation().
void saturation_anything (t_saturation * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 254 of file jcom.saturation~.cpp.
Referenced by main().
void saturation_assist (t_saturation * x, void * b, long msg, long arg, char * dst)
Definition at line 182 of file jcom.saturation~.cpp.
Referenced by main().
void saturation_clear (t_saturation * x)
Definition at line 197 of file jcom.saturation~.cpp.
References t_saturation::overdrive.
Referenced by main().
void saturation_dsp (t_saturation * x, t_signal ** sp, short * count)
Definition at line 314 of file jcom.saturation~.cpp.
References t_saturation::overdrive, saturation_perform(), and saturation_perform2().
Referenced by main().
void saturation_free (t_saturation * x)
Definition at line 165 of file jcom.saturation~.cpp.
References NUM_INPUTS, and NUM_OUTPUTS.
Referenced by main().
void * saturation_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 128 of file jcom.saturation~.cpp.
References NUM_INPUTS, NUM_OUTPUTS, ps_dumpout, and saturation_class.
Referenced by main().
t_int * saturation_perform (t_int * w)
Definition at line 272 of file jcom.saturation~.cpp.
References t_saturation::attr_bypass, t_saturation::attr_mute, t_saturation::copy, t_saturation::overdrive, t_saturation::signal_in, t_saturation::signal_out, and t_saturation::x_obj.
Referenced by saturation_dsp().
t_int * saturation_perform2 (t_int * w)
Definition at line 292 of file jcom.saturation~.cpp.
References t_saturation::attr_bypass, t_saturation::attr_mute, t_saturation::copy, t_saturation::overdrive, t_saturation::signal_in, t_saturation::signal_out, and t_saturation::x_obj.
Referenced by saturation_dsp().
t_max_err saturation_setbypass_dcblocker (t_saturation * x, void * attr, long argc, t_atom * argv)
Definition at line 215 of file jcom.saturation~.cpp.
References t_saturation::attr_bypass_dcblocker, and t_saturation::overdrive.
Referenced by main().
t_max_err saturation_setbypass_overdrive (t_saturation * x, void * attr, long argc, t_atom * argv)
t_max_err saturation_setmode (t_saturation * x, void * attr, long argc, t_atom * argv)
Definition at line 233 of file jcom.saturation~.cpp.
References t_saturation::attr_mode, and t_saturation::overdrive.
Referenced by main().
t_max_err saturation_setmute (t_saturation * x, void * attr, long argc, t_atom * argv)
Definition at line 225 of file jcom.saturation~.cpp.
References t_saturation::attr_mute.
Referenced by main().
t_max_err saturation_setpreamp (t_saturation * x, void * attr, long argc, t_atom * argv)
Definition at line 260 of file jcom.saturation~.cpp.
References t_saturation::attr_preamp_db, and t_saturation::overdrive.
Referenced by main().
t_max_err saturation_setsaturation (t_saturation * x, void * attr, long argc, t_atom * argv)
Definition at line 204 of file jcom.saturation~.cpp.
References t_saturation::attr_overdrive, and t_saturation::overdrive.
Referenced by main().
void set_bypass (t_saturation * x)
Variable Documentation
t_symbol* ps_dumpout
Definition at line 53 of file jcom.saturation~.cpp.
t_symbol* ps_float32
Definition at line 52 of file jcom.saturation~.cpp.
t_symbol* ps_long
Definition at line 51 of file jcom.saturation~.cpp.
t_symbol* ps_symbol
Definition at line 50 of file jcom.saturation~.cpp.
t_class* saturation_class
Definition at line 49 of file jcom.saturation~.cpp.
Referenced by main(), and saturation_new().