Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.metro/jcom.metro.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.metro/jcom.metro.cpp File Reference
#include "Jamoma.h"
Classes
struct t_jcom_metro
Functions
void * jcom_metro_new (t_symbol *s, long argc, t_atom *argv)
void jcom_metro_free (t_jcom_metro *x)
void jcom_metro_int (t_jcom_metro *x, long toggle)
void jcom_metro_tick (t_jcom_metro *x)
t_max_err metro_attr_setperiod (t_jcom_metro *x, void *attr, long argc, t_atom *argv)
int main (void)
Variables
static t_class * jcom_metro_class
Function Documentation
void jcom_metro_free (t_jcom_metro * x)
Definition at line 94 of file jcom.metro.cpp.
References t_jcom_metro::event, and jamoma_scheduler_removeevent().
Referenced by main().
void jcom_metro_int (t_jcom_metro * x, long toggle)
Definition at line 104 of file jcom.metro.cpp.
References t_jcom_metro::attr_active, t_jcom_metro::event, jamoma_scheduler_delay(), jamoma_scheduler_removeevent(), JCOM_EVENT_PRIORITY_MEDIUM, and jcom_metro_tick().
Referenced by main().
void * jcom_metro_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 73 of file jcom.metro.cpp.
References jcom_metro_class.
Referenced by main().
void jcom_metro_tick (t_jcom_metro * x)
Definition at line 117 of file jcom.metro.cpp.
References t_jcom_metro::outlet.
Referenced by jcom_metro_int().
int main (void)
Definition at line 36 of file jcom.metro.cpp.
References jamoma_dsp(), jamoma_init(), jcom_metro_class, jcom_metro_free(), jcom_metro_int(), jcom_metro_new(), and metro_attr_setperiod().
t_max_err metro_attr_setperiod (t_jcom_metro * x, void * attr, long argc, t_atom * argv)
Definition at line 123 of file jcom.metro.cpp.
References t_jcom_metro::attr_period.
Referenced by main().
Variable Documentation
t_class* jcom_metro_class [static]
Definition at line 30 of file jcom.metro.cpp.
Referenced by jcom_metro_new(), and main().