Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.oscroute/jcom.oscroute.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.oscroute/jcom.oscroute.cpp File Reference
#include "Jamoma.h"
Classes
struct t_oscroute
Defines
#define MAX_ARGCOUNT 100
#define MAX_MESS_SIZE 2048
Functions
void * oscroute_new (t_symbol *s, long argc, t_atom *argv)
void oscroute_free (t_oscroute *x)
void oscroute_assist (t_oscroute *x, void *b, long msg, long arg, char *dst)
void oscroute_bang (t_oscroute *x)
void oscroute_int (t_oscroute *x, long n)
void oscroute_float (t_oscroute *x, double f)
void oscroute_list (t_oscroute *x, t_symbol *msg, long argc, t_atom *argv)
void oscroute_symbol (t_oscroute *x, t_symbol *msg, long argc, t_atom *argv)
int main (void)
void output_msg (t_oscroute *x, char *msg, int outlet, long argc, t_atom *argv)
Variables
t_class * oscroute_class
Define Documentation
#define MAX_ARGCOUNT 100
Definition at line 12 of file jcom.oscroute.cpp.
#define MAX_MESS_SIZE 2048
Definition at line 13 of file jcom.oscroute.cpp.
Referenced by oscroute_symbol(), and pass_new().
Function Documentation
int main (void)
Definition at line 45 of file jcom.oscroute.cpp.
References jamoma_init(), oscroute_assist(), oscroute_bang(), oscroute_class, oscroute_float(), oscroute_free(), oscroute_int(), oscroute_list(), oscroute_new(), and oscroute_symbol().
void oscroute_assist (t_oscroute * x, void * b, long msg, long arg, char * dst)
Definition at line 132 of file jcom.oscroute.cpp.
References t_oscroute::arguments.
Referenced by main().
void oscroute_bang (t_oscroute * x)
Definition at line 146 of file jcom.oscroute.cpp.
References t_oscroute::outlet_overflow.
Referenced by main().
void oscroute_float (t_oscroute * x, double f)
Definition at line 158 of file jcom.oscroute.cpp.
References t_oscroute::outlet_overflow.
Referenced by main().
void oscroute_free (t_oscroute * x)
Definition at line 120 of file jcom.oscroute.cpp.
References t_oscroute::proxy_inlet.
Referenced by main().
void oscroute_int (t_oscroute * x, long n)
Definition at line 152 of file jcom.oscroute.cpp.
References t_oscroute::outlet_overflow.
Referenced by main().
void oscroute_list (t_oscroute * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 164 of file jcom.oscroute.cpp.
References t_oscroute::outlet_overflow.
Referenced by main().
void * oscroute_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 83 of file jcom.oscroute.cpp.
References t_oscroute::arglen, t_oscroute::arguments, t_oscroute::num_args, oscroute_class, t_oscroute::outlet_overflow, t_oscroute::outlets, and t_oscroute::proxy_inlet.
Referenced by main().
void oscroute_symbol (t_oscroute * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 202 of file jcom.oscroute.cpp.
References MAX_MESS_SIZE, and output_msg().
Referenced by main().
void output_msg (t_oscroute * x, char * msg, int outlet, long argc, t_atom * argv)
Definition at line 169 of file jcom.oscroute.cpp.
References t_oscroute::outlets.
Referenced by oscroute_symbol().
Variable Documentation
t_class* oscroute_class
Definition at line 39 of file jcom.oscroute.cpp.
Referenced by main(), and oscroute_new().