Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.snapshot~/jcom.snapshot~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.snapshot~/jcom.snapshot~.cpp File Reference
#include "Jamoma.h"
Functions
void * send_new (t_symbol *s, long argc, t_atom *argv)
void send_free (t_send *x)
void send_assist (t_send *x, void *b, long msg, long arg, char *dst)
void send_bang (t_send *x)
void send_int (t_send *x, long value)
void send_float (t_send *x, double value)
void send_list (t_send *x, t_symbol *msg, long argc, t_atom *argv)
int main (void)
Variables
static t_class * s_send_class
static t_object * s_receivemaster_object = NULL
Function Documentation
int main (void)
Definition at line 46 of file jcom.snapshot~.cpp.
References jamoma_init(), s_send_class, send_assist(), send_bang(), send_float(), send_int(), send_list(), and send_new().
void send_assist (t_send * x, void * b, long msg, long arg, char * dst)
void send_bang (t_send * x)
void send_float (t_send * x, double value)
void send_free (t_send * x)
void send_int (t_send * x, long value)
void send_list (t_send * x, t_symbol * msg, long argc, t_atom * argv)
void* send_new (t_symbol * s, long argc, t_atom * argv)
Variable Documentation
t_object* s_receivemaster_object = NULL [static]
Definition at line 40 of file jcom.snapshot~.cpp.
t_class* s_send_class [static]
Definition at line 39 of file jcom.snapshot~.cpp.