Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.colorspace/jcom.colorspace.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.colorspace/jcom.colorspace.cpp File Reference
#include "Jamoma.h"
Classes
struct t_cs
Functions
void * cs_new (Symbol *msg, long argc, Atom *argv)
void cs_free (t_cs *x)
void cs_bang (t_cs *x)
void cs_float (t_cs *x, double value)
void cs_int (t_cs *x, long value)
void cs_assist (t_cs *x, void *b, long m, long a, char *s)
void cs_list (t_cs *x, Symbol *msg, long argc, Atom *argv)
void no_transform (t_cs *x)
void rgb2cmy (t_cs *x, int r, int g, int b)
void cmy2rgb (t_cs *x, int c, int m, int y)
void rgb2hsv (t_cs *x, int red, int green, int blue)
void hsv2rgb (t_cs *x, int hue, int saturation, int value)
void rgb2xyz (t_cs *x, int r, int g, int b)
void xyz2rgb (t_cs *x, int xx, int xy, int xz)
void rgb2uvw (t_cs *x, int r, int g, int b)
void uvw2rgb (t_cs *x, int u, int v, int w)
void rgb2cone (t_cs *x, int r, int g, int b)
void cone2rgb (t_cs *x, int t1, int t2, int t3)
void rgb2lab (t_cs *x, int r, int g, int b)
void lab2rgb (t_cs *x, int l, int a, int b)
void rgb2yiq (t_cs *x, int r, int g, int b)
void yiq2rgb (t_cs *x, int y, int i, int q)
void rgb2hls (t_cs *x, int red, int green, int blue)
void hls2rgb (t_cs *x, int h, int l, int s)
void rgb2rgbcie (t_cs *x, int r, int g, int b)
void rgbcie2rgb (t_cs *x, int r, int g, int b)
void rgb2rgbsmpte (t_cs *x, int r, int g, int b)
void rgbsmpte2rgb (t_cs *x, int r, int g, int b)
void rgb2hsl (t_cs *x, int red, int green, int blue)
void hsl2rgb (t_cs *x, int h, int s, int l)
double hls_value (double n1, double n2, double hue)
void tristimulus_product (double *matrix, double *input, double *output)
double cbrt (double x)
int main (void)
Variables
t_class * this_class
t_symbol * ps_no_transform
t_symbol * ps_rgb2cmy
t_symbol * ps_cmy2rgb
t_symbol * ps_rgb2hsv
t_symbol * ps_hsv2rgb
t_symbol * ps_rgb2xyz
t_symbol * ps_xyz2rgb
t_symbol * ps_rgb2uvw
t_symbol * ps_uvw2rgb
t_symbol * ps_rgb2retinalcone
t_symbol * ps_retinalcone2rgb
t_symbol * ps_rgb2lab
t_symbol * ps_lab2rgb
t_symbol * ps_rgb2yiq
t_symbol * ps_yiq2rgb
t_symbol * ps_rgb2hls
t_symbol * ps_hls2rgb
t_symbol * ps_rgb2rgbcie
t_symbol * ps_rgbcie2rgb
t_symbol * ps_rgb2rgbsmpte
t_symbol * ps_rgbsmpte2rgb
t_symbol * ps_rgb2hsl
t_symbol * ps_hsl2rgb
t_symbol * ps_split
t_symbol * ps_packed
Function Documentation
double cbrt (double x)
Definition at line 934 of file jcom.colorspace.cpp.
Referenced by lab2rgb(), and rgb2lab().
void cmy2rgb (t_cs * x, int c, int m, int y)
Definition at line 334 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, and t_cs::calc3.
Referenced by cs_bang().
void cone2rgb (t_cs * x, int t1, int t2, int t3)
Definition at line 542 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void cs_assist (t_cs * x, void * b, long m, long a, char * s)
Definition at line 213 of file jcom.colorspace.cpp.
Referenced by main().
void cs_bang (t_cs * x)
Definition at line 275 of file jcom.colorspace.cpp.
References t_cs::attr_mode, t_cs::attr_outputtype, t_cs::calc1, t_cs::calc2, t_cs::calc3, cmy2rgb(), cone2rgb(), hls2rgb(), hsl2rgb(), hsv2rgb(), lab2rgb(), no_transform(), t_cs::out1, t_cs::out2, t_cs::out3, ps_cmy2rgb, ps_hls2rgb, ps_hsl2rgb, ps_hsv2rgb, ps_lab2rgb, ps_no_transform, ps_packed, ps_retinalcone2rgb, ps_rgb2cmy, ps_rgb2hls, ps_rgb2hsl, ps_rgb2hsv, ps_rgb2lab, ps_rgb2retinalcone, ps_rgb2rgbcie, ps_rgb2rgbsmpte, ps_rgb2uvw, ps_rgb2xyz, ps_rgb2yiq, ps_rgbcie2rgb, ps_rgbsmpte2rgb, ps_uvw2rgb, ps_xyz2rgb, ps_yiq2rgb, rgb2cmy(), rgb2cone(), rgb2hls(), rgb2hsl(), rgb2hsv(), rgb2lab(), rgb2rgbcie(), rgb2rgbsmpte(), rgb2uvw(), rgb2xyz(), rgb2yiq(), rgbcie2rgb(), rgbsmpte2rgb(), uvw2rgb(), t_cs::val1, t_cs::val2, t_cs::val3, xyz2rgb(), and yiq2rgb().
Referenced by cs_float(), cs_int(), cs_list(), and main().
void cs_float (t_cs * x, double value)
Definition at line 248 of file jcom.colorspace.cpp.
References cs_bang().
Referenced by main().
void cs_free (t_cs * x)
Definition at line 202 of file jcom.colorspace.cpp.
References t_cs::inlets.
Referenced by main().
void cs_int (t_cs * x, long value)
Definition at line 234 of file jcom.colorspace.cpp.
References cs_bang().
Referenced by main().
void cs_list (t_cs * x, Symbol * msg, long argc, Atom * argv)
Definition at line 263 of file jcom.colorspace.cpp.
References t_cs::attr_autopack, cs_bang(), t_cs::val1, t_cs::val2, and t_cs::val3.
Referenced by main().
void * cs_new (Symbol * msg, long argc, Atom * argv)
Definition at line 177 of file jcom.colorspace.cpp.
References ps_rgb2hsl, ps_split, and this_class.
Referenced by main().
void hls2rgb (t_cs * x, int h, int l, int s)
Definition at line 719 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and hls_value().
Referenced by cs_bang().
double hls_value (double n1, double n2, double hue)
Definition at line 13 of file ColorDataspace.cpp.
Referenced by HSLUnit::convertToNeutral(), hls2rgb(), and hsl2rgb().
void hsl2rgb (t_cs * x, int h, int s, int l)
Definition at line 873 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and hls_value().
Referenced by cs_bang().
void hsv2rgb (t_cs * x, int hue, int saturation, int value)
Definition at line 393 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, and t_cs::calc3.
Referenced by cs_bang().
void lab2rgb (t_cs * x, int l, int a, int b)
Definition at line 605 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, cbrt(), and tristimulus_product().
Referenced by cs_bang().
int main (void)
Definition at line 103 of file jcom.colorspace.cpp.
References cs_assist(), cs_bang(), cs_float(), cs_free(), cs_int(), cs_list(), cs_new(), jamoma_init(), ps_cmy2rgb, ps_hls2rgb, ps_hsl2rgb, ps_hsv2rgb, ps_lab2rgb, ps_no_transform, ps_packed, ps_retinalcone2rgb, ps_rgb2cmy, ps_rgb2hls, ps_rgb2hsl, ps_rgb2hsv, ps_rgb2lab, ps_rgb2retinalcone, ps_rgb2rgbcie, ps_rgb2rgbsmpte, ps_rgb2uvw, ps_rgb2xyz, ps_rgb2yiq, ps_rgbcie2rgb, ps_rgbsmpte2rgb, ps_split, ps_uvw2rgb, ps_xyz2rgb, ps_yiq2rgb, and this_class.
void no_transform (t_cs * x)
Definition at line 320 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, t_cs::val1, t_cs::val2, and t_cs::val3.
Referenced by cs_bang().
void rgb2cmy (t_cs * x, int r, int g, int b)
Definition at line 327 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, and t_cs::calc3.
Referenced by cs_bang().
void rgb2cone (t_cs * x, int r, int g, int b)
Definition at line 517 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void rgb2hls (t_cs * x, int red, int green, int blue)
Definition at line 676 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, and t_cs::calc3.
Referenced by cs_bang().
void rgb2hsl (t_cs * x, int red, int green, int blue)
Definition at line 830 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, and t_cs::calc3.
Referenced by cs_bang().
void rgb2hsv (t_cs * x, int red, int green, int blue)
Definition at line 341 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and value.
Referenced by cs_bang().
void rgb2lab (t_cs * x, int r, int g, int b)
Definition at line 567 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, cbrt(), and tristimulus_product().
Referenced by cs_bang().
void rgb2rgbcie (t_cs * x, int r, int g, int b)
Definition at line 754 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void rgb2rgbsmpte (t_cs * x, int r, int g, int b)
Definition at line 792 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void rgb2uvw (t_cs * x, int r, int g, int b)
Definition at line 477 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void rgb2xyz (t_cs * x, int r, int g, int b)
Definition at line 437 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void rgb2yiq (t_cs * x, int r, int g, int b)
Definition at line 636 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void rgbcie2rgb (t_cs * x, int r, int g, int b)
Definition at line 773 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void rgbsmpte2rgb (t_cs * x, int r, int g, int b)
Definition at line 811 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void tristimulus_product (double * matrix, double * input, double * output)
Definition at line 922 of file jcom.colorspace.cpp.
Referenced by cone2rgb(), lab2rgb(), rgb2cone(), rgb2lab(), rgb2rgbcie(), rgb2rgbsmpte(), rgb2uvw(), rgb2xyz(), rgb2yiq(), rgbcie2rgb(), rgbsmpte2rgb(), uvw2rgb(), xyz2rgb(), and yiq2rgb().
void uvw2rgb (t_cs * x, int u, int v, int w)
Definition at line 497 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void xyz2rgb (t_cs * x, int xx, int xy, int xz)
Definition at line 457 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
void yiq2rgb (t_cs * x, int y, int i, int q)
Definition at line 656 of file jcom.colorspace.cpp.
References t_cs::calc1, t_cs::calc2, t_cs::calc3, and tristimulus_product().
Referenced by cs_bang().
Variable Documentation
t_symbol * ps_cmy2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_hls2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_hsl2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_hsv2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_lab2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol* ps_no_transform
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_packed
Definition at line 60 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_retinalcone2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2cmy
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2hls
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2hsl
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), cs_new(), and main().
t_symbol * ps_rgb2hsv
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2lab
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2retinalcone
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2rgbcie
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2rgbsmpte
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2uvw
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2xyz
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgb2yiq
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgbcie2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_rgbsmpte2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol* ps_split
Definition at line 60 of file jcom.colorspace.cpp.
Referenced by cs_new(), and main().
t_symbol * ps_uvw2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_xyz2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_symbol * ps_yiq2rgb
Definition at line 55 of file jcom.colorspace.cpp.
Referenced by cs_bang(), and main().
t_class* this_class
Definition at line 53 of file jcom.colorspace.cpp.