Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.h File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.h File Reference
#include "Jamoma.h"
Classes
struct t_subscriber
Data structure for storing information about objects subscribed to the hub.
struct t_preset_item
struct t_preset
Linked list of loaded presets.
struct t_hub
The Hub.
Defines
#define MAX_STRING_LEN 2048
#define LISTSIZE 512
Typedefs
typedef jcomList< t_subscriber * > subscriberList
typedef list< t_subscriber * >
::iterator subscriberIterator
typedef jcomList< t_preset_item * > presetItemList
typedef list< t_preset_item * >
::iterator presetItemListIterator
typedef jcomList< t_preset * > presetList
typedef list< t_preset * >
::iterator presetListIterator
Enumerations
enum outlets {
k_outlet_return = 0, k_outlet_dumpout, k_num_outlets, k_outlet_set = 0,
k_outlet_direct, k_outlet_dumpout, num_outlets, k_outlet_value = 0,
k_outlet_dumpout, num_outlets, k_outlet_thru = 0, k_outlet_dumpout,
num_outlets
}
Functions
void * hub_new (t_symbol *s, long argc, t_atom *argv)
The jcom.hub constructor.
void hub_examine_context (t_hub *x)
void hub_free (t_hub *x)
The hub deconstructor, free's any memory used by the hub.
void hub_assist (t_hub *x, void *b, long msg, long arg, char *dst)
t_object * hub_getobj_audioin (t_hub *x)
t_object * hub_getobj_audioout (t_hub *x)
void hub_bang (t_hub *x)
When the hub receives a bang, it ask all parameters and messages using /drive async to update.
void hub_symbol (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
t_symbol * hub_subscribe (t_hub *x, t_symbol *name, t_object *param_object, t_symbol *type)
This is called by clients who wish to register their parameters with the hub.
void hub_unsubscribe (t_hub *x, t_object *subscriber_object)
Unsubscribe a client from the hub.
void hub_receive (t_hub *x, t_symbol *name, long argc, t_atom *argv)
void hub_private (t_hub *x, t_symbol *name, long argc, t_atom *argv)
void hub_return (t_hub *x, t_symbol *name, long argc, t_atom *argv)
void hub_return_extended (t_hub *x, t_symbol *name, long argc, t_atom *argv)
void hub_outlet_return (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
void hub_paramnames_get (t_hub *x)
void hub_messagenames_get (t_hub *x)
void hub_returnnames_get (t_hub *x)
void hub_paramvalues_get (t_hub *x)
void hub_allnames_get (t_hub *x)
t_symbol * hub_modulename_get (t_hub *x)
t_symbol * core_modulename_get (t_hub *x)
Returns the name of the module.
t_symbol * hub_algorithmtype_get (t_hub *x)
void hub_init (t_hub *x, t_symbol *, long, t_atom *)
Initializes any jcom.init objects that are subscribed to the hub by sending them a 'bang'.
void hub_qfn_init (t_hub *x)
void hub_gui_build (t_hub *x)
void hub_module_view_alg (t_hub *x, t_symbol *, long, t_atom *)
void hub_ui_freeze (t_hub *x, t_symbol *, long argc, t_atom *argv)
Freeze updating of the UI.
void hub_ui_refresh (t_hub *x, t_symbol *, long, t_atom *)
Refresh the UI.
void hub_receive_callback (void *x, t_symbol *msg, long argc, t_atom *argv)
void hub_autodoc (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
void hub_doautodoc (t_hub *x, t_symbol *userpath)
void hub_autodoc_css (t_filehandle *file_handle, long *myEof)
void table_heading (t_filehandle *file_handle, long *myEof)
void hub_internals_create (t_hub *x)
Create parameters, messages, and other internal subscribers to the hub.
void hub_internals_destroy (t_hub *x)
Destroy (free) parameters, messages, etc.
void hub_internals_dispatch (t_hub *x, t_symbol *osc_name, long argc, t_atom *argv)
Send a message to the appropriate internal parameter or message.
void hub_preset_read (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Read an XML preset file.
void hub_preset_doread (t_hub *x, t_symbol *userpath)
This does the actual work for hub_preset_read since the actual act of reading the file is defered to the low priority thread.
void hub_preset_parse (t_hub *x, char *path)
Reads in and parses an XML file of presets.
short hub_preset_validate (t_hub *x, char *xml_path)
Given a path to an XML file it validates that it is a valid XML file.
void hub_preset_write (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Writes an XML preset file.
void hub_preset_dowrite (t_hub *x, t_symbol *userpath)
This does the actual work for hub_preset_write since the actual act of writing the file is defered to the low priority thread.
void hub_preset_recall (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Recalls a preset by number or name.
void hub_preset_interpolate (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
void hub_preset_copy (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Copies a preset by number or name.
void hub_preset_store (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Stores a preset by number or name.
void hub_preset_store_next (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
Stores a preset in the next slot by name.
void hub_preset_default (t_hub *x, t_symbol *, long, t_atom *)
Recall the default file and recall the first preset.
void hub_presets_clear (t_hub *x, t_symbol *, long, t_atom *)
Clears all presets loaded in memory.
void hub_presets_dump (t_hub *x, t_symbol *, long, t_atom *)
Dump all presets.
void hub_preset_buildmenu (t_hub *x)
Adds presets to the GUI menu.
Variables
t_class * hub_class
Define Documentation
#define LISTSIZE 512
Definition at line 16 of file jcom.hub.h.
Referenced by interpolate_presets(), main(), param_list(), param_new(), param_send_feedback(), and paramui_new().
#define MAX_STRING_LEN 2048
Definition at line 15 of file jcom.hub.h.
Referenced by hub_symbol().
Typedef Documentation
typedef jcomList<t_preset_item*> presetItemList
Definition at line 42 of file jcom.hub.h.
typedef list<t_preset_item*>::iterator presetItemListIterator
Definition at line 43 of file jcom.hub.h.
typedef jcomList<t_preset*> presetList
Definition at line 54 of file jcom.hub.h.
typedef list<t_preset*>::iterator presetListIterator
Definition at line 55 of file jcom.hub.h.
typedef list<t_subscriber*>::iterator subscriberIterator
Definition at line 32 of file jcom.hub.h.
typedef jcomList<t_subscriber*> subscriberList
Definition at line 31 of file jcom.hub.h.
Enumeration Type Documentation
enum outlets
Enumerator:
k_outlet_return
k_outlet_dumpout
k_num_outlets
k_outlet_set
k_outlet_direct
k_outlet_dumpout
num_outlets
k_outlet_value
k_outlet_dumpout
num_outlets
k_outlet_thru
k_outlet_dumpout
num_outlets
Definition at line 18 of file jcom.hub.h.
Function Documentation
t_symbol* core_modulename_get (t_hub * x)
Returns the name of the module.
Only really used by jcom.core.cpp
Returns:
the name of the module
Definition at line 599 of file jcom.hub.cpp.
References t_hub::attr_name.
Referenced by main().
t_symbol* hub_algorithmtype_get (t_hub * x)
Definition at line 604 of file jcom.hub.cpp.
References t_hub::attr_algorithm_type.
Referenced by main().
void hub_allnames_get (t_hub * x)
Definition at line 834 of file jcom.hub.cpp.
References hub_messagenames_get(), hub_paramnames_get(), and hub_returnnames_get().
Referenced by main().
void hub_assist (t_hub * x, void * b, long msg, long arg, char * dst)
Definition at line 704 of file jcom.hub.cpp.
References k_outlet_dumpout, and k_outlet_return.
Referenced by main().
void hub_autodoc (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 13 of file jcom.hub.autodoc.cpp.
References hub_doautodoc().
Referenced by hub_internals_create().
void hub_autodoc_css (t_filehandle * file_handle, long * myEof)
Definition at line 420 of file jcom.hub.autodoc.cpp.
References jcom_core_file_writeline().
Referenced by hub_doautodoc().
void hub_bang (t_hub * x)
When the hub receives a bang, it ask all parameters and messages using /drive async to update.
Definition at line 1013 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_subscriber::object, ps_subscribe_message, ps_subscribe_parameter, t_hub::subscriber, and t_subscriber::type.
Referenced by main().
void hub_doautodoc (t_hub * x, t_symbol * userpath)
Definition at line 23 of file jcom.hub.autodoc.cpp.
References t_hub::attr_algorithm_type, t_hub::attr_description, t_hub::attr_name, t_hub::attr_size, t_hub::attr_type, jcomList< T >::begin(), jcomList< T >::end(), hub_autodoc_css(), hub_outlet_return(), t_hub::in_object, jcom_core_file_writeline(), t_subscriber::name, t_subscriber::object, t_hub::out_object, ps_clipmode, ps_description, ps_done, ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_toggle, ps_num_inputs, ps_num_outputs, ps_ramp_drive, ps_range, ps_repetitions, ps_subscribe_message, ps_subscribe_parameter, ps_subscribe_return, ps_type, t_hub::subscriber, table_heading(), and t_subscriber::type.
Referenced by hub_autodoc().
void hub_examine_context (t_hub * x)
Definition at line 207 of file jcom.hub.cpp.
References t_hub::attr_name, t_hub::container, jamoma_hub_register(), jamoma_patcher_getargs(), jamoma_patcher_getcontext(), jamoma_patcher_getvarname(), t_hub::osc_name, and s_jcom_send_notifications.
Referenced by hub_new().
void hub_free (t_hub * x)
The hub deconstructor, free's any memory used by the hub.
Parameters:
x the hub who's memory should be freed
See also:
hub_free
Definition at line 295 of file jcom.hub.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::clear(), jcomList< T >::end(), hub_internals_destroy(), hub_presets_clear(), t_hub::init_qelem, jamoma_hub_remove(), t_hub::jcom_receive, t_hub::jcom_send, t_hub::jcom_send_broadcast, t_hub::osc_name, t_hub::preset, ps_release, s_jcom_send_notifications, and t_hub::subscriber.
Referenced by main().
t_object* hub_getobj_audioin (t_hub * x)
Definition at line 722 of file jcom.hub.cpp.
References t_hub::attr_type, t_hub::in_object, and ps_audio.
Referenced by main().
t_object* hub_getobj_audioout (t_hub * x)
Definition at line 732 of file jcom.hub.cpp.
References t_hub::attr_type, t_hub::out_object, and ps_audio.
Referenced by main().
void hub_gui_build (t_hub * x)
Definition at line 637 of file jcom.hub.cpp.
References t_hub::attr_algorithm_type, t_hub::attr_inspector, t_hub::attr_name, t_hub::attr_size, t_hub::attr_skin, t_hub::attr_type, jcomList< T >::begin(), jcomList< T >::end(), t_hub::gui_object, t_subscriber::name, t_hub::osc_name, ps_algorithm_type, ps_ATTRIBUTES, ps_BUILD, ps_dispatched, ps_inspector, ps_MODULE_NAME, ps_MODULE_TITLE, ps_module_type, ps_PARAMETER, ps_size, ps_skin, ps_subscribe_message, ps_subscribe_parameter, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_qfn_init().
void hub_init (t_hub * x, t_symbol * , long , t_atom *)
Initializes any jcom.init objects that are subscribed to the hub by sending them a 'bang'.
Parameters:
x the hub who's subscribed jcom.init objects should be banged
Definition at line 610 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_preset_default(), ps_go, ps_subscribe_init, and t_hub::subscriber.
Referenced by hub_internals_create(), and hub_qfn_init().
void hub_internals_create (t_hub * x)
Create parameters, messages, and other internal subscribers to the hub.
Parameters:
x the hub
See also:
hub_internals_destroy
Definition at line 42 of file jcom.hub.internals.cpp.
References hubInternalObject::action, t_hub::hash_internals, hub_autodoc(), hub_init(), hub_module_view_alg(), hub_preset_copy(), hub_preset_default(), hub_preset_interpolate(), hub_preset_read(), hub_preset_recall(), hub_preset_store(), hub_preset_store_next(), hub_preset_write(), hub_presets_clear(), hub_presets_dump(), hub_ui_freeze(), and hub_ui_refresh().
Referenced by hub_new().
void hub_internals_destroy (t_hub * x)
Destroy (free) parameters, messages, etc.
that are internal to hub.
Parameters:
x the hub
See also:
hub_internals_create
Definition at line 110 of file jcom.hub.internals.cpp.
References t_hub::hash_internals.
Referenced by hub_free().
void hub_internals_dispatch (t_hub * x, t_symbol * osc_name, long argc, t_atom * argv)
Send a message to the appropriate internal parameter or message.
Parameters:
x the hub
osc_name the osc name of the parameter or message
argc the number of values to send to the parameter or message
argv the actual values to send to the parameter or message
Definition at line 132 of file jcom.hub.internals.cpp.
References t_hub::hash_internals.
Referenced by hub_receive().
void hub_messagenames_get (t_hub * x)
Definition at line 791 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_outlet_return(), t_subscriber::name, ps_message_name, ps_message_names_end, ps_message_names_start, ps_subscribe_message, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_allnames_get(), and main().
void hub_module_view_alg (t_hub * x, t_symbol * , long , t_atom *)
Definition at line 926 of file jcom.hub.cpp.
References hub_outlet_return(), t_hub::in_object, ps_open, and ps_slash_module_view_internals.
Referenced by hub_internals_create(), and hub_private().
t_symbol* hub_modulename_get (t_hub * x)
Definition at line 584 of file jcom.hub.cpp.
References t_hub::attr_name, hub_outlet_return(), and t_hub::osc_name.
Referenced by main().
void* hub_new (t_symbol * s, long argc, t_atom * argv)
The jcom.hub constructor.
Definition at line 126 of file jcom.hub.cpp.
References hub_examine_context(), hub_internals_create(), hub_qfn_init(), hub_receive_callback(), jamoma_object_getpatcher(), jcom_core_loadextern(), k_num_outlets, k_outlet_dumpout, MAX_NUM_CHANNELS, t_hub::outlets, ps_1U_half, ps_control, ps_default, ps_jcom_broadcast_fromHub, ps_jcom_receive, ps_jcom_remote_fromModule, ps_jcom_remote_toModule, ps_jcom_send, ps_setcallback, s_hub_class, and s_jcom_send_notifications.
Referenced by main().
void hub_outlet_return (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 566 of file jcom.hub.cpp.
References t_hub::jcom_send, k_outlet_return, t_hub::osc_name, and t_hub::outlets.
Referenced by hub_doautodoc(), hub_messagenames_get(), hub_module_view_alg(), hub_modulename_get(), hub_paramnames_get(), hub_paramvalues_get(), hub_receive(), hub_return(), hub_return_extended(), and hub_returnnames_get().
void hub_paramnames_get (t_hub * x)
Definition at line 742 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_outlet_return(), t_subscriber::name, ps_parameter_name, ps_parameter_names_end, ps_parameter_names_start, ps_subscribe_parameter, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_allnames_get(), and main().
void hub_paramvalues_get (t_hub * x)
Definition at line 764 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_outlet_return(), t_subscriber::name, t_subscriber::object, ps_parameter_value, ps_parameter_values_end, ps_parameter_values_start, ps_subscribe_parameter, ps_value, t_hub::subscriber, and t_subscriber::type.
Referenced by main().
void hub_preset_buildmenu (t_hub * x)
Adds presets to the GUI menu.
Parameters:
x a pointer to the hub whose preset menu will be updated
Definition at line 958 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_hub::gui_object, t_preset::name, t_hub::preset, ps_dispatched, ps_MENU_REBUILD, ps_NEW_PRESETS, and ps_NEW_PRESETS_START.
Referenced by hub_preset_copy(), hub_preset_doread(), and hub_preset_store().
void hub_preset_copy (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Copies a preset by number or name.
Parameters:
x the hub containing the preset
msg
argc the argument count for argv
argv the number or name of the preset to recall
See also:
hub_preset_store
Definition at line 35 of file jcom.hub.presets.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::end(), hub_preset_buildmenu(), t_preset::item, jcomList< T >::merge(), t_preset::name, t_preset::number, t_hub::preset, presetIsLess, and jcomList< T >::size().
Referenced by hub_internals_create(), and hub_private().
void hub_preset_default (t_hub * x, t_symbol * , long , t_atom *)
Recall the default file and recall the first preset.
Parameters:
x the hub whose default preset should be recalled
Definition at line 413 of file jcom.hub.presets.cpp.
References t_hub::attr_name, hub_preset_doread(), and hub_preset_recall().
Referenced by hub_init(), hub_internals_create(), and hub_private().
void hub_preset_doread (t_hub * x, t_symbol * userpath)
This does the actual work for hub_preset_read since the actual act of reading the file is defered to the low priority thread.
See also:
hub_preset_read
Definition at line 444 of file jcom.hub.presets.cpp.
References t_hub::attr_name, hub_preset_buildmenu(), hub_preset_parse(), and jcom_core_getfilepath().
Referenced by hub_preset_default(), and hub_preset_read().
void hub_preset_dowrite (t_hub * x, t_symbol * userpath)
This does the actual work for hub_preset_write since the actual act of writing the file is defered to the low priority thread.
See also:
hub_preset_write
Definition at line 861 of file jcom.hub.presets.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::end(), t_preset::item, jcom_core_file_writeline(), t_preset_item::list_size, t_preset::name, t_preset::number, t_preset_item::param_name, t_hub::preset, t_preset_item::priority, t_preset_item::type, and writeList().
Referenced by hub_preset_write().
void hub_preset_interpolate (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 256 of file jcom.hub.presets.cpp.
References t_hub::attr_name, find_preset(), interpolate_presets(), and t_hub::preset.
Referenced by hub_internals_create().
void hub_preset_parse (t_hub * x, char * path)
Reads in and parses an XML file of presets.
Parameters:
x the hub to which the loaded presets should be attached
path the path the XML file to read
Definition at line 497 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), coerceType(), hub_preset_validate(), hub_presets_clear(), t_preset::item, t_preset_item::list_size, jcomList< T >::merge(), t_preset::name, t_preset::number, t_preset_item::param_name, t_hub::preset, presetIsLess, t_preset_item::priority, ps_msg_generic, ps_msg_int, ps_msg_symbol, ps_msg_toggle, jcomList< T >::push_back(), t_preset_item::type, and t_preset_item::value_list.
Referenced by hub_preset_doread().
void hub_preset_read (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Read an XML preset file.
Parameters:
x the hub to the preset file should be loaded for
userpath path to the XML file to load
See also:
hub_preset_doread hub_preset_write hub_preset_dowrite
Definition at line 431 of file jcom.hub.presets.cpp.
References hub_preset_doread().
Referenced by hub_internals_create(), and hub_private().
void hub_preset_recall (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Recalls a preset by number or name.
Parameters:
x the hub containing the preset
msg
argc the argument count for argv
argv the number or name of the preset to recall
See also:
hub_preset_store
Definition at line 89 of file jcom.hub.presets.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::end(), hub_symbol(), t_preset_item::list_size, t_preset_item::param_name, t_hub::preset, t_preset_item::priority, and t_preset_item::value_list.
Referenced by hub_internals_create(), hub_preset_default(), and hub_private().
void hub_preset_store (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Stores a preset by number or name.
Parameters:
x the hub containing the preset
msg
argc the argument count for argv
argv the number of the preset with an optional name
See also:
hub_preset_recall
Definition at line 287 of file jcom.hub.presets.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::empty(), jcomList< T >::end(), jcomList< T >::erase(), hub_preset_buildmenu(), t_preset::item, t_preset_item::list_size, jcomList< T >::merge(), t_subscriber::name, t_preset::name, t_preset::number, t_subscriber::object, t_preset_item::param_name, t_hub::preset, presetIsLess, t_preset_item::priority, ps_priority, ps_subscribe_parameter, ps_type, ps_value, jcomList< T >::push_back(), jcomList< T >::size(), t_hub::subscriber, t_preset_item::type, t_subscriber::type, and t_preset_item::value_list.
Referenced by hub_internals_create(), hub_preset_store_next(), hub_preset_write(), and hub_private().
void hub_preset_store_next (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Stores a preset in the next slot by name.
Parameters:
x the hub containing the preset
msg
argc the argument count for argv
argv the number of the preset with an optional name
See also:
hub_preset_recall
Definition at line 404 of file jcom.hub.presets.cpp.
References hub_preset_store(), t_hub::preset, and jcomList< T >::size().
Referenced by hub_internals_create(), and hub_private().
short hub_preset_validate (t_hub * x, char * xml_path)
Given a path to an XML file it validates that it is a valid XML file.
Parameters:
x the hub for which the XML preset file should be validated for
xml_path the path to the XML file
Returns:
0 if succesfully validated, non-zero otherwise
Definition at line 657 of file jcom.hub.presets.cpp.
References t_hub::attr_name, and jcom_core_getfilepath().
Referenced by hub_preset_parse().
void hub_preset_write (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Writes an XML preset file.
Parameters:
x the hub whose presets should be written to disk
userpath path to the XML file to write
See also:
hub_preset_dowrite hub_preset_read hub_preset_doread
Definition at line 793 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::empty(), hub_preset_dowrite(), hub_preset_store(), t_hub::preset, and ps_default.
Referenced by hub_internals_create(), and hub_private().
void hub_presets_clear (t_hub * x, t_symbol * , long , t_atom *)
Clears all presets loaded in memory.
Parameters:
x the hub whose presets should be cleared
Definition at line 727 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::empty(), t_preset::item, t_hub::preset, and jcomList< T >::remove().
Referenced by hub_free(), hub_internals_create(), and hub_preset_parse().
void hub_presets_dump (t_hub * x, t_symbol * , long , t_atom *)
Dump all presets.
Parameters:
x a pointer to the hub whose presets should be dumped
Definition at line 757 of file jcom.hub.presets.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_preset::item, t_preset::name, t_preset::number, t_preset_item::param_name, t_hub::preset, t_preset_item::priority, ps_msg_int, ps_msg_symbol, ps_msg_toggle, and t_preset_item::type.
Referenced by hub_internals_create().
void hub_private (t_hub * x, t_symbol * name, long argc, t_atom * argv)
Definition at line 477 of file jcom.hub.cpp.
References hub_module_view_alg(), hub_preset_copy(), hub_preset_default(), hub_preset_read(), hub_preset_recall(), hub_preset_store(), hub_preset_store_next(), hub_preset_write(), hub_symbol(), hub_ui_freeze(), hub_ui_refresh(), ps__gui__, ps_slash_module_view_internals, ps_slash_preset_slash_copy, ps_slash_preset_slash_default, ps_slash_preset_slash_load, ps_slash_preset_slash_recall, ps_slash_preset_slash_store, ps_slash_preset_slash_storenext, ps_slash_preset_slash_write, ps_slash_ui_slash_freeze, and ps_slash_ui_slash_refresh.
Referenced by main().
void hub_qfn_init (t_hub * x)
Definition at line 629 of file jcom.hub.cpp.
References hub_gui_build(), and hub_init().
Referenced by hub_new().
void hub_receive (t_hub * x, t_symbol * name, long argc, t_atom * argv)
Definition at line 454 of file jcom.hub.cpp.
References hub_internals_dispatch(), hub_outlet_return(), t_hub::in_object, t_hub::out_object, and ps_algorithm_message.
Referenced by main().
void hub_receive_callback (void * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 970 of file jcom.hub.cpp.
References t_hub::attr_name, t_hub::osc_name, and t_hub::using_wildcard.
Referenced by hub_new().
void hub_return (t_hub * x, t_symbol * name, long argc, t_atom * argv)
Definition at line 527 of file jcom.hub.cpp.
References hub_outlet_return().
Referenced by main().
void hub_return_extended (t_hub * x, t_symbol * name, long argc, t_atom * argv)
Definition at line 540 of file jcom.hub.cpp.
References hub_outlet_return().
Referenced by main().
void hub_returnnames_get (t_hub * x)
Definition at line 812 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), hub_outlet_return(), t_subscriber::name, ps_message_return, ps_return_names_end, ps_return_names_start, ps_subscribe_return, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_allnames_get(), and main().
t_symbol* hub_subscribe (t_hub * x, t_symbol * name, t_object * param_object, t_symbol * type)
This is called by clients who wish to register their parameters with the hub.
Meaning these is typically called by jcom.parameter
Parameters:
x the hub the client wants to subscribe to
name the name of the subscribing object
param_object a pointer to the subscribing object itself
type the type of the object subscribing to the hub
Returns:
the name of the hub subscribed to
See also:
hub_unsubscribe
Definition at line 334 of file jcom.hub.cpp.
References t_hub::attr_name, t_hub::gui_object, t_hub::in_object, t_hub::init_qelem, MAX_NUM_CHANNELS, jcomList< T >::merge(), t_hub::meter_object, t_subscriber::name, t_hub::num_parameters, t_subscriber::object, t_hub::osc_name, t_hub::out_object, t_hub::preview_object, ps___preview__, ps__gui__, ps_link_in, ps_link_out, ps_register_meter, ps_register_preview, ps_subscribe_in, ps_subscribe_out, ps_subscribe_parameter, ps_subscribe_remote, t_hub::subscriber, subscriberIsLess, and t_subscriber::type.
Referenced by main().
void hub_symbol (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 843 of file jcom.hub.cpp.
References t_hub::attr_name, jcomList< T >::begin(), jcomList< T >::end(), jcom_core_atom_copy(), MAX_STRING_LEN, t_subscriber::name, t_subscriber::object, t_hub::osc_name, t_hub::out_object, ps_algorithm_message, ps_audio_meters_freeze, ps_dispatched, ps_slash_audio_meters_freeze, ps_star, ps_subscribe_message, ps_subscribe_parameter, ps_subscribe_return, t_hub::subscriber, t_subscriber::type, and t_hub::using_wildcard.
Referenced by hub_preset_recall(), hub_private(), interpolate_presets(), and main().
void hub_ui_freeze (t_hub * x, t_symbol * , long argc, t_atom * argv)
Freeze updating of the UI.
Parameters:
x a pointer to the hub
value non-zero to freeze UI updates, 0 to enable updating the UI
See also:
hub_ui_refresh
Definition at line 935 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_subscriber::object, ps_subscribe_parameter, ps_ui_slash_freeze, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_internals_create(), and hub_private().
void hub_ui_refresh (t_hub * x, t_symbol * , long , t_atom *)
Refresh the UI.
Parameters:
x a pointer to the hub
See also:
hub_ui_freeze
Definition at line 953 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), t_subscriber::object, ps_subscribe_parameter, ps_ui_slash_refresh, t_hub::subscriber, and t_subscriber::type.
Referenced by hub_internals_create(), and hub_private().
void hub_unsubscribe (t_hub * x, t_object * subscriber_object)
Unsubscribe a client from the hub.
Parameters:
x the hub to be unsubscribed from
subscriber_object the object to unsubscribe
See also:
hub_subscribe
XXX why does this need to be here? It seems Microsoft's compiler is generating code that will preincrement (++) the item iterator in the for loop despite the fact that the for loops if condition has been met and following conditional statement shouldn't execute. Either that or something awkward about the the behavior of their STL implementation
Definition at line 403 of file jcom.hub.cpp.
References jcomList< T >::begin(), jcomList< T >::end(), jcomList< T >::erase(), t_hub::in_object, MAX_NUM_CHANNELS, t_subscriber::name, t_hub::num_parameters, t_subscriber::object, t_hub::out_object, ps_subscribe_in, ps_subscribe_out, ps_subscribe_parameter, ps_subscribe_remote, ps_unlink_in, ps_unlink_out, t_hub::subscriber, and t_subscriber::type.
Referenced by main().
void table_heading (t_filehandle * file_handle, long * myEof)
Definition at line 404 of file jcom.hub.autodoc.cpp.
References jcom_core_file_writeline().
Referenced by hub_doautodoc().
Variable Documentation
t_class* hub_class