Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.gain~/jcom.gain~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.gain~/jcom.gain~.cpp File Reference
#include "Jamoma.h"
Classes
struct t_gain
Functions
void * gain_new (t_symbol *s, long argc, t_atom *argv)
void gain_free (t_gain *x)
void gain_dsp (t_gain *x, t_signal **sp, short *count)
void gain_assist (t_gain *x, void *b, long m, long a, char *s)
t_int * gain_perform (t_int *w)
t_max_err attr_set_gain (t_gain *x, void *attr, long argc, t_atom *argv)
t_max_err attr_set_mix (t_gain *x, void *attr, long argc, t_atom *argv)
t_max_err attr_set_bypass (t_gain *x, void *attr, long argc, t_atom *argv)
int main (void)
Variables
t_class * gain_class
t_symbol * ps_float32
t_symbol * ps_long
t_symbol * ps_dumpout
Function Documentation
t_max_err attr_set_bypass (t_gain * x, void * attr, long argc, t_atom * argv)
Definition at line 194 of file jcom.gain~.cpp.
References t_gain::attr_bypass, t_gain::attr_mix, and t_gain::xfade.
Referenced by main().
t_max_err attr_set_gain (t_gain * x, void * attr, long argc, t_atom * argv)
Definition at line 171 of file jcom.gain~.cpp.
References t_gain::attr_gain, and t_gain::gain.
Referenced by main().
t_max_err attr_set_mix (t_gain * x, void * attr, long argc, t_atom * argv)
Definition at line 182 of file jcom.gain~.cpp.
References t_gain::attr_bypass, t_gain::attr_mix, and t_gain::xfade.
Referenced by main().
void gain_assist (t_gain * x, void * b, long m, long a, char * s)
Definition at line 157 of file jcom.gain~.cpp.
Referenced by main().
void gain_dsp (t_gain * x, t_signal ** sp, short * count)
Definition at line 224 of file jcom.gain~.cpp.
References gain_perform(), t_gain::num_chans, and t_gain::signal_temp.
Referenced by main().
void gain_free (t_gain * x)
Definition at line 139 of file jcom.gain~.cpp.
Referenced by main().
void * gain_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 97 of file jcom.gain~.cpp.
References gain_class, MAX_NUM_CHANNELS, and ps_dumpout.
Referenced by main().
t_int * gain_perform (t_int * w)
Definition at line 208 of file jcom.gain~.cpp.
References t_gain::gain, t_gain::signal_in, t_gain::signal_out, t_gain::signal_temp, and t_gain::xfade.
Referenced by gain_dsp().
int main (void)
Definition at line 48 of file jcom.gain~.cpp.
References attr_set_bypass(), attr_set_gain(), attr_set_mix(), gain_assist(), gain_class, gain_dsp(), gain_free(), gain_new(), jamoma_init(), ps_dumpout, ps_float32, and ps_long.
Variable Documentation
t_class* gain_class
Definition at line 39 of file jcom.gain~.cpp.
Referenced by gain_new(), and main().
t_symbol* ps_dumpout
Definition at line 42 of file jcom.gain~.cpp.
t_symbol* ps_float32
Definition at line 40 of file jcom.gain~.cpp.
t_symbol* ps_long
Definition at line 41 of file jcom.gain~.cpp.