Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.parameter/jcom.parameter.clip.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.parameter/jcom.parameter.clip.cpp File Reference
#include "jcom.parameter.h"
#include "TTAudioObject.h"
Functions
void param_clip_generic (t_param *x)
void param_clip_int (t_param *x)
void param_clip_float (t_param *x)
void param_clip_list (t_param *x)
Function Documentation
void param_clip_float (t_param * x)
Definition at line 42 of file jcom.parameter.clip.cpp.
References t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_range, t_param::common, ps_both, ps_high, and ps_low.
Referenced by param_clip_generic(), and param_output_float().
void param_clip_generic (t_param * x)
Definition at line 14 of file jcom.parameter.clip.cpp.
References t_param::atom_list, t_param::list_size, param_clip_float(), param_clip_int(), and param_clip_list().
Referenced by param_output_generic().
void param_clip_int (t_param * x)
Definition at line 26 of file jcom.parameter.clip.cpp.
References t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_range, t_param::common, ps_both, ps_high, and ps_low.
Referenced by param_clip_generic(), and param_output_int().
void param_clip_list (t_param * x)
Definition at line 58 of file jcom.parameter.clip.cpp.
References t_param::atom_list, t_jcom_core_subscriber_extended::attr_clipmode, t_jcom_core_subscriber_extended::attr_range, t_param::common, t_param::list_size, ps_both, ps_high, and ps_low.
Referenced by param_clip_generic(), and param_output_list().