Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.aed2xyz/jcom.aed2xyz.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.aed2xyz/jcom.aed2xyz.cpp File Reference
#include "jamoma.h"
Classes
struct t_aed2xyz
Functions
void * aed2xyz_new (void)
void aed2xyz_bang (t_aed2xyz *x)
void aed2xyz_assist (t_aed2xyz *x, void *b, long m, long a, char *s)
void aed2xyz_list (t_aed2xyz *x, Symbol *msg, long argc, t_atom *argv)
int main (void)
Variables
const double rad2deg = 180.0 / 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068
const double deg2rad = 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068 / 180.0
t_class * this_class
Function Documentation
void aed2xyz_assist (t_aed2xyz * x, void * b, long m, long a, char * s)
Definition at line 94 of file jcom.aed2xyz.cpp.
Referenced by main().
void aed2xyz_bang (t_aed2xyz * x)
Definition at line 132 of file jcom.aed2xyz.cpp.
References t_aed2xyz::outlet, and t_aed2xyz::outlist.
Referenced by aed2xyz_list(), and main().
void aed2xyz_list (t_aed2xyz * x, Symbol * msg, long argc, t_atom * argv)
Definition at line 110 of file jcom.aed2xyz.cpp.
References aed2xyz_bang(), deg2rad, and t_aed2xyz::outlist.
Referenced by main().
void * aed2xyz_new (void)
Definition at line 72 of file jcom.aed2xyz.cpp.
References this_class.
Referenced by main().
int main (void)
Definition at line 45 of file jcom.aed2xyz.cpp.
References aed2xyz_assist(), aed2xyz_bang(), aed2xyz_list(), aed2xyz_new(), jamoma_init(), and this_class.
Variable Documentation
const double deg2rad = 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068 / 180.0
Definition at line 19 of file jcom.aed2xyz.cpp.
Referenced by aed2xyz_list(), and main().
const double rad2deg = 180.0 / 3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068
Definition at line 18 of file jcom.aed2xyz.cpp.
Referenced by main(), and xyz2aed_list().
t_class* this_class
Definition at line 32 of file jcom.aed2xyz.cpp.
Referenced by aed2xyz_new(), cs_new(), cubic_interpolate_new(), delta2_new(), delta_new(), envExp_new(), main(), round_new(), stats_new(), velocity_new(), and xyz2aed_new().