Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.remote/jcom.remote.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.remote/jcom.remote.cpp File Reference
#include "Jamoma.h"
Classes
struct t_remote
Functions
void * remote_new (t_symbol *s, long argc, t_atom *argv)
void remote_assist (t_remote *x, void *b, long m, long a, char *s)
void remote_dispatched (t_remote *x, t_symbol *msg, long argc, t_atom *argv)
void remote_jit_matrix (t_remote *x, t_symbol *msg, long argc, t_atom *argv)
void remote_send_feedback (t_remote *x)
void remote_int (t_remote *x, long value)
void remote_float (t_remote *x, double value)
void remote_symbol (t_remote *x, t_symbol *msg, long argc, t_atom *argv)
void remote_list (t_remote *x, t_symbol *msg, long argc, t_atom *argv)
void remote_setcallback (t_remote *x, method newCallback, t_object *callbackArg)
void remote_subscribe (t_remote *x)
int main (void)
void remote_send_private (t_remote *x)
Variables
t_class * remote_class
Function Documentation
int main (void)
Definition at line 46 of file jcom.remote.cpp.
References jamoma_init(), jcom_core_subscriber_classinit_common(), jcom_core_subscriber_common_free(), remote_assist(), remote_class, remote_dispatched(), remote_float(), remote_int(), remote_jit_matrix(), remote_list(), remote_new(), remote_setcallback(), and remote_symbol().
void remote_assist (t_remote * x, void * b, long m, long a, char * s)
Definition at line 117 of file jcom.remote.cpp.
Referenced by main().
void remote_dispatched (t_remote * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 137 of file jcom.remote.cpp.
References t_jcom_core_subscriber_common::attr_name, t_remote::callback, t_remote::callbackArg, t_remote::common, and t_remote::outlet.
Referenced by main().
void remote_float (t_remote * x, double value)
Definition at line 170 of file jcom.remote.cpp.
References t_remote::output, t_remote::output_len, and remote_send_private().
Referenced by main().
void remote_int (t_remote * x, long value)
Definition at line 161 of file jcom.remote.cpp.
References t_remote::output, t_remote::output_len, and remote_send_private().
Referenced by main().
void remote_jit_matrix (t_remote * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 146 of file jcom.remote.cpp.
References t_remote::outlet.
Referenced by main().
void remote_list (t_remote * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 196 of file jcom.remote.cpp.
References jcom_core_atom_copy(), t_remote::output, t_remote::output_len, and remote_send_private().
Referenced by main().
void * remote_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 84 of file jcom.remote.cpp.
References t_remote::dumpout, jcom_core_subscriber_new_common(), jcom_core_subscriber_setcustomsubscribe_method(), jcom_core_subscriber_subscribe(), t_remote::outlet, ps_dumpout, ps_subscribe_remote, remote_class, and remote_subscribe().
Referenced by main().
void remote_send_feedback (t_remote * x)
void remote_send_private (t_remote * x)
Definition at line 153 of file jcom.remote.cpp.
References t_remote::common, t_jcom_core_subscriber_common::hub, t_remote::output, t_remote::output_len, and ps_private.
Referenced by remote_float(), remote_int(), remote_list(), and remote_symbol().
void remote_setcallback (t_remote * x, method newCallback, t_object * callbackArg)
Definition at line 208 of file jcom.remote.cpp.
References t_remote::callback, and t_remote::callbackArg.
Referenced by main().
void remote_subscribe (t_remote * x)
Definition at line 129 of file jcom.remote.cpp.
References t_remote::callback, t_remote::callbackArg, and ps_subscribe.
Referenced by remote_new().
void remote_symbol (t_remote * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 179 of file jcom.remote.cpp.
References jcom_core_atom_copy(), t_remote::output, t_remote::output_len, and remote_send_private().
Referenced by main().
Variable Documentation
t_class* remote_class
Definition at line 40 of file jcom.remote.cpp.
Referenced by main(), and remote_new().