Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.paramui/jcom.paramui.h File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.paramui/jcom.paramui.h File Reference
#include "ext.h"
#include "ext_obex.h"
#include "ext_user.h"
#include "ext_common.h"
#include "jpatcher_api.h"
#include "jgraphics.h"
#include "Jamoma.h"
#include "ext_symobject.h"
Classes
struct t_paramui
Defines
#define LISTSIZE 512
Functions
t_paramui * paramui_new (t_symbol *s, short argc, t_atom *argv)
void paramui_free (t_paramui *x)
void paramui_notify (t_paramui *x, t_symbol *s, t_symbol *msg, void *sender, void *data)
void paramui_paint (t_paramui *x, t_object *view)
void paramui_mousedown (t_paramui *x, t_object *patcherview, t_pt pt, long modifiers)
void paramui_mousedragdelta (t_paramui *x, t_object *patcherview, t_pt pt, long modifiers)
void paramui_mouseup (t_paramui *x, t_object *patcherview)
void paramui_menu_do (t_paramui *x, t_object *patcherview, t_pt px, long modifiers)
void paramui_menu_qfn (t_paramui *x)
void paramui_menu_build (t_paramui *x)
void paramui_refmenu_do (t_paramui *x, t_object *patcherview, t_pt px, long modifiers)
void paramui_refmenu_qfn (t_paramui *x)
void paramui_refmenu_build (t_paramui *x)
void * paramui_oksize (t_paramui *x, t_rect *rect)
t_max_err paramui_getName (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setName (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getType (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setType (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getDefault (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setDefault (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getRampDrive (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setRampDrive (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getRampFunction (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setRampFunction (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getUIFreeze (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setUIFreeze (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getStepsize (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setStepsize (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getPriority (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setPriority (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getRange (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setRange (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getRepetitions (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setRepetitions (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getClipmode (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setClipmode (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getDescription (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setDescription (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getDataspace (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setDataspace (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getUnitActive (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setUnitActive (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getUnitNative (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setUnitNative (t_paramui *x, void *attr, long argc, t_atom *argv)
Define Documentation
#define LISTSIZE 512
Definition at line 19 of file jcom.paramui.h.
Function Documentation
void paramui_free (t_paramui * x)
Definition at line 284 of file jcom.paramui.cpp.
References t_paramui::box, t_paramui::layout_unit, t_paramui::layout_value, t_paramui::menu_items, t_paramui::menu_qelem, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getClipmode (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 175 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getDataspace (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 212 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getDefault (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 45 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getDescription (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 191 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getName (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 13 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getPriority (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 125 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getRampDrive (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 61 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getRampFunction (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 77 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getRange (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 141 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getRepetitions (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 159 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getStepsize (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 109 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getType (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 29 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getUIFreeze (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 93 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getUnitActive (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 228 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getUnitNative (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 244 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
void paramui_menu_build (t_paramui * x)
Definition at line 534 of file jcom.paramui.cpp.
References t_paramui::attr_name, and t_paramui::menu_items.
Referenced by paramui_new(), and paramui_notify().
void paramui_menu_do (t_paramui * x, t_object * patcherview, t_pt px, long modifiers)
Definition at line 482 of file jcom.paramui.cpp.
References JAMOMA_MENU_FONT, and JAMOMA_MENU_FONTSIZE.
Referenced by paramui_mousedown().
void paramui_menu_qfn (t_paramui * x)
Definition at line 525 of file jcom.paramui.cpp.
References t_paramui::menu_items, t_paramui::menu_selection, and t_paramui::obj_parameter.
Referenced by paramui_new().
void paramui_mousedown (t_paramui * x, t_object * patcherview, t_pt pt, long modifiers)
Definition at line 455 of file jcom.paramui.cpp.
References paramui_menu_do().
Referenced by main().
void paramui_mousedragdelta (t_paramui * x, t_object * patcherview, t_pt pt, long modifiers)
Definition at line 467 of file jcom.paramui.cpp.
Referenced by main().
void paramui_mouseup (t_paramui * x, t_object * patcherview)
Definition at line 473 of file jcom.paramui.cpp.
Referenced by main().
t_paramui* paramui_new (t_symbol * s, short argc, t_atom * argv)
Definition at line 188 of file jcom.paramui.cpp.
References t_paramui::attr_clipmode, t_paramui::attr_dataspace, t_paramui::attr_default, t_paramui::attr_defaultSize, t_paramui::attr_description, t_paramui::attr_name, t_paramui::attr_priority, t_paramui::attr_rampDrive, t_paramui::attr_rampFunction, t_paramui::attr_range, t_paramui::attr_repetitions, t_paramui::attr_stepsize, t_paramui::attr_type, t_paramui::attr_uiFreeze, t_paramui::attr_unitActive, t_paramui::attr_unitNative, t_paramui::box, jcom_core_loadextern(), t_paramui::layout_unit, t_paramui::layout_value, LISTSIZE, t_paramui::menu_items, t_paramui::menu_qelem, t_paramui::obj_parameter, t_paramui::outlet, paramui_menu_build(), paramui_menu_qfn(), and s_ui_class.
Referenced by main().
void paramui_notify (t_paramui * x, t_symbol * s, t_symbol * msg, void * sender, void * data)
Definition at line 305 of file jcom.paramui.cpp.
References t_paramui::attr_label, t_paramui::box, and paramui_menu_build().
Referenced by main().
void* paramui_oksize (t_paramui * x, t_rect * rect)
Definition at line 556 of file jcom.paramui.cpp.
References s_light_gray.
Referenced by main().
void paramui_paint (t_paramui * x, t_object * view)
Definition at line 338 of file jcom.paramui.cpp.
References t_paramui::attr_dataspace, t_paramui::attr_type, t_paramui::box, JAMOMA_DEFAULT_FONT, JAMOMA_DEFAULT_FONTSIZE, t_paramui::layout_unit, t_paramui::layout_value, t_paramui::obj_parameter, ps_msg_float, ps_msg_int, ps_msg_symbol, ps_msg_toggle, ps_none, and s_light_gray.
Referenced by main().
void paramui_refmenu_build (t_paramui * x)
void paramui_refmenu_do (t_paramui * x, t_object * patcherview, t_pt px, long modifiers)
void paramui_refmenu_qfn (t_paramui * x)
t_max_err paramui_setClipmode (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 181 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_clipmode, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setDataspace (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 218 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_dataspace, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setDefault (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 51 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_default, t_paramui::attr_defaultSize, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setDescription (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 197 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_description, t_paramui::obj_parameter, and ps_description.
Referenced by main().
t_max_err paramui_setName (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 19 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_name, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setPriority (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 131 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_priority, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setRampDrive (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 67 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_rampDrive, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setRampFunction (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 83 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_rampFunction, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setRange (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 147 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_range, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setRepetitions (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 165 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_repetitions, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setStepsize (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 115 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_stepsize, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setType (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 35 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_type, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setUIFreeze (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 99 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_uiFreeze, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setUnitActive (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 234 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_unitActive, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setUnitNative (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 250 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_unitNative, and t_paramui::obj_parameter.
Referenced by main().