Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.round/jcom.round.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.round/jcom.round.cpp File Reference
#include "Jamoma.h"
Classes
struct t_round
Defines
#define MAX_LISTLENGTH 256
Functions
void * round_new (void)
void round_float (t_round *x, double value)
void round_int (t_round *x, long value)
void round_list (t_round *x, t_symbol *msg, long argc, t_atom *argv)
void round_symbol (t_round *x, t_symbol *msg, long argc, t_atom *argv)
void round_assist (t_round *round, void *b, long m, long a, char *s)
int main (void)
Variables
t_class * this_class
Define Documentation
#define MAX_LISTLENGTH 256
Definition at line 12 of file jcom.round.cpp.
Referenced by round_list(), and round_symbol().
Function Documentation
int main (void)
Definition at line 36 of file jcom.round.cpp.
References jamoma_init(), round_assist(), round_float(), round_int(), round_list(), round_new(), round_symbol(), and this_class.
void round_assist (t_round * round, void * b, long m, long a, char * s)
Definition at line 82 of file jcom.round.cpp.
Referenced by main().
void round_float (t_round * x, double value)
Definition at line 99 of file jcom.round.cpp.
References t_round::outlet.
Referenced by main().
void round_int (t_round * x, long value)
Definition at line 92 of file jcom.round.cpp.
References t_round::outlet.
Referenced by main().
void round_list (t_round * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 113 of file jcom.round.cpp.
References MAX_LISTLENGTH, t_round::outlet, and value.
Referenced by main().
void * round_new (void)
Definition at line 65 of file jcom.round.cpp.
References this_class.
Referenced by main().
void round_symbol (t_round * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 142 of file jcom.round.cpp.
References MAX_LISTLENGTH, t_round::outlet, and value.
Referenced by main().
Variable Documentation
t_class* this_class
Definition at line 31 of file jcom.round.cpp.