Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.teabox~/jcom.teabox~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.teabox~/jcom.teabox~.cpp File Reference
#include "ext.h"
#include "ext_strings.h"
#include "z_dsp.h"
Classes
struct t_teabox
Functions
t_int * teabox_perform (t_int *w)
void teabox_dsp (t_teabox *x, t_signal **sp, short *count)
void teabox_assist (t_teabox *x, void *b, long m, long a, char *s)
void * teabox_new (void)
void teabox_getversion (t_teabox *x)
void teabox_getstatus (t_teabox *x)
int main (void)
Variables
void * teabox_class
Function Documentation
int main (void)
Definition at line 55 of file jcom.teabox~.cpp.
References teabox_assist(), teabox_class, teabox_dsp(), teabox_getstatus(), teabox_getversion(), and teabox_new().
void teabox_assist (t_teabox * x, void * b, long m, long a, char * s)
Definition at line 97 of file jcom.teabox~.cpp.
Referenced by main().
void teabox_dsp (t_teabox * x, t_signal ** sp, short * count)
Definition at line 223 of file jcom.teabox~.cpp.
References teabox_getstatus(), and teabox_perform().
Referenced by main().
void teabox_getstatus (t_teabox * x)
Definition at line 140 of file jcom.teabox~.cpp.
References t_teabox::hw_version, and t_teabox::outlet.
Referenced by main(), and teabox_dsp().
void teabox_getversion (t_teabox * x)
Definition at line 120 of file jcom.teabox~.cpp.
References t_teabox::hw_version, and t_teabox::outlet.
Referenced by main().
void * teabox_new (void)
Definition at line 72 of file jcom.teabox~.cpp.
References teabox_class.
Referenced by main().
t_int * teabox_perform (t_int * w)
Definition at line 155 of file jcom.teabox~.cpp.
References t_teabox::counter, t_teabox::data, t_teabox::hw_version, t_teabox::last_value, value, and t_teabox::x_obj.
Referenced by teabox_dsp().
Variable Documentation
void* teabox_class
Definition at line 29 of file jcom.teabox~.cpp.
Referenced by main(), and teabox_new().