Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.out/jcom.out.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.out/jcom.out.cpp File Reference
#include "Jamoma.h"
#include "jcom.out.h"
Defines
#define POLL_INTERVAL 150
Functions
int main (void)
void * out_new (t_symbol *s, long argc, t_atom *argv)
jcom.out and jcom.out~ constructor
void out_subscribe (void *z)
void out_free (t_out *x)
jcom.out and jcom.out~ deconstructor
void out_release (t_out *x)
Unsubscribe from jcom.hub.
void out_assist (t_out *x, void *b, long msg, long arg, char *dst)
Max assistance method.
void out_algorithm_message (t_out *x, t_symbol *msg, long argc, t_atom *argv)
void out_link_to_in_object (t_out *x, t_in *y)
void out_unlink (t_out *x)
void out_register_meter (t_out *x, int meternum, void *meter_object)
void out_remove_meters (t_out *x)
void out_register_preview (t_out *x, void *preview_object)
void out_dispatched (t_out *x, t_symbol *msg, long argc, t_atom *argv)
void out_sendbypassedvalue (t_out *x, short inletnum, t_symbol *msg, long argc, t_atom *argv)
void out_sendlastvalue (t_out *x)
void out_anything (t_out *x, t_symbol *msg, long argc, t_atom *argv)
void update_meters (t_out *x)
t_int * out_perform (t_int *w)
jcom.out~ MSP perform method
t_int * out_perform_zero (t_int *w)
void out_getAudioForChannel (t_out *x, int channel, float **vector)
void out_dsp (t_out *x, t_signal **sp, short *count)
jcom.out~ DSP method
void out_alloc (t_out *x, int vector_size)
Variables
t_class * out_class
Define Documentation
#define POLL_INTERVAL 150
Definition at line 26 of file jcom.out.cpp.
Function Documentation
int main (void)
Definition at line 35 of file jcom.out.cpp.
References jamoma_init(), jcom_core_subscriber_classinit_common(), out_algorithm_message(), out_anything(), out_assist(), out_class, out_dispatched(), out_dsp(), out_free(), out_getAudioForChannel(), out_link_to_in_object(), out_new(), out_register_meter(), out_register_preview(), out_release(), out_remove_meters(), out_sendbypassedvalue(), out_sendlastvalue(), and out_unlink().
void out_algorithm_message (t_out * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 245 of file jcom.out.cpp.
References t_out::attr_bypass, t_out::attr_defeat_meters, t_out::attr_gain, t_out::attr_mix, t_out::attr_mute, t_out::attr_preview, t_out::gain, ps_audio_bypass, ps_audio_gain_midi, ps_audio_meters_freeze, ps_audio_mix, ps_audio_mute, ps_audio_sample_rate, ps_slash_audio_bypass, ps_slash_audio_gain_midi, ps_slash_audio_meters_freeze, ps_slash_audio_mix, ps_slash_audio_mute, ps_slash_audio_sample_rate, ps_slash_video_preview, ps_video_preview, and t_out::xfade.
Referenced by main().
void out_alloc (t_out * x, int vector_size)
Definition at line 473 of file jcom.out.cpp.
References t_out::ramp_gain, t_out::ramp_xfade, t_out::signal_temp, and t_out::vector_size.
Referenced by out_dsp(), and out_new().
void out_anything (t_out * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 351 of file jcom.out.cpp.
Referenced by main().
void out_assist (t_out * x, void * b, long msg, long arg, char * dst)
Max assistance method.
Definition at line 233 of file jcom.out.cpp.
Referenced by main().
void out_dispatched (t_out * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 323 of file jcom.out.cpp.
Referenced by main().
void out_dsp (t_out * x, t_signal ** sp, short * count)
jcom.out~ DSP method
Definition at line 453 of file jcom.out.cpp.
References t_out::num_outputs, out_alloc(), out_perform(), out_perform_zero(), t_out::out_vectors, t_out::ramp_gain, and t_out::ramp_xfade.
Referenced by main().
void out_free (t_out * x)
jcom.out and jcom.out~ deconstructor
Definition at line 196 of file jcom.out.cpp.
References jcom_core_subscriber_common_free().
Referenced by main().
void out_getAudioForChannel (t_out * x, int channel, float ** vector)
Definition at line 446 of file jcom.out.cpp.
References t_out::out_vectors.
Referenced by main().
void out_link_to_in_object (t_out * x, t_in * y)
Definition at line 288 of file jcom.out.cpp.
References t_out::in_object.
Referenced by main().
void* out_new (t_symbol * s, long argc, t_atom * argv)
jcom.out and jcom.out~ constructor
Definition at line 101 of file jcom.out.cpp.
References t_out::dumpout, jcom_core_subscriber_new_common(), jcom_core_subscriber_setcustomsubscribe_method(), jcom_core_subscriber_subscribe(), MAX_NUM_CHANNELS, out_alloc(), out_class, out_subscribe(), ps__jcom_out__, ps_dumpout, ps_subscribe_out, and update_meters().
Referenced by main().
t_int* out_perform (t_int * w)
jcom.out~ MSP perform method
Definition at line 385 of file jcom.out.cpp.
References t_out::attr_bypass, t_out::attr_defeat_meters, t_out::attr_mute, t_out::clock, t_out::clock_is_set, t_out::copy, t_out::gain, t_out::in_object, t_out::peakamp, POLL_INTERVAL, t_in::signal_in, t_out::signal_in, t_out::signal_out, t_out::signal_temp, and t_out::xfade.
Referenced by out_dsp().
t_int* out_perform_zero (t_int * w)
Definition at line 435 of file jcom.out.cpp.
Referenced by out_dsp().
void out_register_meter (t_out * x, int meternum, void * meter_object)
Definition at line 299 of file jcom.out.cpp.
References t_out::meter_object, and t_out::num_meter_objects.
Referenced by main().
void out_register_preview (t_out * x, void * preview_object)
Definition at line 316 of file jcom.out.cpp.
References t_out::preview_object.
Referenced by main().
void out_release (t_out * x)
Unsubscribe from jcom.hub.
Definition at line 216 of file jcom.out.cpp.
References t_out::common, t_out::in_object, jcom_core_subscriber_hubrelease(), MAX_NUM_CHANNELS, t_out::meter_object, t_out::num_meter_objects, and t_out::preview_object.
Referenced by main().
void out_remove_meters (t_out * x)
Definition at line 307 of file jcom.out.cpp.
References MAX_NUM_CHANNELS, t_out::meter_object, and t_out::num_meter_objects.
Referenced by main().
void out_sendbypassedvalue (t_out * x, short inletnum, t_symbol * msg, long argc, t_atom * argv)
Definition at line 330 of file jcom.out.cpp.
References t_out::outlet.
Referenced by main().
void out_sendlastvalue (t_out * x)
Definition at line 337 of file jcom.out.cpp.
References t_out::last_argc, t_out::last_argv, t_out::last_msg, t_out::num_outputs, and t_out::outlet.
Referenced by main().
void out_subscribe (void * z)
Definition at line 160 of file jcom.out.cpp.
References t_out::attr_algorithm_type, t_out::common, t_jcom_core_subscriber_common::hub, t_jcom_core_subscriber_common::module_name, t_out::num_meter_objects, ps_algorithm_type, ps_audio, ps_control, ps_default, ps_jitter, ps_module_type, ps_name, ps_poly, and ps_video.
Referenced by out_new().
void out_unlink (t_out * x)
Definition at line 293 of file jcom.out.cpp.
References t_out::in_object.
Referenced by main().
void update_meters (t_out * x)
Definition at line 367 of file jcom.out.cpp.
References t_out::clock_is_set, t_out::meter_object, t_out::num_meter_objects, t_out::peakamp, and ps_dispatched.
Referenced by out_new().
Variable Documentation
t_class* out_class
Definition at line 29 of file jcom.out.cpp.
Referenced by main(), and out_new().