Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.autodoc.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.hub/jcom.hub.autodoc.cpp File Reference
#include "jcom.hub.h"
Functions
void hub_autodoc (t_hub *x, t_symbol *msg, long argc, t_atom *argv)
void hub_doautodoc (t_hub *x, t_symbol *userpath)
void table_heading (t_filehandle *file_handle, long *myEof)
void hub_autodoc_css (t_filehandle *file_handle, long *myEof)
Function Documentation
void hub_autodoc (t_hub * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 13 of file jcom.hub.autodoc.cpp.
References hub_doautodoc().
Referenced by hub_internals_create().
void hub_autodoc_css (t_filehandle * file_handle, long * myEof)
Definition at line 420 of file jcom.hub.autodoc.cpp.
References jcom_core_file_writeline().
Referenced by hub_doautodoc().
void hub_doautodoc (t_hub * x, t_symbol * userpath)
Definition at line 23 of file jcom.hub.autodoc.cpp.
References t_hub::attr_algorithm_type, t_hub::attr_description, t_hub::attr_name, t_hub::attr_size, t_hub::attr_type, jcomList< T >::begin(), jcomList< T >::end(), hub_autodoc_css(), hub_outlet_return(), t_hub::in_object, jcom_core_file_writeline(), t_subscriber::name, t_subscriber::object, t_hub::out_object, ps_clipmode, ps_description, ps_done, ps_msg_float, ps_msg_generic, ps_msg_int, ps_msg_toggle, ps_num_inputs, ps_num_outputs, ps_ramp_drive, ps_range, ps_repetitions, ps_subscribe_message, ps_subscribe_parameter, ps_subscribe_return, ps_type, t_hub::subscriber, table_heading(), and t_subscriber::type.
Referenced by hub_autodoc().
void table_heading (t_filehandle * file_handle, long * myEof)
Definition at line 404 of file jcom.hub.autodoc.cpp.
References jcom_core_file_writeline().
Referenced by hub_doautodoc().