Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.zerox~/jcom.zerox~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.zerox~/jcom.zerox~.cpp File Reference
#include "Jamoma.h"
Classes
struct t_zerox
Defines
#define NUM_INPUTS 1
#define NUM_OUTPUTS 2
Functions
void * zerox_new (t_symbol *msg, long argc, t_atom *argv)
t_int * zerox_perform (t_int *w)
void zerox_dsp (t_zerox *x, t_signal **sp, short *count)
void zerox_assist (t_zerox *x, void *b, long m, long a, char *s)
t_max_err attr_set_size (t_zerox *x, void *attr, long argc, t_atom *argv)
void zerox_free (t_zerox *x)
int main (void)
Variables
t_class * zerox_class
Define Documentation
#define NUM_INPUTS 1
Definition at line 12 of file jcom.zerox~.cpp.
#define NUM_OUTPUTS 2
Definition at line 13 of file jcom.zerox~.cpp.
Function Documentation
t_max_err attr_set_size (t_zerox * x, void * attr, long argc, t_atom * argv)
Definition at line 125 of file jcom.zerox~.cpp.
References t_zerox::attr_size, and t_zerox::my_zerox.
Referenced by main().
int main (void)
Definition at line 40 of file jcom.zerox~.cpp.
References attr_set_size(), jamoma_init(), zerox_assist(), zerox_class, zerox_dsp(), zerox_free(), and zerox_new().
void zerox_assist (t_zerox * x, void * b, long m, long a, char * s)
Definition at line 110 of file jcom.zerox~.cpp.
Referenced by main().
void zerox_dsp (t_zerox * x, t_signal ** sp, short * count)
Definition at line 152 of file jcom.zerox~.cpp.
References t_zerox::my_zerox, and zerox_perform().
Referenced by main().
void zerox_free (t_zerox * x)
Definition at line 94 of file jcom.zerox~.cpp.
References NUM_INPUTS, and NUM_OUTPUTS.
Referenced by main().
void * zerox_new (t_symbol * msg, long argc, t_atom * argv)
Definition at line 70 of file jcom.zerox~.cpp.
References NUM_INPUTS, NUM_OUTPUTS, and zerox_class.
Referenced by main().
t_int * zerox_perform (t_int * w)
Definition at line 136 of file jcom.zerox~.cpp.
References t_zerox::my_zerox, t_zerox::signal_in, t_zerox::signal_out, and t_zerox::x_obj.
Referenced by zerox_dsp().
Variable Documentation
t_class* zerox_class
Definition at line 34 of file jcom.zerox~.cpp.
Referenced by main(), and zerox_new().