Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.ui/jcom.ui.internals.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.ui/jcom.ui.internals.cpp File Reference
#include "jcom.ui.h"
Classes
class uiInternalObject
Functions
void ui_internals_destroy (t_ui *obj)
void ui_mute (t_ui *obj, t_symbol *msg, long argc, t_atom *argv)
void ui_bypass (t_ui *obj, t_symbol *msg, long argc, t_atom *argv)
void ui_mix (t_ui *obj, t_symbol *msg, long argc, t_atom *argv)
void ui_gain (t_ui *obj, t_symbol *msg, long argc, t_atom *argv)
void ui_freeze (t_ui *obj, t_symbol *msg, long argc, t_atom *argv)
void ui_preview (t_ui *obj, t_symbol *msg, long argc, t_atom *argv)
t_max_err attr_set_mute (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_bypass (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_mix (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_gain (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_freeze (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_preview (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasmute (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasbypass (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasmix (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasgain (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_hasfreeze (t_ui *obj, void *attr, long argc, t_atom *argv)
t_max_err attr_set_haspreview (t_ui *obj, void *attr, long argc, t_atom *argv)
Function Documentation
t_max_err attr_set_bypass (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 134 of file jcom.ui.internals.cpp.
References t_ui::attr_isbypassed, t_ui::hash_internals, and value.
t_max_err attr_set_freeze (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 182 of file jcom.ui.internals.cpp.
References t_ui::attr_isfrozen, t_ui::hash_internals, and value.
Referenced by main().
t_max_err attr_set_gain (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 166 of file jcom.ui.internals.cpp.
References t_ui::attr_gain, t_ui::hash_internals, and value.
t_max_err attr_set_hasbypass (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 242 of file jcom.ui.internals.cpp.
References t_ui::attr_hasbypass, t_ui::hash_internals, uiInternalObject::setAction(), and ui_bypass().
Referenced by main().
t_max_err attr_set_hasfreeze (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 305 of file jcom.ui.internals.cpp.
References t_ui::attr_hasfreeze, t_ui::hash_internals, uiInternalObject::setAction(), and ui_freeze().
Referenced by main().
t_max_err attr_set_hasgain (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 284 of file jcom.ui.internals.cpp.
References t_ui::attr_hasgain, t_ui::hash_internals, uiInternalObject::setAction(), and ui_gain().
Referenced by main().
t_max_err attr_set_hasmix (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 263 of file jcom.ui.internals.cpp.
References t_ui::attr_hasmix, t_ui::hash_internals, uiInternalObject::setAction(), and ui_mix().
Referenced by main().
t_max_err attr_set_hasmute (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 219 of file jcom.ui.internals.cpp.
References t_ui::attr_hasmute, t_ui::hash_internals, uiInternalObject::setAction(), and ui_mute().
Referenced by main().
t_max_err attr_set_haspreview (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 326 of file jcom.ui.internals.cpp.
References t_ui::attr_haspreview, t_ui::hash_internals, uiInternalObject::setAction(), and ui_preview().
Referenced by main().
t_max_err attr_set_mix (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 150 of file jcom.ui.internals.cpp.
References t_ui::attr_mix, t_ui::hash_internals, and value.
t_max_err attr_set_mute (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 118 of file jcom.ui.internals.cpp.
References t_ui::attr_ismuted, t_ui::hash_internals, and value.
Referenced by main().
t_max_err attr_set_preview (t_ui * obj, void * attr, long argc, t_atom * argv)
Definition at line 198 of file jcom.ui.internals.cpp.
References t_ui::attr_ispreviewing, t_ui::hash_internals, and value.
Referenced by main().
void ui_bypass (t_ui * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 83 of file jcom.ui.internals.cpp.
References t_ui::attr_isbypassed, and t_ui::box.
Referenced by attr_set_hasbypass().
void ui_freeze (t_ui * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 104 of file jcom.ui.internals.cpp.
References t_ui::attr_isfrozen, and t_ui::box.
Referenced by attr_set_hasfreeze().
void ui_gain (t_ui * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 97 of file jcom.ui.internals.cpp.
References t_ui::attr_gain, and t_ui::box.
Referenced by attr_set_hasgain().
void ui_internals_destroy (t_ui * obj)
Definition at line 48 of file jcom.ui.internals.cpp.
References t_ui::hash_internals.
Referenced by ui_free().
void ui_mix (t_ui * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 90 of file jcom.ui.internals.cpp.
References t_ui::attr_mix, and t_ui::box.
Referenced by attr_set_hasmix().
void ui_mute (t_ui * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 77 of file jcom.ui.internals.cpp.
Referenced by attr_set_hasmute().
void ui_preview (t_ui * obj, t_symbol * msg, long argc, t_atom * argv)
Definition at line 111 of file jcom.ui.internals.cpp.
References t_ui::attr_ispreviewing, and t_ui::box.
Referenced by attr_set_haspreview().