Jamoma: /Users/tim/dev/Jamoma/SourceCode/Framework/Internals/jcom.receive.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/Framework/Internals/jcom.receive.cpp File Reference
#include "Jamoma.h"
Functions
void * receive_new (t_symbol *s, long argc, t_atom *argv)
void receive_free (t_receive *x)
void receive_assist (t_receive *x, void *b, long msg, long arg, char *dst)
t_max_err receive_setname (t_receive *x, void *attr, long argc, t_atom *argv)
void receive_setcallback (t_receive *x, void *callback, void *arg)
void receive_dispatch (t_receive *x, t_symbol *msg, long argc, t_atom *argv)
void receive_bind (t_receive *x)
void receive_remove (t_receive *x)
void receive_initclass ()
Variables
static t_class * s_receive_class
static t_object * s_receivemaster_object = NULL
Function Documentation
void receive_assist (t_receive * x, void * b, long msg, long arg, char * dst)
Definition at line 109 of file jcom.receive.cpp.
Referenced by receive_initclass().
void receive_bind (t_receive * x)
Definition at line 138 of file jcom.receive.cpp.
Referenced by receive_setname().
void receive_dispatch (t_receive * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 153 of file jcom.receive.cpp.
References t_receive::baton, t_receive::callback, and t_receive::outlet.
Referenced by receive_initclass().
void receive_free (t_receive * x)
Definition at line 100 of file jcom.receive.cpp.
References receive_remove().
Referenced by receive_initclass().
void receive_initclass ()
Definition at line 29 of file jcom.receive.cpp.
References receive_assist(), receive_dispatch(), receive_free(), receive_new(), receive_setcallback(), receive_setname(), and s_receive_class.
Referenced by jamoma_init().
void * receive_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 67 of file jcom.receive.cpp.
References s_receive_class, and s_receivemaster_object.
Referenced by receive_initclass().
void receive_remove (t_receive * x)
Definition at line 145 of file jcom.receive.cpp.
References t_receive::attr_name, ps_remove, and s_receivemaster_object.
Referenced by receive_free(), and receive_setname().
void receive_setcallback (t_receive * x, void * callback, void * arg)
Definition at line 165 of file jcom.receive.cpp.
References t_receive::baton, and t_receive::callback.
Referenced by receive_initclass().
t_max_err receive_setname (t_receive * x, void * attr, long argc, t_atom * argv)
Definition at line 123 of file jcom.receive.cpp.
References t_receive::attr_name, receive_bind(), and receive_remove().
Referenced by receive_initclass().
Variable Documentation
t_class* s_receive_class [static]
Definition at line 23 of file jcom.receive.cpp.
Referenced by receive_initclass(), and receive_new().
t_object* s_receivemaster_object = NULL [static]
Definition at line 24 of file jcom.receive.cpp.
Referenced by receive_new(), receive_remove(), send_list(), and send_new().