Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.teabox.bits~/jcom.teabox.bits~.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.teabox.bits~/jcom.teabox.bits~.cpp File Reference
#include "ext.h"
#include "ext_strings.h"
#include "z_dsp.h"
Classes
struct t_teabox_bits
Functions
t_int * teabox_bits_perform (t_int *w)
void teabox_bits_dsp (t_teabox_bits *x, t_signal **sp, short *count)
void teabox_bits_assist (t_teabox_bits *x, void *b, long m, long a, char *s)
void * teabox_bits_new (void)
int main (void)
Variables
void * teabox_bits_class
Function Documentation
int main (void)
Definition at line 50 of file jcom.teabox.bits~.cpp.
References teabox_bits_assist(), teabox_bits_class, teabox_bits_dsp(), and teabox_bits_new().
void teabox_bits_assist (t_teabox_bits * x, void * b, long m, long a, char * s)
Definition at line 84 of file jcom.teabox.bits~.cpp.
Referenced by main().
void teabox_bits_dsp (t_teabox_bits * x, t_signal ** sp, short * count)
Definition at line 136 of file jcom.teabox.bits~.cpp.
References teabox_bits_perform().
Referenced by main().
void * teabox_bits_new (void)
Definition at line 65 of file jcom.teabox.bits~.cpp.
References teabox_bits_class.
Referenced by main().
t_int * teabox_bits_perform (t_int * w)
Definition at line 94 of file jcom.teabox.bits~.cpp.
References t_teabox_bits::x_obj.
Referenced by teabox_bits_dsp().
Variable Documentation
void* teabox_bits_class
Definition at line 30 of file jcom.teabox.bits~.cpp.
Referenced by main(), and teabox_bits_new().