Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.delta2/jcom.delta2.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.delta2/jcom.delta2.cpp File Reference
#include "Jamoma.h"
Classes
struct t_delta2
Functions
void * delta2_new (void)
void delta2_bang (t_delta2 *x)
void delta2_int (t_delta2 *x, long n)
void delta2_float (t_delta2 *x, double f)
void delta2_clear (t_delta2 *x)
void delta2_set (t_delta2 *x, Symbol *s, short ac, Atom *setval)
void delta2_assist (t_delta2 *x, void *b, long msg, long arg, char *dst)
int main (void)
Variables
t_class * this_class
Function Documentation
void delta2_assist (t_delta2 * x, void * b, long msg, long arg, char * dst)
Definition at line 181 of file jcom.delta2.cpp.
Referenced by main().
void delta2_bang (t_delta2 * x)
Definition at line 100 of file jcom.delta2.cpp.
References t_delta2::delta2, and t_delta2::outlet.
Referenced by delta2_float(), and main().
void delta2_clear (t_delta2 * x)
Definition at line 173 of file jcom.delta2.cpp.
References t_delta2::clearflag, and t_delta2::delta2.
Referenced by delta2_new(), and main().
void delta2_float (t_delta2 * x, double f)
Definition at line 115 of file jcom.delta2.cpp.
References t_delta2::clearflag, t_delta2::delta2, delta2_bang(), t_delta2::prev, and t_delta2::prev2.
Referenced by delta2_int(), and main().
void delta2_int (t_delta2 * x, long n)
Definition at line 105 of file jcom.delta2.cpp.
References delta2_float().
Referenced by main().
void * delta2_new (void)
Definition at line 80 of file jcom.delta2.cpp.
References delta2_clear(), and this_class.
Referenced by main().
void delta2_set (t_delta2 * x, Symbol * s, short ac, Atom * setval)
Definition at line 137 of file jcom.delta2.cpp.
References t_delta2::clearflag, t_delta2::delta2, t_delta2::prev, and t_delta2::prev2.
Referenced by main().
int main (void)
Definition at line 47 of file jcom.delta2.cpp.
References delta2_assist(), delta2_bang(), delta2_clear(), delta2_float(), delta2_int(), delta2_new(), delta2_set(), jamoma_init(), and this_class.
Variable Documentation
t_class* this_class
Definition at line 41 of file jcom.delta2.cpp.