Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.velocity/jcom.velocity.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.velocity/jcom.velocity.cpp File Reference
#include "jamoma.h"
Classes
struct t_velocity
Defines
#define nonzero(x) ((x > 0) ? x : 1.)
Functions
void * velocity_new (Symbol *s, short ac, Atom *arg)
void velocity_bang (t_velocity *x)
void velocity_int (t_velocity *x, long n)
void velocity_float (t_velocity *x, double f)
void velocity_set (t_velocity *x, Symbol *s, short ac, Atom *setval)
void velocity_assist (t_velocity *x, void *b, long m, long a, char *s)
int main (void)
Variables
t_class * this_class
Define Documentation
#define nonzero (x) ((x > 0) ? x : 1.)
Definition at line 14 of file jcom.velocity.cpp.
Referenced by velocity_bang().
Function Documentation
int main (void)
Definition at line 40 of file jcom.velocity.cpp.
References jamoma_init(), this_class, velocity_assist(), velocity_bang(), velocity_float(), velocity_int(), velocity_new(), and velocity_set().
void velocity_assist (t_velocity * x, void * b, long m, long a, char * s)
Definition at line 157 of file jcom.velocity.cpp.
Referenced by main().
void velocity_bang (t_velocity * x)
Definition at line 104 of file jcom.velocity.cpp.
References t_velocity::lasttime, nonzero, t_velocity::outlet, t_velocity::xn, and t_velocity::xn1.
Referenced by main(), velocity_float(), and velocity_int().
void velocity_float (t_velocity * x, double f)
Definition at line 126 of file jcom.velocity.cpp.
References velocity_bang(), t_velocity::xn, and t_velocity::xn1.
Referenced by main().
void velocity_int (t_velocity * x, long n)
Definition at line 117 of file jcom.velocity.cpp.
References velocity_bang(), t_velocity::xn, and t_velocity::xn1.
Referenced by main().
void * velocity_new (Symbol * s, short ac, Atom * arg)
Definition at line 71 of file jcom.velocity.cpp.
References this_class.
Referenced by main().
void velocity_set (t_velocity * x, Symbol * s, short ac, Atom * setval)
Definition at line 135 of file jcom.velocity.cpp.
References t_velocity::lasttime, t_velocity::xn, and t_velocity::xn1.
Referenced by main().
Variable Documentation
t_class* this_class
Definition at line 35 of file jcom.velocity.cpp.