Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.paramui/jcom.paramui.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.paramui/jcom.paramui.cpp File Reference
#include "jcom.paramui.h"
Functions
int main (void)
t_paramui * paramui_new (t_symbol *s, short argc, t_atom *argv)
void paramui_free (t_paramui *x)
void paramui_notify (t_paramui *x, t_symbol *s, t_symbol *msg, void *sender, void *data)
void paramui_paint (t_paramui *x, t_object *view)
void paramui_mousedown (t_paramui *x, t_object *patcherview, t_pt px, long modifiers)
void paramui_mousedragdelta (t_paramui *x, t_object *patcherview, t_pt pt, long modifiers)
void paramui_mouseup (t_paramui *x, t_object *patcherview)
void paramui_menu_do (t_paramui *x, t_object *patcherview, t_pt px, long modifiers)
void paramui_menu_qfn (t_paramui *x)
void paramui_menu_build (t_paramui *x)
void * paramui_oksize (t_paramui *x, t_rect *rect)
Variables
static t_class * s_ui_class = NULL
static t_jrgba s_light_gray = { 0.65, 0.65, 0.65, 1.0}
Function Documentation
int main (void)
Definition at line 21 of file jcom.paramui.cpp.
References FunctionLib::getUnitNames(), JAMOMA_DEFAULT_FONT, JAMOMA_DEFAULT_FONTSIZE, jamoma_getDataspaceList(), jamoma_init(), LISTSIZE, paramui_free(), paramui_getClipmode(), paramui_getDataspace(), paramui_getDefault(), paramui_getDescription(), paramui_getName(), paramui_getPriority(), paramui_getRampDrive(), paramui_getRampFunction(), paramui_getRange(), paramui_getRepetitions(), paramui_getStepsize(), paramui_getType(), paramui_getUIFreeze(), paramui_getUnitActive(), paramui_getUnitNative(), paramui_mousedown(), paramui_mousedragdelta(), paramui_mouseup(), paramui_new(), paramui_notify(), paramui_oksize(), paramui_paint(), paramui_setClipmode(), paramui_setDataspace(), paramui_setDefault(), paramui_setDescription(), paramui_setName(), paramui_setPriority(), paramui_setRampDrive(), paramui_setRampFunction(), paramui_setRange(), paramui_setRepetitions(), paramui_setStepsize(), paramui_setType(), paramui_setUIFreeze(), paramui_setUnitActive(), paramui_setUnitNative(), and s_ui_class.
void paramui_free (t_paramui * x)
Definition at line 284 of file jcom.paramui.cpp.
References t_paramui::box, t_paramui::layout_unit, t_paramui::layout_value, t_paramui::menu_items, t_paramui::menu_qelem, and t_paramui::obj_parameter.
Referenced by main().
void paramui_menu_build (t_paramui * x)
Definition at line 534 of file jcom.paramui.cpp.
References t_paramui::attr_name, and t_paramui::menu_items.
Referenced by paramui_new(), and paramui_notify().
void paramui_menu_do (t_paramui * x, t_object * patcherview, t_pt px, long modifiers)
Definition at line 482 of file jcom.paramui.cpp.
References JAMOMA_MENU_FONT, and JAMOMA_MENU_FONTSIZE.
Referenced by paramui_mousedown().
void paramui_menu_qfn (t_paramui * x)
Definition at line 525 of file jcom.paramui.cpp.
References t_paramui::menu_items, t_paramui::menu_selection, and t_paramui::obj_parameter.
Referenced by paramui_new().
void paramui_mousedown (t_paramui * x, t_object * patcherview, t_pt px, long modifiers)
Definition at line 455 of file jcom.paramui.cpp.
References paramui_menu_do().
Referenced by main().
void paramui_mousedragdelta (t_paramui * x, t_object * patcherview, t_pt pt, long modifiers)
Definition at line 467 of file jcom.paramui.cpp.
Referenced by main().
void paramui_mouseup (t_paramui * x, t_object * patcherview)
Definition at line 473 of file jcom.paramui.cpp.
Referenced by main().
t_paramui* paramui_new (t_symbol * s, short argc, t_atom * argv)
Definition at line 188 of file jcom.paramui.cpp.
References t_paramui::attr_clipmode, t_paramui::attr_dataspace, t_paramui::attr_default, t_paramui::attr_defaultSize, t_paramui::attr_description, t_paramui::attr_name, t_paramui::attr_priority, t_paramui::attr_rampDrive, t_paramui::attr_rampFunction, t_paramui::attr_range, t_paramui::attr_repetitions, t_paramui::attr_stepsize, t_paramui::attr_type, t_paramui::attr_uiFreeze, t_paramui::attr_unitActive, t_paramui::attr_unitNative, t_paramui::box, jcom_core_loadextern(), t_paramui::layout_unit, t_paramui::layout_value, LISTSIZE, t_paramui::menu_items, t_paramui::menu_qelem, t_paramui::obj_parameter, t_paramui::outlet, paramui_menu_build(), paramui_menu_qfn(), and s_ui_class.
Referenced by main().
void paramui_notify (t_paramui * x, t_symbol * s, t_symbol * msg, void * sender, void * data)
Definition at line 305 of file jcom.paramui.cpp.
References t_paramui::attr_label, t_paramui::box, and paramui_menu_build().
Referenced by main().
void* paramui_oksize (t_paramui * x, t_rect * rect)
Definition at line 556 of file jcom.paramui.cpp.
References s_light_gray.
Referenced by main().
void paramui_paint (t_paramui * x, t_object * view)
Definition at line 338 of file jcom.paramui.cpp.
References t_paramui::attr_dataspace, t_paramui::attr_type, t_paramui::box, JAMOMA_DEFAULT_FONT, JAMOMA_DEFAULT_FONTSIZE, t_paramui::layout_unit, t_paramui::layout_value, t_paramui::obj_parameter, ps_msg_float, ps_msg_int, ps_msg_symbol, ps_msg_toggle, ps_none, and s_light_gray.
Referenced by main().
Variable Documentation
t_jrgba s_light_gray = { 0.65, 0.65, 0.65, 1.0} [static]
Definition at line 15 of file jcom.paramui.cpp.
Referenced by paramui_oksize(), and paramui_paint().
t_class* s_ui_class = NULL [static]
Definition at line 14 of file jcom.paramui.cpp.
Referenced by main(), paramui_new(), and ui_new().