Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.paramui/jcom.paramui.attrs.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.paramui/jcom.paramui.attrs.cpp File Reference
#include "jcom.paramui.h"
Functions
t_max_err paramui_getName (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setName (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getType (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setType (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getDefault (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setDefault (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getRampDrive (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setRampDrive (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getRampFunction (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setRampFunction (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getUIFreeze (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setUIFreeze (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getStepsize (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setStepsize (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getPriority (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setPriority (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getRange (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setRange (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getRepetitions (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setRepetitions (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getClipmode (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setClipmode (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getDescription (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setDescription (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getDataspace (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setDataspace (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getUnitActive (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setUnitActive (t_paramui *x, void *attr, long argc, t_atom *argv)
t_max_err paramui_getUnitNative (t_paramui *x, void *attr, long *argc, t_atom **argv)
t_max_err paramui_setUnitNative (t_paramui *x, void *attr, long argc, t_atom *argv)
Function Documentation
t_max_err paramui_getClipmode (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 175 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getDataspace (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 212 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getDefault (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 45 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getDescription (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 191 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getName (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 13 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getPriority (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 125 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getRampDrive (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 61 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getRampFunction (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 77 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getRange (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 141 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getRepetitions (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 159 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getStepsize (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 109 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getType (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 29 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getUIFreeze (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 93 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getUnitActive (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 228 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_getUnitNative (t_paramui * x, void * attr, long * argc, t_atom ** argv)
Definition at line 244 of file jcom.paramui.attrs.cpp.
References t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setClipmode (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 181 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_clipmode, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setDataspace (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 218 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_dataspace, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setDefault (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 51 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_default, t_paramui::attr_defaultSize, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setDescription (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 197 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_description, t_paramui::obj_parameter, and ps_description.
Referenced by main().
t_max_err paramui_setName (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 19 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_name, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setPriority (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 131 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_priority, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setRampDrive (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 67 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_rampDrive, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setRampFunction (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 83 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_rampFunction, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setRange (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 147 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_range, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setRepetitions (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 165 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_repetitions, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setStepsize (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 115 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_stepsize, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setType (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 35 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_type, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setUIFreeze (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 99 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_uiFreeze, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setUnitActive (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 234 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_unitActive, and t_paramui::obj_parameter.
Referenced by main().
t_max_err paramui_setUnitNative (t_paramui * x, void * attr, long argc, t_atom * argv)
Definition at line 250 of file jcom.paramui.attrs.cpp.
References t_paramui::attr_unitNative, and t_paramui::obj_parameter.
Referenced by main().