Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.ramp/jcom.ramp.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.ramp/jcom.ramp.cpp File Reference
#include "Jamoma.h"
Classes
struct t_ramp
The Ramp.
Enumerations
enum outlets {
k_outlet_return = 0, k_outlet_dumpout, k_num_outlets, k_outlet_set = 0,
k_outlet_direct, k_outlet_dumpout, num_outlets, k_outlet_value = 0,
k_outlet_dumpout, num_outlets, k_outlet_thru = 0, k_outlet_dumpout,
num_outlets
}
Functions
void * ramp_new (t_symbol *s, long argc, t_atom *argv)
The jcom.ramp constructor.
void ramp_free (t_ramp *x)
The ramp deconstructor, free's any memory used by the object.
void ramp_assist (t_ramp *x, void *b, long msg, long arg, char *dst)
Method for Assistance Messages.
t_max_err ramp_setrampunit (t_ramp *x, void *attr, long argc, t_atom *argv)
Set what mechanism (RampUnit) is used to drive the ramp.
void ramp_setFunction (t_ramp *x, t_symbol *functionName)
Set the function to use when ramping.
void ramp_getFunction (t_ramp *x)
Get the function currently used when ramping.
void ramp_getFunctionParameter (t_ramp *obj, t_symbol *msg, long argc, t_atom *argv)
Get value of an additional parameter used for the function.
void ramp_setFunctionParameter (t_ramp *obj, t_symbol *msg, long argc, t_atom *argv)
Set additional parameters for the function currently used.
void ramp_clock (t_ramp *x, t_symbol *clockName)
Connect to a setclock object.
void ramp_bang (t_ramp *x)
Get a new value now.
void ramp_int (t_ramp *x, long n)
void ramp_float (t_ramp *x, double f)
void ramp_set (t_ramp *x, t_symbol *msg, long argc, t_atom *argv)
void ramp_list (t_ramp *x, t_symbol *msg, long argc, t_atom *argv)
void ramp_callback (void *v, short numvalues, double *values)
Triggered by our Ramp Unit's tick function.
void ramp_attrset (t_ramp *x, t_symbol *msg, long argc, t_atom *argv)
Set attribute value.
void ramp_attrget (t_ramp *x, t_symbol *msg, long argc, t_atom *argv)
Get attribute value.
int main (void)
Variables
t_class * ramp_class
Enumeration Type Documentation
enum outlets
Enumerator:
k_outlet_return
k_outlet_dumpout
k_num_outlets
k_outlet_set
k_outlet_direct
k_outlet_dumpout
num_outlets
k_outlet_value
k_outlet_dumpout
num_outlets
k_outlet_thru
k_outlet_dumpout
num_outlets
Definition at line 12 of file jcom.ramp.cpp.
Function Documentation
int main (void)
Definition at line 92 of file jcom.ramp.cpp.
References jamoma_init(), ramp_assist(), ramp_attrget(), ramp_attrset(), ramp_bang(), ramp_class, ramp_clock(), ramp_float(), ramp_free(), ramp_getFunctionParameter(), ramp_int(), ramp_list(), ramp_new(), ramp_set(), ramp_setFunction(), ramp_setFunctionParameter(), and ramp_setrampunit().
void ramp_assist (t_ramp * x, void * b, long msg, long arg, char * dst)
Method for Assistance Messages.
Definition at line 167 of file jcom.ramp.cpp.
References k_outlet_dumpout, and k_outlet_value.
Referenced by main().
void ramp_attrget (t_ramp * x, t_symbol * msg, long argc, t_atom * argv)
Get attribute value.
Definition at line 386 of file jcom.ramp.cpp.
References t_ramp::rampUnit.
Referenced by main().
void ramp_attrset (t_ramp * x, t_symbol * msg, long argc, t_atom * argv)
Set attribute value.
Definition at line 364 of file jcom.ramp.cpp.
References t_ramp::rampUnit.
Referenced by main().
void ramp_bang (t_ramp * x)
Get a new value now.
Definition at line 289 of file jcom.ramp.cpp.
References t_ramp::rampUnit, and RampUnit::tick().
Referenced by main().
void ramp_callback (void * v, short numvalues, double * values)
Triggered by our Ramp Unit's tick function.
Definition at line 270 of file jcom.ramp.cpp.
References k_outlet_value, and t_ramp::outlets.
Referenced by ramp_setrampunit().
void ramp_clock (t_ramp * x, t_symbol * clockName)
Connect to a setclock object.
Definition at line 263 of file jcom.ramp.cpp.
References t_ramp::rampUnit.
Referenced by main().
void ramp_float (t_ramp * x, double f)
Definition at line 306 of file jcom.ramp.cpp.
References k_outlet_value, t_ramp::outlets, t_ramp::rampUnit, and RampUnit::set().
Referenced by main().
void ramp_free (t_ramp * x)
The ramp deconstructor, free's any memory used by the object.
Definition at line 157 of file jcom.ramp.cpp.
References t_ramp::rampUnit.
Referenced by main().
void ramp_getFunction (t_ramp * x)
Get the function currently used when ramping.
void ramp_getFunctionParameter (t_ramp * obj, t_symbol * msg, long argc, t_atom * argv)
Get value of an additional parameter used for the function.
Definition at line 190 of file jcom.ramp.cpp.
References RampUnit::getFunctionParameterValue(), and t_ramp::rampUnit.
Referenced by main().
void ramp_int (t_ramp * x, long n)
Definition at line 296 of file jcom.ramp.cpp.
References k_outlet_value, t_ramp::outlets, t_ramp::rampUnit, and RampUnit::set().
Referenced by main().
void ramp_list (t_ramp * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 330 of file jcom.ramp.cpp.
References RampUnit::go(), and t_ramp::rampUnit.
Referenced by main().
void * ramp_new (t_symbol * s, long argc, t_atom * argv)
The jcom.ramp constructor.
Definition at line 134 of file jcom.ramp.cpp.
References k_outlet_dumpout, k_outlet_value, t_ramp::outlets, and ramp_class.
Referenced by main().
void ramp_set (t_ramp * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 314 of file jcom.ramp.cpp.
References t_ramp::rampUnit, and RampUnit::set().
Referenced by main().
void ramp_setFunction (t_ramp * x, t_symbol * functionName)
Set the function to use when ramping.
Definition at line 184 of file jcom.ramp.cpp.
References t_ramp::rampUnit.
Referenced by main().
void ramp_setFunctionParameter (t_ramp * obj, t_symbol * msg, long argc, t_atom * argv)
Set additional parameters for the function currently used.
Definition at line 231 of file jcom.ramp.cpp.
References t_ramp::rampUnit, and RampUnit::setFunctionParameterValue().
Referenced by main().
t_max_err ramp_setrampunit (t_ramp * x, void * attr, long argc, t_atom * argv)
Set what mechanism (RampUnit) is used to drive the ramp.
Definition at line 255 of file jcom.ramp.cpp.
References t_ramp::attr_rampunit, RampLib::createUnit(), ramp_callback(), and t_ramp::rampUnit.
Referenced by main().
Variable Documentation
t_class* ramp_class
Definition at line 86 of file jcom.ramp.cpp.
Referenced by main(), and ramp_new().