Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.time/jcom.time.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.time/jcom.time.cpp File Reference
#include "Jamoma.h"
Classes
struct t_jcom_time
Functions
void * jcom_time_new (t_symbol *s, long argc, t_atom *argv)
void jcom_time_free (t_jcom_time *x)
void jcom_time_rewind (t_jcom_time *x)
int main (void)
Variables
static t_class * jcom_time_class
Function Documentation
void jcom_time_free (t_jcom_time * x)
Definition at line 71 of file jcom.time.cpp.
Referenced by main().
void * jcom_time_new (t_symbol * s, long argc, t_atom * argv)
Definition at line 59 of file jcom.time.cpp.
References jcom_time_class.
Referenced by main().
void jcom_time_rewind (t_jcom_time * x)
Definition at line 79 of file jcom.time.cpp.
References jamoma_scheduler_rewind().
Referenced by main().
int main (void)
Definition at line 32 of file jcom.time.cpp.
References jamoma_init(), jcom_time_class, jcom_time_free(), jcom_time_new(), and jcom_time_rewind().
Variable Documentation
t_class* jcom_time_class [static]
Definition at line 26 of file jcom.time.cpp.
Referenced by jcom_time_new(), and main().