Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.map/jcom.map.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.map/jcom.map.cpp File Reference
#include "Jamoma.h"
Classes
struct t_map
Functions
void * map_new (t_symbol *name, long argc, t_atom *argv)
void map_free (t_map *obj)
void map_assist (t_map *obj, void *b, long m, long a, char *s)
void map_int (t_map *obj, long x)
void map_float (t_map *obj, double x)
void map_getFunctions (t_map *x, t_symbol *msg, long argc, t_atom *argv)
void map_getParameter (t_map *x, t_symbol *msg, long argc, t_atom *argv)
void map_getFunctionParameters (t_map *x, t_symbol *msg, long argc, t_atom *argv)
void map_setParameter (t_map *x, t_symbol *msg, long argc, t_atom *argv)
t_max_err map_setFunction (t_map *obj, void *attr, long argc, t_atom *argv)
t_max_err map_setInputMin (t_map *obj, void *attr, long argc, t_atom *argv)
t_max_err map_setInputMax (t_map *obj, void *attr, long argc, t_atom *argv)
void map_scaleInput (t_map *obj)
t_max_err map_setOutputMin (t_map *obj, void *attr, long argc, t_atom *argv)
t_max_err map_setOutputMax (t_map *obj, void *attr, long argc, t_atom *argv)
void map_scaleOutput (t_map *obj)
int main (void)
void map_doSetFunction (t_map *obj, t_symbol *newFunctionName)
Variables
t_class * map_class
Function Documentation
int main (void)
Definition at line 56 of file jcom.map.cpp.
References jamoma_init(), map_assist(), map_class, map_float(), map_free(), map_getFunctionParameters(), map_getFunctions(), map_getParameter(), map_int(), map_new(), map_setFunction(), map_setInputMax(), map_setInputMin(), map_setOutputMax(), map_setOutputMin(), and map_setParameter().
void map_assist (t_map * obj, void * b, long m, long a, char * s)
Definition at line 145 of file jcom.map.cpp.
Referenced by main().
void map_doSetFunction (t_map * obj, t_symbol * newFunctionName)
Definition at line 291 of file jcom.map.cpp.
References t_map::attr_function, FunctionLib::createUnit(), t_map::functionUnit, and t_map::valid.
Referenced by map_setFunction().
void map_float (t_map * obj, double x)
Definition at line 164 of file jcom.map.cpp.
References t_map::a, t_map::b, t_map::c, t_map::d, t_map::functionUnit, FunctionUnit::map(), t_map::outlet, and t_map::valid.
Referenced by main(), and map_int().
void map_free (t_map * obj)
Definition at line 134 of file jcom.map.cpp.
References t_map::functionUnit.
Referenced by main().
void map_getFunctionParameters (t_map * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 241 of file jcom.map.cpp.
References t_map::functionUnit.
Referenced by main().
void map_getFunctions (t_map * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 175 of file jcom.map.cpp.
References t_map::attr_function, and FunctionLib::getUnitNames().
Referenced by main().
void map_getParameter (t_map * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 200 of file jcom.map.cpp.
References t_map::functionUnit.
Referenced by main().
void map_int (t_map * obj, long x)
Definition at line 158 of file jcom.map.cpp.
References map_float().
Referenced by main().
void * map_new (t_symbol * name, long argc, t_atom * argv)
Definition at line 109 of file jcom.map.cpp.
References map_class, map_scaleInput(), and map_scaleOutput().
Referenced by main().
void map_scaleInput (t_map * obj)
Definition at line 326 of file jcom.map.cpp.
References t_map::a, t_map::attr_inputMax, t_map::attr_inputMin, and t_map::b.
Referenced by map_new(), map_setInputMax(), and map_setInputMin().
void map_scaleOutput (t_map * obj)
Definition at line 360 of file jcom.map.cpp.
References t_map::attr_outputMax, t_map::attr_outputMin, t_map::c, and t_map::d.
Referenced by map_new(), map_setOutputMax(), and map_setOutputMin().
t_max_err map_setFunction (t_map * obj, void * attr, long argc, t_atom * argv)
Definition at line 298 of file jcom.map.cpp.
References map_doSetFunction(), and t_map::valid.
Referenced by main().
t_max_err map_setInputMax (t_map * obj, void * attr, long argc, t_atom * argv)
Definition at line 317 of file jcom.map.cpp.
References t_map::attr_inputMax, and map_scaleInput().
Referenced by main().
t_max_err map_setInputMin (t_map * obj, void * attr, long argc, t_atom * argv)
Definition at line 308 of file jcom.map.cpp.
References t_map::attr_inputMin, and map_scaleInput().
Referenced by main().
t_max_err map_setOutputMax (t_map * obj, void * attr, long argc, t_atom * argv)
Definition at line 351 of file jcom.map.cpp.
References t_map::attr_outputMax, and map_scaleOutput().
Referenced by main().
t_max_err map_setOutputMin (t_map * obj, void * attr, long argc, t_atom * argv)
Definition at line 341 of file jcom.map.cpp.
References t_map::attr_outputMin, and map_scaleOutput().
Referenced by main().
void map_setParameter (t_map * x, t_symbol * msg, long argc, t_atom * argv)
Definition at line 268 of file jcom.map.cpp.
References t_map::functionUnit.
Referenced by main().
Variable Documentation
t_class* map_class
Definition at line 50 of file jcom.map.cpp.
Referenced by main(), and map_new().