Jamoma: /Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.mkdir/mkdir.cpp File Reference
/Users/tim/dev/Jamoma/SourceCode/MaxObjects/jcom.mkdir/mkdir.cpp File Reference
#include "Jamoma.h"
Classes
struct t_mkdir
Functions
void * mkdir_new (void)
void mkdir_free (t_mkdir *x)
void mkdir_assist (t_mkdir *x, void *b, long m, long a, char *s)
void mkdir_make (t_mkdir *x, t_symbol *s, long argc, t_atom *argv)
void mkdir_domake (t_mkdir *x, t_symbol *s, long argc, t_atom *argv)
int main (void)
Variables
static t_class * mkdir_class
Function Documentation
int main (void)
Definition at line 31 of file mkdir.cpp.
References jamoma_init(), mkdir_assist(), mkdir_class, mkdir_free(), mkdir_make(), and mkdir_new().
void mkdir_assist (t_mkdir * x, void * b, long m, long a, char * s)
Definition at line 73 of file mkdir.cpp.
Referenced by main().
void mkdir_domake (t_mkdir * x, t_symbol * s, long argc, t_atom * argv)
Definition at line 91 of file mkdir.cpp.
Referenced by mkdir_make().
void mkdir_free (t_mkdir * x)
Definition at line 66 of file mkdir.cpp.
Referenced by main().
void mkdir_make (t_mkdir * x, t_symbol * s, long argc, t_atom * argv)
Definition at line 85 of file mkdir.cpp.
References mkdir_domake().
Referenced by main().
void * mkdir_new (void)
Definition at line 53 of file mkdir.cpp.
References mkdir_class.
Referenced by main().
Variable Documentation
t_class* mkdir_class [static]
Definition at line 27 of file mkdir.cpp.
Referenced by main(), and mkdir_new().